### ISSUE TITLE
Can't set up ofscraper properly

### ISSUE THREAD

**Issue by chrome2ru** [datawhores/OF-Scraper#100]
Hello. Tell me how to set up ofscraper so that it downloads all my Subscriptions of them 61

**Comment by ctrlcmdshft** [comment]
Follow guides here https://of-scraper.gitbook.io/of-scraper/

**Comment by cjb900** [comment]
Information on how to install and use this scrapper can be found here https://of-scraper.gitbook.io/of-scraper/installation

**Comment by datawhores** [comment]
Use the binaries if you cant  install though I would recommend installing though python if you can
