### ISSUE TITLE
jpeg not jpg

### ISSUE THREAD

**Issue by ResidentSpaceDragon** [datawhores/OF-Scraper#101]
The script is downloading as 'jpeg' where it used  to be 'jpg'

**Comment by RonnieBlaze** [comment]
if you are on widows, you can use this from command prompt,  ive just been renaming them.

forfiles /S /M *.jpeg /C "cmd /c rename @file @fname.jpg"

**Comment by datawhores** [comment]
Im using whatever the onlyfans returns from the api

**Comment by ResidentSpaceDragon** [comment]
I've never encountered a jpeg file before on OF in years, even with the browser extensions, DC's script and even the sources inspector, they are all jpg.You can even check the metadata db and see the media URL ends in .jpg

> {ext if ext!="jpeg" else "jpg"}
> 
> Make sure code executive is True in the config so that line can be eval

This does not work,i throws a syntax error,with "code-execution": true

**Comment by datawhores** [comment]
This is an example of a jpeg

https://onlyfans.com/4704529/francety

**Comment by datawhores** [comment]
{ext if ext!=\"jpeg\" else \"jpg\"}

**Comment by avekifes** [comment]
If I rename the .jpeg files to .jpg, is ofscraper going to download everything again?

Also, I'm not seeing any .jpegs at the OF link posted above...

...but if it's really what OF's API is returning, then I'm fine with this.

**Comment by datawhores** [comment]
It always redownload if you have the dupe option on

Otherwise no

Yeah the API is inconsistent in some places including jpg vs jpeg
