### ISSUE TITLE
Release Notifications

### ISSUE THREAD

**Issue by Nostang3** [datawhores/OF-Scraper#109]
I just wanted to make you aware that the release section is alerting every time you make a commit or something. It used to only notify on numbered version releases, now it's saying things like: package_8b1cd7e. Sometimes multiple time a minute. If this is how you want it please disregard.

**Comment by datawhores** [comment]
I turned it off the change causing this for now

Trying to figure something out

**Comment by datawhores** [comment]
Releases are out
