### ISSUE TITLE
Feature Request: Download Resume - or give URL for manual downloading

### ISSUE THREAD

**Issue by ShadowSteve1** [datawhores/OF-Scraper#112]
Hi

I've noticed with this script even though stuff gets downloaded into a .part file it never actually tries to resume a download from where it left off.

it would be good if it could use the part file to resume where it left off - or failing that spit out a URL we could manually go to and grab whatever failed.

it's mostly large video files that i have this issue on.

**Comment by xxx-uploaded** [comment]
Similar problem
![Screenshot_2](https://github.com/datawhores/OF-Scraper/assets/88721958/84f6a0e8-a111-4598-8dc4-09b8c5df9af1)

**Comment by datawhores** [comment]
I've added this along with a config and args to cleanup part files if desired

of course if you delete part files this removes the ability to resume files
Might be good to do once to delete all the legacy files
