### ISSUE TITLE
OF and encrypted content

### ISSUE THREAD

**Issue by goodboi69691** [datawhores/OF-Scraper#113]
Does this scrapper handle DRM content?
If not, will it?
Is there a way to detect what content is DRM via the scrapper or manually?

**Comment by datawhores** [comment]
--download-type protecred

**Comment by goodboi69691** [comment]
> --download-type protecred

Does it un-encrypt the content?

**Comment by goodboi69691** [comment]
> --download-type protected Add that to the path Example Normally you run
> 
> ofscraper
> 
> Now you would run
> 
> ofscraper --download-type protected

Does it un-encrypt the content?

**Comment by datawhores** [comment]
Yes
