### ISSUE TITLE
[Feature Request] - Option to output only what was downloaded

### ISSUE THREAD

**Issue by ondrovic** [datawhores/OF-Scraper#115]
I have looked the following options, and tried most  of the combinations to attempt to get only the output that I wanted but haven't been very successful.

```python
# Logging:
-l
-dc
-p
```

I was hoping for an option to only output the following

```python
[download.process_dicts:133]  {username} (0 photos, 0 videos, 0 audios,  0 skipped)                download.py:133
```

Maybe there is already an option but  tired `-l OFF -dc OFF -p STATS`

**Comment by datawhores** [comment]
what wrong with stats it outputs exactly that

**Comment by datawhores** [comment]
Their is no output flag

**Comment by datawhores** [comment]
What are you see on your end?
It should be just that and the timers

If you want to hide the timers I can add an option for that

**Comment by datawhores** [comment]
What version

**Comment by datawhores** [comment]
oh I see do you know which exe you got specifically

Also does it work if you just do ofscaper.exe -p stats

**Comment by datawhores** [comment]
This issue is not happening on linux so it might be related to the terminal program

What are you using in the screenshot above

**Comment by datawhores** [comment]
okay I can't recreate this issue

Though I will note a few things
if you set the output to low then that supresses all output including indications of process for example
The one that indicates that usernames are being retrived.

Which may make it seem that the program is frozen when in reality username retrieval is taking a bit

If your going to use --output low I would highly recommend pass --username option --excluded-username option if needed
Along with --post 

That way you can skip any menus
