### ISSUE TITLE
Just getting PART files

### ISSUE THREAD

**Issue by sweetcatastrophe** [datawhores/OF-Scraper#116]
Sorry if I'm being dumb, first time using this script!

I got it to download some content but then it just started getting part files which never get finalized into video files and they are removed when the script finishes. 

Am I doing something wrong, how can I fix it?

**Comment by 5n0wstorm** [comment]
It's because cdrm-project.com is currently down. This script relies on that website to decrypt widevine-encrypted videos.

**Comment by josemerinom** [comment]
:(

**Comment by datawhores** [comment]
The a bypass in the discord does require setup
