### ISSUE TITLE
Encrypted Content

### ISSUE THREAD

**Issue by dgauge1** [datawhores/OF-Scraper#118]
Hello. On the command prompt, I put in this to download the DRM content:

ofscraper  --username name1 --posts timeline    --download-type protected

When the files were downloading, it kept on skipping. I would only get PART files.

I would like to know, did I make an error with the path? 

Thanks in advance.

**Comment by datawhores** [comment]
Discord

**Comment by dgauge1** [comment]
> Discord

Can you explain what that means?

**Comment by basketballhead6** [comment]
> > Discord
> 
> 
> 
> Can you explain what that means? 

There is currently an issue with the site that provides the keys for DRM content being down. If you join the discord you can find the manual workaround until the site returns.

**Comment by dgauge1** [comment]
> > > Discord
> > 
> > 
> > Can you explain what that means?
> 
> There is currently an issue with the site that provides the keys for DRM content being down. If you join the discord you can find the manual workaround until the site returns.

Ahh okay. Thank you.
