### ISSUE TITLE
not an issue 

### ISSUE THREAD

**Issue by yourgodfather12** [datawhores/OF-Scraper#119]
Is there anyway to add a skip feature? I have some profile that have 17k posts and have slow DSL 20mbps internet so its taking days lol

**Comment by basketballhead6** [comment]
You can choose to only select specific models instead of all of them

**Comment by basketballhead6** [comment]
> Is there anyway to add a skip feature? I have some profile that have 17k posts and have slow DSL 20mbps internet so its taking days lol

Also see issue #114 as a way to 'blacklist' models
