### ISSUE TITLE
pinned content not downloaded

### ISSUE THREAD

**Issue by ghost** [datawhores/OF-Scraper#122]
for a certain model i noticed that i was missing some timeline images. they turned out to be pinned posts from this month: 2 free posts with a single image, and 1 locked post with a preview image. running the download for all content types including 'timeline' and 'pinned' doesn't find them. using `post_check` i'm able to find the locked post but not the free posts. i ended up passing the url to `manual` but then it goes to `/Post` and not `/Posts`

2.7.1 pipx

**Comment by datawhores** [comment]
you run
--log trace --post pinned


Try to see if the text from the post at least appear

It will be a little slower and print off a bunch of text to the file

**Comment by datawhores** [comment]
Add --trace so I can see the JSON response from the api

**Comment by datawhores** [comment]
Yeah I don't know 
I would need to see some logs
Preferably --trace so and maybe details of the post you looking for

**Comment by datawhores** [comment]
@gootzoot 
How many pinned post do they have?

**Comment by datawhores** [comment]
This may have been fixed with a fix I made to fix a infinite loop bug
