### ISSUE TITLE
how to transfer .config folder

### ISSUE THREAD

**Issue by chrome2ru** [datawhores/OF-Scraper#123]
can you tell me how to transfer the .config folder from C:\Users\XXXXXX to disk d

**Comment by cjb900** [comment]
last I knew the config folder can not be moved

**Comment by datawhores** [comment]
--config full paths to new folder

**Comment by chrome2ru** [comment]
> --config полные пути к новой папке

Can you be more specific?
what to write where

**Comment by cjb900** [comment]
`ofscraper --config <path you want to move it to>` with out the <>

**Comment by chrome2ru** [comment]
I understand correctly that this is only for the Python version

**Comment by datawhores** [comment]
They are the same program?

The args would be the same

**Comment by Puk0** [comment]
1. "Simbolo del sistema"
2. cd C:\Users\***\Documents\OF-Scraper\           + ENTER
3. "ofscraper_windows_ac6969c.exe" --config Configuraciones
...
![2023-07-13_004236](https://github.com/datawhores/OF-Scraper/assets/138377242/9f08b00c-e1d2-4b99-aa42-911600bcfc40)

**Comment by chrome2ru** [comment]
> --config full paths to new folder

thanks, there is a suggestion to make this function customizable in the program.

**Comment by datawhores** [comment]
It is very dynamic now
You can for example pass
--config /d/test.ext

If you want to change the name of the file 
It goes though some checks to see if a condition is true if not it checks the next one

https://of-scraper.gitbook.io/of-scraper/batch-scraping-and-bot-actions/advanced-args#multiple-configs
