### ISSUE TITLE
Minor: For some reason Windows username of 't' results in the letter 't' being replaced with "your_username' everywhere...

### ISSUE THREAD

**Issue by thisisme79** [datawhores/OF-Scraper#128]
Windows username is:
C:\Users\t

when running ofscraper it results in output that looks like this:

`
 [syour_usernamearyour_username.syour_usernamearyour_usernamevalues:47]  config payour_usernameh: C:\Users\your_username\.config\ofscraper\config.json                                     start.py:47
 [syour_usernamearyour_username.syour_usernamearyour_usernamevalues:48]  profile payour_usernameh: C:\Users\your_username\.config\ofscraper\main_profile                             	   start.py:48
 [syour_usernamearyour_username.syour_usernamearyour_usernamevalues:49]  log folder: C:\Users\your_username\.config\ofscraper\logging
`

Where the letter 't' is replaced with 'your_username' even in places that wouldn't appear to be related...
I assume the first sentence was supposed to be 'start.startvalues' but the letter 't' was replaced with 'your_username' throughout...

It still seems to download without issue, it is just odd

**Comment by datawhores** [comment]
Your name selection is kind of an edge cause.

I think being more specific here would probably fix the issue

**Comment by datawhores** [comment]
This should be fixed as I included the surrounded special characters
