### ISSUE TITLE
did need reinstall win 11 after run

### ISSUE THREAD

**Issue by Fall0n** [datawhores/OF-Scraper#129]
Is there a fix that i dont need reinstall win 11 every time i run this?

**Comment by datawhores** [comment]
Did you get a blue screen
What forced you to reinstall

**Comment by Jules-WinnfieldX** [comment]
Very confused here, I run this on win 11 without issue. Doesn't really make sense a python program would break to the point that you'd need to reinstall the OS.

**Comment by datawhores** [comment]
There has been no response and this seems unlikely to be caused by a python script
