### ISSUE TITLE
mp4 decrypt not being detected

### ISSUE THREAD

**Issue by penguinpatrol** [datawhores/OF-Scraper#130]
as you can see in the images it is being directed to the right place i believe but it refuses to detect the .exe I'm using the "ofscraper_windows_d6555cc.exe"

![image](https://github.com/datawhores/OF-Scraper/assets/117539617/238121da-441c-458b-b70d-e89fd6c929fc)

![image](https://github.com/datawhores/OF-Scraper/assets/117539617/219e65f0-5b94-4dd9-9cb0-bd52ac29130a)

**Comment by cjb900** [comment]
Because you have to actually put the mp4decrypt file name in the file path it's self like `C:\Users\cslar\Downloads\OFTEST\config\Bento4-SDK-1-6-0-640.x86_64-microsoft-win32\bin\mp4decrypt`

**Comment by penguinpatrol** [comment]
thanks but what do i have to do for ffmpeg?

![image](https://github.com/datawhores/OF-Scraper/assets/117539617/f10b0500-0af8-40b6-bae8-585dbb7f8a3f)

**Comment by cjb900** [comment]
You have to either fully install ffmpeg then provide the path to where it installed to or download the portable exe version

**Comment by Puk0** [comment]
> thanks but what do i have to do for ffmpeg?
> 

ffmpeg 6.0 essentials > https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
solo extrae el \bin\ffmpeg.exe
