### ISSUE TITLE
Still can't figure DRM videos out

### ISSUE THREAD

**Issue by avekifes** [datawhores/OF-Scraper#131]
I seem to have everything correct, but DRM videos still aren't downloading for me.

Files:

client_id.bin
private_key.pem

Relevant lines from config file:

"mp4decrypt": "C:\\Users\\username\\Desktop\\OF-Scraper-main\\mp4decrypt.exe",
"ffmpeg": "C:\\Users\\username\\Desktop\\OF-Scraper-main\\ffmpeg.exe",
"private-key": "C:\\Users\\username\\Desktop\\OF-Scraper-main\\keys\\private_key.pem",
"client-id": "C:\\Users\username\\Desktop\\OF-Scraper-main\\keys\\client_id.bin",
"key-mode-default": "manual",

But I'm still only getting .part files that look like this:

tempaudio_0hfbatozgxm9fu595ye6g_audio.mp4.part
tempvid_0hfbatozgxm9fu595ye6g_source.mp4.part

**Comment by Puk0** [comment]
cuando te sale eso es porque
No funcionan los 2 archivos cdm
No los desencripta y asi los deja, y no los une en un solo archivo (_source.mp4)

Porque funcionan con los nombres que quieras y con o sin extensión
