### ISSUE TITLE
[BUG] {media_id} is reported as improper syntax or invalid placeholder during config configuration.

### ISSUE THREAD

**Issue by Jules-WinnfieldX** [datawhores/OF-Scraper#132]
I prefer to have my filenames be of format: `{model_username} - {date} - {media_id}.{ext}`

Trying to diagnose a different issue I am having, I cannot get past the filename format section of the config configurator without removing media_id from the input despite it being a valid option.

**Comment by datawhores** [comment]
I can add this 
Are you on a stable or git release

**Comment by Jules-WinnfieldX** [comment]
I forgot to reply to this, I'm on stable release. I ended up just removing and then editing the config afterwards to re-add it. Just thought it should be noted

**Comment by datawhores** [comment]
Oh yeah I had to remove the  prompt validators for the placeholder values
The user will just have to self confirm that the option is current now.

**Comment by kotori2** [comment]
I'm wondering if we could update the documentation on placeholders? [The current one](https://of-scraper.gitbook.io/of-scraper/config-options/file-output-options/customizing-save-path) is missing a lot of them.

**Comment by datawhores** [comment]
I take another look tomorrow and see what I missed

**Comment by datawhores** [comment]
I added some missing placeholders 
They should all be there 
The no underline version should work as well l, but they are not mentioned directly too keep things short
