### ISSUE TITLE
Loop and .part files

### ISSUE THREAD

**Issue by original-copy** [datawhores/OF-Scraper#135]
I noticed that for some models, the download loops (i.e. after downloading a file, the system re-downloads the same file). Using 2023.07.26_14:59_main_de9ebfc_package.

Also, rather than combining to a single mp4 file, I get an audio & source file separately with a ".part" extension.

xxx_audio.mp4.part
xxx_source.mp4.part

Anyone has any idea how to resolve this?

**Comment by datawhores** [comment]
Do you have the manual option setup
check the discord if not
