### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by tim1f1** [datawhores/OF-Scraper#136]
Uninstalled and reinstalled the scraper, now it gives me this error message when I try to run it
![image](https://github.com/datawhores/OF-Scraper/assets/16625605/fde8ef94-b346-4c2d-9e66-b7bf907d1535)

**Comment by Puk0** [comment]
pip install pycryptodome

**Comment by datawhores** [comment]
Yeah this issue was very weird

I think I may have been able to fix it by reseting the requirments file
check 2.7.8

**Comment by tim1f1** [comment]
> pip install pycryptodome

Tells me that the requirement is already satisfied and still gives me the same error when I try to run the program

**Comment by datawhores** [comment]
Okay it seems maybe your enviroment has issue

Try running these commands
pip3 uninstall crypto 
pip3 uninstall pycrypto 
pip3 install pycryptodome
