### ISSUE TITLE
what does *pushing discord queue* mean?.  program is crashing

### ISSUE THREAD

**Issue by mama-miaWhatAkia** [datawhores/OF-Scraper#142]
![Screenshot 2023-08-01 042400](https://github.com/datawhores/OF-Scraper/assets/141093257/ff6ca462-6ce7-4e88-a8f9-47cf51e5fc5f)

i press enter on download from a user then this line shows up and the program crashes

**Comment by mama-miaWhatAkia** [comment]
also the discord invite link has been expired.

**Comment by Puk0** [comment]
Lo de "Discord" ("discord": "",) >https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

https://discord.gg/xBzPT4mGhb

**Comment by datawhores** [comment]
a queue is used for discord since it is much slower then logging to a file or console
This has been changed in upcoming 3.0 to be less intrusive

can you show the output of 
--output debug so I can gain more info
