### ISSUE TITLE
what are these .part files

### ISSUE THREAD

**Issue by chrome2ru** [datawhores/OF-Scraper#143]
files with the .part extension began to fall
here is an example
tempvid_0hg6m5x0wl4htkj9dpjas_source.mp4.part
tempaudio_0herihv0v2hoq1ktllznd_audio.mp4.part
on many models

**Comment by It5Ju5t4Fun** [comment]
Just started getting these as well, not all of them come through this way, but a handful from different models.  Link to discord for more info or anyone have some fix?
