### ISSUE TITLE
It doesn't download well.

### ISSUE THREAD

**Issue by rciptv2019** [datawhores/OF-Scraper#144]
You do not have the problem now that when you are supposed to have downloaded the content, you get the files like this?:
tempvid_0he9xj9hcvgr1zy4n6pm7_source.mp4.part
.
.
.

**Comment by cjb900** [comment]
This means the contact it DRM protected so its not able to fully download. You need to join the [discord](https://discord.gg/wN7uxEVHRK) to get the instruction on how to be able to get the manual DRM keys to then be able to download DRM content. The sites that were being used for automatic DRM key retrieval are down and no word on when they will back backup.

**Comment by datawhores** [comment]
https://github.com/datawhores/OF-Scraper/issues/145
