### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by djmarioka** [datawhores/OF-Scraper#147]
Hi,

I don't know if it's because I'm using Wi-fi now (because I'm currently in travel), but it goes so slow.. is it normal? 

Let me know.

Thanks.

**Comment by datawhores** [comment]
Do you have an idea of what version your on

**Comment by datawhores** [comment]
Also I would maybe try to do a speedtest or use something like.
https://www.thinkbroadband.com/download

To check it is not your speed

**Comment by djmarioka** [comment]
> Do you have an idea of what version your on

The version is 2.7.8

**Comment by datawhores** [comment]
It could be many things
run with --output debug to make sure it isn't errorring out 

Also with your statement

**Comment by datawhores** [comment]
You could also try 3.0 and turn the number of threads up

**Comment by djmarioka** [comment]
How could I upgrade? Which command should I use?

**Comment by datawhores** [comment]
depends on how you installed 
pip or pipx
