### ISSUE TITLE
Scraper isn't getting all media and still ending up with part files even with keys selected

### ISSUE THREAD

**Issue by hmmark1984** [datawhores/OF-Scraper#148]
I'm currently scraping an account that has 1915 photos and 702 videos, after the scraper runs i end up with only 1790 pictures and 530 videos

I'm using 2.7.10

I think part of the issue is that the oldest media the script grabs is dated 29-12-2020 however the account i'm scrapping has pics and vids going back to December 2019. I''m telling the scrapper to grab every option given, so it's not that.

Yesterday i went through the process of creating my own keys, however i'm still getting .part files in the videos folder, specifically 70 of them, i assume i've done something wrong, here's my config.json settings ![Untitled](https://github.com/datawhores/OF-Scraper/assets/98670010/93836585-52ef-4541-964a-406ab8cd1293)

The script can "see" all the media as it shows 1915 photos and 702 vids and 1 archived post, when it first starts. Under the progress read out it only ends up showing 34 as "skipped". I've seen it said the difference in media numbers between those on the account and those scraped, might be due to duplicates, but that doesn't explain it not getting anything prior to Dec 2020. I believe my file naming convention should mean it doesn't have any duplicates as i use {date}-{text}#{media_id}.{ext} in the past i used DigitalCriminals script, when it worked, and i used the same naming convention, so i don't believe there should be any issues with duplicates as that script grabbed everything bar maybe a couple pics

Please note i'm not claiming that script was better, not only is this one kept up to date but it's a lot easier to use/run and better in pretty much every way. i'm just saying that i know it should be able to get more than it currently is. The script also takes around 3hrs 30mins to scrape that one account, even when selecting False for "scrape entire paid page" is that normal as i have 1GB download speeds.

I've attached a debug log, any help is appreciated.

[ofscraper_main_profile_2023-08-03.log](https://github.com/datawhores/OF-Scraper/files/12250125/ofscraper_main_profile_2023-08-03.log)

**Comment by datawhores** [comment]
You can try to switch to httpx backend via the advanced config menu to see if that is faster on your system

**Comment by datawhores** [comment]
3.0 should also be a little faster when it is ready

**Comment by hmmark1984** [comment]
Ok, I'll see if I can figure it out how to do that, although the speed
issue I can live with, it's why I'm still getting part files even with keys
and why, even if I count the part files, it's not grabbing all the files.

I'm currently running with the --dupe suffix as I beilive that grabs
everything, without excluding dupes, but so far it looks to be getting no
more than my last scrape

**Comment by datawhores** [comment]
try to run with 
--no-cache

**Comment by datawhores** [comment]
I message on discord but I can't find any indication that the post on this account came from before dec 2020

**Comment by datawhores** [comment]
This model only has 2834 post on her account
the scraper is find 2830 unduped timeline post

So that means they all have unique counts

**Comment by hmmark1984** [comment]
> I message on discord but I can't find any indication that the post on this account came from before dec 2020

yes, sorry about that, i see now that she must've, for some reason, deleted her earlier content. so that issue appears to be my fault.


> This model only has 2834 post on her account the scraper is find 2830 unduped timeline post
> 
> So that means they all have unique counts

yes, she has 2834 posts, of which 2620 are media with 1917 of those being photos and 703 of them being videos, however the scrapper only gets around 1817 photos and 530 videos with the exact number fluctuating a little each time i try.

Also, even though i'm pretty sure i've got the keys set up correctly, i'm still ending up with 66 .part files totalling over 37GB in the videos folder. none are present in the photos folder though.

**Comment by datawhores** [comment]
Some files seem to be failing to get proper rename values
I've added a change in 3.0 to normalize the path across operating system.

Theres also a few trace values that can show the different calculated values of the final path via 
--output trace

--output debug will also show more information about the calculated paths now as the files download
