### ISSUE TITLE
Error when launching OF-Scraper in OSX

### ISSUE THREAD

**Issue by BosonHair** [datawhores/OF-Scraper#149]
Lately been getting this error and a pop up that python crashed:

objc[69266]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[69266]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

Using v2.7.12. I also tried the latest dev build to see if it fixes it and it doesn't.

**Comment by datawhores** [comment]
Are you using the binary or from pip/pipx?

**Comment by BosonHair** [comment]
This is with pipx

**Comment by datawhores** [comment]
2.7.13 should fix the issue for now

What version of python are you on by chance
The latest commits are for 3.0 unless your on the 2.7patch branch

**Comment by BosonHair** [comment]
That got rid of my error but 2.7.13 does't have the shift arrow/alt fix that the 3.0 dev version had.

**Comment by datawhores** [comment]
What version of python are you on by chance?

**Comment by BosonHair** [comment]
Python 3.10.1

**Comment by BosonHair** [comment]
Updated to 3.11 same result with 2.7.13

**Comment by datawhores** [comment]
Does this happen with 3.0

**Comment by BosonHair** [comment]
Still getting this

Exception in thread Thread-1 (logger_process):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
 ofscraper -sk -dc normal
 [start.startvalues:87]  config path:                                start.py:87
/Users/your_username/.config/ofscraper/config.json                              
 [start.startvalues:88]  profile path:                               start.py:88
/Users/your_username/.config/ofscraper/main_profile                             
 [start.startvalues:89]  log folder:                                 start.py:89
/Users/your_username/.config/ofscraper/logging                                  
objc[11322]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[11322]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

**Comment by datawhores** [comment]
Seems to be related to this I pushed a fix where the type is set as spawn is set explicity

https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr

**Comment by datawhores** [comment]
can you try the latest commit
pipx uninstall ofscraper 
pipx install git+https://github.com/datawhores/OF-Scraper.git

**Comment by BosonHair** [comment]
Uninstalled and reinstalled with the latest back to 3.0.5 and same error.
objc[16081]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[16081]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
Welcome to OF-Scraper Version 3.0.5

Using python3 v 3.11.4

**Comment by datawhores** [comment]
Yeah sure
Just install the git version

**Comment by BosonHair** [comment]
Uninstalled pipx version and installed pip version and same issue

**Comment by datawhores** [comment]
What version of mac are you on?

**Comment by BosonHair** [comment]
Monterey

**Comment by datawhores** [comment]
Can you try to set this enviroment variable before running
export "OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES"

**Comment by BosonHair** [comment]
Yeah, was just about to comment. That removed the python error popup. Thanks!

https://hynek.me/til/rq-macos/

**Comment by datawhores** [comment]
I added the environmental variables to the script

So I think that should fix the error without having to manually set that value.

I haven't been able to recreate this issue
