### ISSUE TITLE
how to limit max downloads?

### ISSUE THREAD

**Issue by god43** [datawhores/OF-Scraper#151]
how do i limit the max downloads I run

**Comment by god43** [comment]
thanks

**Comment by datawhores** [comment]
Which version

**Comment by god43** [comment]
the latest version?

**Comment by datawhores** [comment]
2.7.13

Or 3.0  beta

**Comment by god43** [comment]
2.7.13

**Comment by datawhores** [comment]
For that version threads would be the max allowed at once.

**Comment by datawhores** [comment]
3.0
threads*download_sems
