### ISSUE TITLE
Liking Posts

### ISSUE THREAD

**Issue by MyNameJeff12123** [datawhores/OF-Scraper#153]
When Liking all posts the script gets stuck on the first like. Any help? No errors.

**Comment by datawhores** [comment]
See if the issue persist in 3.0 for you 
I was unable to recreate this error on machine

**Comment by datawhores** [comment]
or run with
--output debug 
or 
--log trace

I would recommend log trace, just because of the amount of output

**Comment by MyNameJeff12123** [comment]
> or run with --output debug or --log trace
> 
> I would recommend log trace, just because of the amount of output

Stuck on Welcome to OF-Scraper Version 2.7.12
Installed with pip, how can I update? I used the pip install with the git address too... Cheers.

**Comment by MyNameJeff12123** [comment]
> or run with --output debug or --log trace
> 
> I would recommend log trace, just because of the amount of output


[j@server ~]$ pip3.9 install git+https://github.com/datawhores/OF-Scraper.git
Successfully built ofscraper
Installing collected packages: ofscraper
Successfully installed ofscraper-2.7.12

**Comment by MyNameJeff12123** [comment]
Using the compiled version it works fine :)
