### ISSUE TITLE
Add support for running as non-root user?

### ISSUE THREAD

**Issue by dunngitter** [datawhores/OF-Scraper#157]
Hello! I'm trying to switch to this script from UltimaScraper, so far so good. The one major issue I have right now is that (unless I'm missing it) this script always runs as root in the container. This doesn't work for me since the NFS share I'm downloading files to, and other tools that are subsequently processing the downloaded files, have a specific UID and GID associated with them.

Does this functionality already exist and I'm missing it? If not, any chance you could add support for this?

**Comment by datawhores** [comment]
you can pass the --user arg to docker run 
--user 1000:1000

or have

**Comment by datawhores** [comment]
or in the compose something like
    image: datawhores/of-scraper:main
    user: "${UID:-1000}:${GID:-1000}"

**Comment by datawhores** [comment]
I added a commit to handle this better

**Comment by dunngitter** [comment]
Yeah setting it directly wasn't working for me because the files were stored in /root. I saw you merged the PR I put up to resolve though, thanks!
