### ISSUE TITLE
{filename} template not working when code-execution is true

### ISSUE THREAD

**Issue by newdenim** [datawhores/OF-Scraper#161]
Hello. Let me start by saying thanks for working on this, it's pretty useful and I like the features you are adding.

I'm currently migrating from Digitalcriminal's script and trying to maintain the same library of downloaded files and encountered an issue when I tried to rename the `jpeg` files to `jpg`. In the end I found out that the issue appears as soon as you enable code-execution.

**Description**
When setting `"code-execution": true` on the config, the `{filename}` template sets always **None** for all the downloaded files in their place.

**Version**
3.0.10 (running from source).

**Environment**
* Python: 3.10.6
* Pip: 22.0.2
* Poetry: 1.3.2
* OS: Ubuntu 22.04.2

**Relevant Config**
config.json
```
    "config": {
        "file_format": "{date}_{filename}.{ext}",
         "date": "YYYY-MM-DD",
        "code-execution": true,
}
```

For example in this case I get files named `2020-08-08_None.jpeg`. This was reported [here](https://github.com/datawhores/OF-Scraper/issues/155), with another issue but I think only the issue about freezing was fixed.

**Other Notes**
I did not check if the other templates work as expected, until now I know that `{date}` and `{ext}` seems to be working correctly.

Please let me know if you need any other config or detail.

Thanks!

**Comment by datawhores** [comment]
Yes it should be fixed now

**Comment by datawhores** [comment]
If you want to do the replacement the easiest way would be to do something like this

**Comment by newdenim** [comment]
I didn't know that way, I was doing `{ext if ext!=\"jpeg\" else \"jpg\"}` to just change jpeg and leave the rest as is, but I like that idea also to rename other extensions.
I'll try it. Thanks!
