### ISSUE TITLE
Script running incredibly slowly and failing on high percentage of posts after updating to 3.0.10

### ISSUE THREAD

**Issue by distantowl** [datawhores/OF-Scraper#164]
Title.

Download took 1h 30m for a single profile as well as failed on about 33% of posts. Any ideas? The last 2.X version only took about 30 minutes per profile and seemed to be limited by my bandwidth.

**Comment by datawhores** [comment]
You should run with --output debug 
And then we can see why it keeps failing

Long download times would come from constant retrying

**Comment by distantowl** [comment]
i can post more but these are everywhere in my log file.

`2023-08-08 15:48:38 - DEBUG - Media:2198566727 Post:186371976 [attempt 1/10] exception database is locked
2023-08-08 15:48:38 - DEBUG - Media:2198566727 Post:186371976 [attempt 1/10] exception Traceback (most recent call last):
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/utils/download.py", line 363, in download
    return await main_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id)
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/utils/download.py", line 405, in main_download_helper
    await operations.write_media_table(ele,path_to_file,model_id,username)
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/db/operations.py", line 143, in write_media_table
    await conn.execute(queries.mediaInsert,insertData)
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
sqlite3.OperationalError: database is locked
`

**Comment by distantowl** [comment]
i dont think this is causing it but i dont see anything else.

full log here: https://gist.github.com/distantowl/2cae4e8978e078be6b0694c30f9db6fc

**Comment by datawhores** [comment]
See if 3.0.11 helps

**Comment by distantowl** [comment]
pipx is refusing to upgrade, it cant seem to find 3.0.11

**Comment by datawhores** [comment]
Yes check again when you have time
I hadn't pushed the update

**Comment by basketballhead6** [comment]
It's still extremely slow on 3.0.12 @datawhores Downloading is fine but it takes forever to get through the menus and the pre downloading stages

**Comment by distantowl** [comment]
https://gist.github.com/distantowl/89b93bfc588ebf376f36e6a20a151511

took 2 hours for a single account, still about 1/3 of the posts failed

**Comment by datawhores** [comment]
Are you running more then one instance of the script

**Comment by datawhores** [comment]
What kind of drive do you have? Is it a network drive

**Comment by basketballhead6** [comment]
Maybe it was just OF being slow to respond for some reason the other day. It's now back to the normal speeds now but won't download anything as the exe version of your release is currently broken

**Comment by datawhores** [comment]
I'm trying to see if I can speed things up some way
But also if you scrape labels that might slow things down. Since there is not really a good way to cache those

**Comment by basketballhead6** [comment]
No worries. Will you be releasing a numbers version soon with some of your recent fixes? 3.0.12 won't even scrape content for me and can't use the exe at the moment either @datawhores

**Comment by datawhores** [comment]
I'm not sure if I will keep the exe
The zips work the same, and are slightly faster since they don't have to unpack into a temp folder

For some reason the exe won't work

**Comment by datawhores** [comment]
> https://gist.github.com/distantowl/89b93bfc588ebf376f36e6a20a151511
> 
> took 2 hours for a single account, still about 1/3 of the posts failed

It looks like the downloads are going through fine
They are just being marked as failed because of this
sqlite3.OperationalError: database is locked

Maybe try with 1 thread, and just turn up the number of download-sems slightly
Maybe 10 or 15

I a little unsure of the reason why your database is being marked as locked so many times

**Comment by distantowl** [comment]
im only running one instance of the script and the drive is a NAS. I've been using the NAS the entire time though

**Comment by distantowl** [comment]
> > https://gist.github.com/distantowl/89b93bfc588ebf376f36e6a20a151511
> > took 2 hours for a single account, still about 1/3 of the posts failed
> 
> It looks like the downloads are going through fine They are just being marked as failed because of this sqlite3.OperationalError: database is locked
> 
> Maybe try with 1 thread, and just turn up the number of download-sems slightly Maybe 10 or 15
> 
> I a little unsure of the reason why your database is being marked as locked so many times

i'll try that, another issue i seem to be running across is changing the sem count does not persist after i close and open the script. ive tried editing using the script and a text editor and both get reset to 6 seemingly at random

**Comment by distantowl** [comment]
https://gist.github.com/distantowl/dc4d14ad5157961ad7a7fdc666b8066f

ran with 1 thread and 12 sems, no failures this time. it still took 2 full hours though

**Comment by newdenim** [comment]
I do not know if this idea would help. But maybe to increase the speed, the scrapper could check on the metadata which was the last Post, Message, etc. and then stop fetching older posts when these were found on the metadata. You'll have to fetch from more recent posts to older ones.
That way when you run again the script it will only fetch the new posts instead of having to scrape all the posts, this will be helpful specially for models that have older accounts or post a lot.

For example when testing some things I ran it multiple times for one model on the same day and noticed that it takes like 15 minutes fetching posts from 2020 only to end up downloading nothing or maybe 1 new post on the timeline.

This won't do anything for the first run or new subscriptions,  but if you want to update a model you downloaded recently it'll increase dramatically the speed.

I'm currently not so familiar with the code or python to know where to send a patch :disappointed:

**Comment by datawhores** [comment]
I think that is more doable now with the way the code is written

**Comment by newdenim** [comment]
Awesome, let me know if I can help you with anything. Regarding the `database is locked` issue.
Something similar is happening to me when running with multiple threads.

Maybe this can help to find the issue, but I found out that In general it seems to be working right until there is an error on one of the threads, for example I found out this crash:
```
TRACEBACK - Traceback (most recent call last):
  File "/home/your_username/Workspace/OF-Scraper/ofscraper/utils/download.py", line 427, in main_download_downloader
    async with c.requests(url=url)() as r:
  File "/home/your_username/Workspace/OF-Scraper/ofscraper/classes/sessionbuilder.py", line 80, in requests
    headers=self._create_headers(headers,url)
  File "/home/your_username/Workspace/OF-Scraper/ofscraper/classes/sessionbuilder.py", line 69, in _create_headers
    headers=self._create_sign(headers,url)
  File "/home/your_username/Workspace/OF-Scraper/ofscraper/classes/sessionbuilder.py", line 72, in _create_sign
    auth.create_sign(url,headers) if self._set_sign else None
  File "/home/your_username/Workspace/OF-Scraper/ofscraper/utils/auth.py", line 205, in create_sign
    content = read_request_auth()
  File "/home/your_username/Workspace/OF-Scraper/ofscraper/utils/auth.py", line 245, in read_request_auth
    content = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

TRACEBACK - Expecting value: line 1 column 1 (char 0)
```
And then a flood of `database is locked` stacktraces start appearing. So it seems that after a thread crashes it does not close the database nicely, but it releases the semaphore and that causes all the other threads to start failing.

I did not found out if that's really the reason or there is another thing there, I'll post again if I find anything else.

**Comment by datawhores** [comment]
Yeah at the moment I'm still trying to figure out why some users are more proned to database locks.
With that said I've rewritten the code to hopefully force the database to close, which should help with locks

I've written timeline and archive to only get the newest posts.
other stuff will take a bit more work

**Comment by distantowl** [comment]
saw the latest update, with your note about network drives - does this only apply if the cache/metadata for the scraper is on a network drive or if the download location is a network drive? i have the metadata on my local drive

**Comment by datawhores** [comment]
Yes it only applies if 
cache/metadata for the scraper is on a network drive 

At least in terms of diskcache having issues
the core of the issue comes from sqlite, so having the metadata on a network drive would cause issue

**Comment by datawhores** [comment]
By the way you can set 
threads to 0
To have the disable multi-threading

That may help if your still having issues

**Comment by distantowl** [comment]
marking as closed for now, latest updates with the partial scrapes have made the script run in like 30-45 minutes for 50ish accounts vice 2 hours for 1 account. suggestion for the future is to add the --after and --dupe options to the menu when running the script in the interactive mode.
