### ISSUE TITLE
Bug: "d" being replaced with "name" in logs

### ISSUE THREAD

**Issue by dunngitter** [datawhores/OF-Scraper#165]
Any ideas? I'm dumbfounded...
![image](https://github.com/datawhores/OF-Scraper/assets/84608106/93a0a286-a094-4c89-934f-cea22fb10276)

**Comment by dunngitter** [comment]
omg, my username is just "d", I bet it's the filter for sensitive data that's stripping out?

**Comment by datawhores** [comment]
I can make this more specific with regex
Which should make it work

Right now it is only looking for the name, but I can add info about the letters around it

**Comment by datawhores** [comment]
Should work now
![image](https://github.com/datawhores/OF-Scraper/assets/67020411/44b236fd-6b42-42b9-825f-ce6622fee3c6)
 re.sub("(d |d |\\bd\\b)","username","d")
'username'
>>> re.sub("(d |d |\\bd\\b)","username","dsad")
'dsad'
>>> re.sub("(d |d |\\bd\\b)","username","d ")
'username'
>>> re.sub("(d |d |\\bd\\b)","username"," d")
' username'
