### ISSUE TITLE
Error when trying to Scrape entire paid page

### ISSUE THREAD

**Issue by hiddenGoldNova7** [datawhores/OF-Scraper#168]
When trying to scrape the entire paid content with the additional selection option in the script, it only scraps one model and then stops with an error.
Version is 3.0.12

![Screenshot 2023-08-10 151728](https://github.com/datawhores/OF-Scraper/assets/36936998/93eeb1b6-05ce-4b62-85fb-49e1dcfcf6a3)

**Comment by datawhores** [comment]
This should be fixed
