### ISSUE TITLE
It works :-) but may I ask some questions

### ISSUE THREAD

**Issue by waswosi** [datawhores/OF-Scraper#169]
Thank you, it works!!!

I have some questions.
Is it yet possible for the downloaded pics and vids that
the filename gets the format YYYY-MM-DD_Original Filename with the date the
pic or vid has been posted on the site? Where to put it in in the script?
If not, please make it possible!
It's much more convenient with the date from the original post at the beginning of the filename.

My first try was with a encrypted file.
I get three files in output.
A tempvid_xxx.mp4 (video with no audio) a tempaudio_xxx.mp4 (audio form vid with no video)
and finally a temp_xxx.mp4 which is the correct video.
Should it not be only one output file?
I think something is not correct with my ffmpeg setting here?
Can you help?

And last, where is the correct place to put special commands in, like dowloading only posts after
a certain date. What will the script do if the file already exists in the dowload directory. Skipping
would be the best.

Thank you so much.

**Comment by datawhores** [comment]
Please come to the discord for questions like this
