### ISSUE TITLE
Dockerfile not found

### ISSUE THREAD

**Issue by dia-val** [datawhores/OF-Scraper#172]
I get an error when trying to docker compose with the latest docker-compose.yml, here is my current file:
`version: '3'

volumes:
  bin:
  config:
  data:

services:
  ofscraper:
    container_name: ofscraper
    image: datawhores/of-scraper:latest
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
    # #change the host mountpoint
      - /mnt/user/appdata/ofscraper:/home/.config/ofscraper
      - /mnt/remotes/SpecialDownloads/onlyfans_script:/of_media
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # use the following two lines if you want to interact with the script manually.
    # bring the container up with `docker compose up -d` and then run it with
    # `docker compose exec -it ofscraper ofscraper --config /ofscraper/config/config.json`
    entrypoint: ["/bin/bash"]
    command: ["-c","sleep infinity"]
    
    # alternatively, if you want the script to run automatically with a set or arguments,
    # comment out the lines above and instead do something like:
    # command: "ofscraper --username ALL --posts all"`

This produces the error:
 => [internal] load build definition from Dockerfile                                                                                                           0.0s
 => => transferring dockerfile: 2B                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                              0.1s
 => => transferring context: 2B                                                                                                                                0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount4085269791/Dockerfile: no such file or directory

Am i doing something wrong? Thanks for helping me out, great fan of your project.

**Comment by datawhores** [comment]
Thank you I commented out the offending lines
