### ISSUE TITLE
Attempt to set Date: Operation not Permitted

### ISSUE THREAD

**Issue by dia-val** [datawhores/OF-Scraper#173]
The model files are downloaded correctly, but show up as failed in the scraper. After setting the "debug" option the following error is thrown after every file is downloaded:

2023-08-20 06:15:52 - DEBUG - Media:2984954732 Post:704208492 Attempt to set Date to 2023-08-18 23:13
2023-08-20 06:15:52 - DEBUG - Media:2984954732 Post:704208492 [attempt 1/10] exception [Errno 1] Operation not permitted
2023-08-20 06:15:52 - DEBUG - Media:2984954732 Post:704208492 [attempt 1/10] exception Traceback (most recent call last):
  File "/home/your_username/app/your_username/utils/download.py", line 366, in download
    return await main_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/app/your_username/utils/download.py", line 405, in main_download_helper
    set_time(path_to_file,newDate )
  File "/home/your_username/app/your_username/utils/download.py", line 843, in set_time
    pathlib.os.utime(path, (timestamp, timestamp))
PermissionError: [Errno 1] Operation not permitted

2023-08-20 06:15:52 - DEBUG - PID: 81 download process thread closing

Unfortunately, this means the scraper cannot mark the file as downloaded in the database and has to download all the files every time. Is there a fix for this? The script is running in Docker with the files on a mounted volume.

**Comment by datawhores** [comment]
Can you try to pass in the owner of the folder

Are you on linux by chance

**Comment by dia-val** [comment]
Yes, now running version 3.0.12+main.bfe776e as Docker container with unraid as host. Tried setting User ID 99 in Docker compose but getting error :
![image](https://github.com/datawhores/OF-Scraper/assets/142575839/4d93a17e-b6a3-41db-b44d-c0ada7651f45)

The files are downloaded, but the "Operation not permitted" error persists.

**Comment by datawhores** [comment]
can I see your compose file

**Comment by dia-val** [comment]
Sure, here is my current compose file that throws the mentioned "Operation not permitted" error:
-----------------------------------------
version: '3'

volumes:
  bin:
  config:
  data:

services:
  ofscraper:
    container_name: ofscraper
    image: datawhores/of-scraper:main
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
    # #change the host mountpoint
      - /mnt/user/appdata/ofscraper:/home/ofscraper/.config/ofscraper
      - /mnt/remotes/SpecialDownloads/onlyfans_script:/of_media
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # use the following two lines if you want to interact with the script manually.
    # bring the container up with `docker compose up -d` and then run it with
    # `docker compose exec -it ofscraper ofscraper --config /ofscraper/config/config.json`
    entrypoint: ["/bin/bash"]
    command: ["-c","sleep infinity"]
    
    # alternatively, if you want the script to run automatically with a set or arguments,
    # comment out the lines above and instead do something like:
    # command: "ofscraper --username ALL --posts all"
-----------------------------------------

Afaik in unraid 99 is user "nobody" with group 100. This is default for most dockers and can be configured per-docker.
In ofscraper version 2.x the permission error did not occur.
Maybe this helps?
https://www.reddit.com/r/unRAID/comments/10lbudb/problem_with_puid_and_pgid_after_update_on/

Thanks for helping out!

**Comment by datawhores** [comment]
I think someone had a similar error
or I'm not sure if your the same person

In either case please come to the discord
Closing issue
