### ISSUE TITLE
pip seemed to fail to build package: uvloop<0.18.0,>=0.17.0

### ISSUE THREAD

**Issue by deadcode0815** [datawhores/OF-Scraper#176]
USERNAMEPS C:\Users\USERNAME> pipx install git+https://github.com/datawhores/OF-Scraper.git
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\USERNAME\.local\pipx\logs\cmd_2023-08-22_01.50.20_pip_errors.log

pip seemed to fail to build package:
    uvloop<0.18.0,>=0.17.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    RuntimeError: uvloop does not support Windows at the moment
    error: metadata-generation-failed

Error installing ofscraper from spec 'git+https://github.com/datawhores/OF-Scraper.git'.

**Comment by datawhores** [comment]
Removed on windows
