### ISSUE TITLE
Can't download from creators with lots of posts/media

### ISSUE THREAD

**Issue by marcintosch** [datawhores/OF-Scraper#182]
Hey there, 

I've currently having an issue where Python 3.11.5 crashes every time when trying to fetch data from bigger creators respectively creators with a lot of posts and media. --output debug lists this error:

`--- Logging error ---
TRACEBACK  [logger.inner:187]  failed with exception: 'function' object has no attribute 'print_exception' logger.py:187
zsh: segmentation fault  ofscraper --output debug`

I'm running OFScraper on macOS Ventura 13.5.1 on a MacBook Pro (Intel-based).

Thanks in advance 
m.

**Comment by datawhores** [comment]
Please make a new issue if this persists in newer version
