### ISSUE TITLE
Arm Binaries

### ISSUE THREAD

**Issue by ResidentSpaceDragon** [datawhores/OF-Scraper#183]
Could there be armv7 armv8 binaries?

**Comment by orithecapper** [comment]
Python should run crossplatform

**Comment by orithecapper** [comment]
> Could there be armv7 armv8 binaries?

please 


```
pip install git+https://github.com/datawhores/OF-Scraper.git
```


but god speed bro :) ez fappennnzzz

**Comment by datawhores** [comment]
The binaries have some system dependencies. Since they are self contained and come with there own python installation.

For example the Mac binary are compiled on a Mac docker. Using a Linux docker would not work for this.

I'm not sure how making a binary for arm would work at the moment.

**Comment by orithecapper** [comment]
> The binaries have some system dependencies. Since they are self contained and come with there own python installation.
> 
> For example the Mac binary are compiled on a Mac docker. Using a Linux docker would not work for this.
> 
> I'm not sure how making a binary for arm would work at the moment.

I been using ARM too ... works fine with pip

**Comment by datawhores** [comment]
Since the pip installation works
I think that will have to be good enough for now in terms of arm support

If someone wants to make a pull requests after figuring out how to use pyinstaller to make the binaries, I would be open to that as well
