### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by darthsimon** [datawhores/OF-Scraper#185]
Thank you for the scraper! It's downloading perfectly, but I can't seem to find where it actually downloads. Please help.

**Comment by Puk0** [comment]
En el programa > Edit config.json file > save_location
o
En tu usuario > .config\ofscraper > config.json > "save_location":

**Comment by darthsimon** [comment]
Awesome! Muchas 
gracias!

**Comment by darthsimon** [comment]
Location found
