### ISSUE TITLE
Discord Web-hook not working

### ISSUE THREAD

**Issue by 6R1M4C3** [datawhores/OF-Scraper#187]
I have passed the url to the config file but when you run the tool nothing is passed to discord as though the webhook doesn't register, any idea the issue?

**Comment by datawhores** [comment]
I want to see if the other logger queue consumer is working
So try  --log debug
, and look for the log file in your config folder

**Comment by 6R1M4C3** [comment]
ok will check that shortly and get back to you

**Comment by datawhores** [comment]
Oh did you pass 
--discord normal?

**Comment by 6R1M4C3** [comment]
> Oh did you pass --discord normal?

I tried that it didn't work, I just tried it again and it started to work again.
