### ISSUE TITLE
Blacklist feature

### ISSUE THREAD

**Issue by spiderzero3** [datawhores/OF-Scraper#188]
I need help using the blacklist feature. I have a list on OF called "Blacklist" for users I want to be subscribed to but would take up too much space to download.

Here are my arguments:
```ofscraper --letter-count --daemon 1 --black-list Blacklist --sub-status active --sort subscribed --username ALL --posts all```

It doesn't filter out the users in my blacklist at all so I'm wondering if my syntax is just wrong.

I'm on version 3.2.5.

**Comment by datawhores** [comment]
Can you somehow send a log

Add --log debug

**Comment by Puk0** [comment]
> It doesn't filter out the users in my blacklist at all so I'm wondering if my syntax is just wrong.

cambia > --black-list Blacklist
por --excluded-username modelo,modelo,modelo,modelo

**Comment by spiderzero3** [comment]
> Can you somehow send a log
> 
> Add --log debug

Here's the log: [ofscraper_main_profile_2023-09-01.log](https://github.com/datawhores/OF-Scraper/files/12503205/ofscraper_main_profile_2023-09-01.log)

> cambia > --black-list Blacklist por --excluded-username
> 
> por ejemplo :
> 
> --excluded-username modelo,modelo,modelo,modelo

I know that's an option, but my blacklist is 38 users big and it sucks to manage it that way. The new blacklist feature is a cleaner way to do it.

**Comment by datawhores** [comment]
Hopefully it works now

You have a capital letter in your input, and I wasn't converting it to lower case before comparing

**Comment by spiderzero3** [comment]
Perfect, it works now. Thanks!
