### ISSUE TITLE
Scrape active subscriptions

### ISSUE THREAD

**Issue by markt7891** [datawhores/OF-Scraper#189]
is there a way of bypassing 'Getting your subscriptions (this may take a while) to only pull active subscriptions. i have over 2000 expired memberships and it takes ages to reload everytime.

**Comment by PsychoSid** [comment]
I use “—sub-status active” to do this.

**Comment by Puk0** [comment]
Asi te acomoda la lista en el programa por nombre y suscripciones activas para seleccionar
ofscraper -ss active --sort name

Y asi te baja todo de todas las suscripciones activas
ofscraper -ss active --username ALL --posts all

**Comment by markt7891** [comment]
i use this ofscraper -l debug --account-type paid --sub-status active but still takes ages to load.

**Comment by datawhores** [comment]
We have support for user list now
I can make another two special list.
ofscraper.main is for both active and expired, and is the main list onlyfans keeps track of for you

I will add an extra list can
ofscraper.active 
And another one called
ofscraper.expired


It would be a little too difficult to try to figure out which list to pull on the fly.
But if you know you only want to scrape certain types of accounts that would be the way to go.

**Comment by markt7891** [comment]
Hi - Thank you for adding this 
i keep getting this error when using ofscraper -ul active

Exception: You have filtered the user list to zero
Please Select less restrictive filters and userlists
Exception in thread Thread-1 (logger_process):

**Comment by datawhores** [comment]
Re-reading my previous post would have helped here

The list name is specifically "ofscraper.active" 

The list you gave has no meaning unless you have a list with that name on the site

**Comment by markt7891** [comment]
i got it :) THANK YOU!
