### ISSUE TITLE
sqlite3.DatabaseError: database disk image is malformed   

### ISSUE THREAD

**Issue by BosonHair** [datawhores/OF-Scraper#190]
Hello,
Updated to v3.2.5 and got this new error: sqlite3.DatabaseError: database disk image is malformed.

When i go to my db, I see a normal db file and a user_date_copy and the new ones are in a backup folder.

Any idea? Should I delete them and run it again?

**Comment by datawhores** [comment]
It is probably the cache file since that is what is used in the backend

Would need to see a log file to confirm
Run with --log and debug to generate that

**Comment by BosonHair** [comment]
TRACEBACK  [logger.inner:187]  failed with exception: database disk image is malformed                  logger.py:187
TRACEBACK  [logger.inner:187]  Traceback (most recent call last):                                       logger.py:187
            File                                                                                                     
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/comm              
          ands/scraper.py", line 185, in normal_post_process                                                         
              combined_urls=OF.process_areas( ele, model_id)                                                         
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                         
            File                                                                                                     
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/util              
          s/of.py", line 271, in process_areas                                                                       
              messages_dicts = process_messages( model_id,username)                                                  
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                  
            File                                                                                                     
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/util              
          s/of.py", line 40, in process_messages                                                                     
              messages_ =asyncio.run(messages.get_messages(  model_id,username))                                     
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                      
            File                                                                                                     
          "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3              
          .11/asyncio/runners.py", line 190, in run                                                                  
              return runner.run(main)                                                                                
                     ^^^^^^^^^^^^^^^^                                                                                
            File                                                                                                     
          "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3              
          .11/asyncio/runners.py", line 118, in run                                                                  
              return self._loop.run_until_complete(task)                                                             
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                             
            File                                                                                                     
          "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3              
          .11/asyncio/base_events.py", line 653, in run_until_complete                                               
              return future.result()                                                                                 
                     ^^^^^^^^^^^^^^^                                                                                 
            File                                                                                                     
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/api/              
          messages.py", line 69, in get_messages                                                                     
              if not args_.getargs().no_cache:oldmessages=cache.get(f"messages_{model_id}",default=[])               
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
            File                                                                                                     
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/diskcache/core              
          .py", line 1165, in get                                                                                    
              rows = self._sql(select, (db_key, raw, time.time())).fetchall()                                        
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                   
          sqlite3.DatabaseError: database disk image is malformed                                                    
                                                                                                                     
 [scraper.scrape_context_manager:378]

**Comment by datawhores** [comment]
Yeah it's the cache file you can delete the cache_sql folder

**Comment by BosonHair** [comment]
Ok, tried that and I got this error:

messages = funct()
               ^^^^^^^
  File "<string>", line 2, in get
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/managers.py", line 822, in _callmethod
    self.run()
    kind, result = conn.recv()
    kind, result = conn.recv()
    self.run()
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
                   ^^^^^^^^^^^
                   ^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 252, in recv
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 252, in recv
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    buf = self._recv_bytes()
    kind, result = conn.recv()
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
                   ^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 252, in recv
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 416, in _recv_bytes
          ^^^^^^^^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 416, in _recv_bytes
    self._target(*self._args, **self._kwargs)
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/logger.py", line 400, in logger_other
    buf = self._recv_bytes()
    buf = self._recv(4)
Exception in thread Thread-93 (logger_process):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
          ^^^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 385, in _recv
    self._target(*self._args, **self._kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 416, in _recv_bytes
    buf = self._recv(4)
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/logger.py", line 400, in logger_other
          ^^^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 385, in _recv
    messages = funct()
               ^^^^^^^
  File "<string>", line 2, in get
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/managers.py", line 822, in _callmethod
    raise EOFError
EOFError
    buf = self._recv(4)
    raise EOFError
          ^^^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 385, in _recv
EOFError
    messages = funct()
               ^^^^^^^
  File "<string>", line 2, in get
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/managers.py", line 822, in _callmethod
    kind, result = conn.recv()
    raise EOFError
    self.run()
                   ^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 252, in recv
EOFError
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    kind, result = conn.recv()
    buf = self._recv_bytes()
                   ^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 252, in recv
          ^^^^^^^^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 416, in _recv_bytes
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 416, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 385, in _recv
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/connection.py", line 385, in _recv
    raise EOFError
EOFError
    raise EOFError
EOFError
    self._target(*self._args, **self._kwargs)
  File "/Users/vfx/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/logger.py", line 356, in DEBUG     [paths._mac_truncateHelper:126]  path:                                                         paths.py:126
         /Volumes/OF/OnlyFans/model/Images/2021-12/2146x1536_0996da1f03bb307823c8700fa139a53d_2292             
         849933.part path size: 106    



Then I though, lets uninstall and reinstall and I get that too many open files error I was having before but I moved my threads/download sems to 2/1:

[downloadbatch.download:430]  Media:2449847964 Post:538810928234 exception [Errno 24]  downloadbatch.py:430
         Too many open files: '/Users/your_username/.config/ofscraper/config.json'                                   
DEBUG     [downloadbatch.download:431]  Media:2449847964 Post:538810928234 exception Traceback   downloadbatch.py:431
         (most recent call last):                                                                                    
           File                                                                                                      
         "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscrape                     
         r/utils/downloadbatch.py", line 424, in download                                                            
           File                                                                                                      
         "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscrape                     
         r/classes/placeholder.py", line 22, in wrapper                                                              
           File                                                                                                      
         "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscrape                     
         r/classes/placeholder.py", line 26, in create_variables                                                     
           File                                                                                                      
         "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscrape                     
         r/utils/profiles.py", line 33, in get_my_info                                                               
           File                                                                                                      
         "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscrape                     
         r/utils/profiles.py", line 134, in get_active_profile                                                       
           File                                                                                                      
         "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscrape                     
         r/utils/profiles.py", line 128, in get_current_config_profile                                               
           File                                                                                                      
         "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscrape                     
         r/utils/config.py", line 38, in read_config                                                                 
         OSError: [Errno 24] Too many open files:                                                                    
         '/Users/your_username/.config/ofscraper/config.json'

**Comment by dvkrav** [comment]
Can you share what settings you changed to fix the issue ? 

> Had some issues but I reinstalled and adjusted some settings. Everything seems to be working now.
