### ISSUE TITLE
keep getting this error when updating

### ISSUE THREAD

**Issue by ipcaldwell** [datawhores/OF-Scraper#191]
ilelock-3.12.3-py3-none-any.whl (11 kB)
Using cached pycryptodome-3.18.0-cp35-abi3-macosx_10_9_universal2.whl (2.4 MB)
Downloading pytest-7.4.1-py3-none-any.whl (324 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.2/324.2 kB 7.8 MB/s eta 0:00:00
Using cached setuptools-67.8.0-py3-none-any.whl (1.1 MB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Downloading pluggy-1.3.0-py3-none-any.whl (18 kB)
Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Using cached multiprocess-0.70.15-py39-none-any.whl (133 kB)
Using cached dill-0.3.7-py3-none-any.whl (115 kB)
Building wheels for collected packages: lxml, cchardet
  Building wheel for lxml (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [121 lines of output]
      Building lxml version 4.9.3.
      /private/var/folders/mc/2zcm0v_d2cj51kgyrpwcbg3w0000gn/T/pip-install-y5024jz4/lxml_b490f8e2a37b4a609261295173944376/setup.py:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Building without Cython.
      Building against libxml2 2.9.13 and libxslt 1.1.35
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-39
      creating build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/_elementpath.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/sax.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/builder.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/doctestcompare.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/usedoctest.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/cssselect.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/ElementInclude.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      creating build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      creating build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/soupparser.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/defs.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/clean.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/html5parser.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/formfill.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/builder.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      copying src/lxml/html/diff.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/html
      creating build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron
      copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron
      copying src/lxml/etree.h -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/etree_api.h -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/lxml.etree.h -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/objectify.pyx -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/etree.pyx -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/public-api.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/xmlid.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/cleanup.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/xslt.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/xpath.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/debug.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/serializer.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/classlookup.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/saxparser.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/objectpath.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/relaxng.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/xinclude.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/iterparse.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/parser.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/dtd.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/apihelpers.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/xmlerror.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/readonlytree.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/extensions.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/xmlschema.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/schematron.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/docloader.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/nsclasses.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/parsertarget.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/xsltext.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/proxy.pxi -> build/lib.macosx-10.9-universal2-cpython-39/lxml
      copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/__init__.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/config.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.9-universal2-cpython-39/lxml/includes
      creating build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources
      creating build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/rng
      copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/rng
      creating build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/xsl
      creating build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.9-universal2-cpython-39/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build/temp.macosx-10.9-universal2-cpython-39
      creating build/temp.macosx-10.9-universal2-cpython-39/src
      creating build/temp.macosx-10.9-universal2-cpython-39/src/lxml
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include -Isrc -Isrc/lxml/includes -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/lxml/etree.c -o build/temp.macosx-10.9-universal2-cpython-39/src/lxml/etree.o -w -flat_namespace
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      Compile failed: command '/usr/bin/gcc' failed with exit code 1
      creating var
      creating var/folders
      creating var/folders/mc
      creating var/folders/mc/2zcm0v_d2cj51kgyrpwcbg3w0000gn
      creating var/folders/mc/2zcm0v_d2cj51kgyrpwcbg3w0000gn/T
      cc -I/usr/include -I/usr/include/libxml2 -c /var/folders/mc/2zcm0v_d2cj51kgyrpwcbg3w0000gn/T/xmlXPathInit_s4zl_m6.c -o var/folders/mc/2zcm0v_d2cj51kgyrpwcbg3w0000gn/T/xmlXPathInit_s4zl_m6.o
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      Perhaps try: xcode-select --install
      *********************************************************************************
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml
  Building wheel for cchardet (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-39
      creating build/lib.macosx-10.9-universal2-cpython-39/cchardet
      copying src/cchardet/version.py -> build/lib.macosx-10.9-universal2-cpython-39/cchardet
      copying src/cchardet/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/cchardet
      running build_ext
      building 'cchardet._cchardet' extension
      creating build/temp.macosx-10.9-universal2-cpython-39
      creating build/temp.macosx-10.9-universal2-cpython-39/src
      creating build/temp.macosx-10.9-universal2-cpython-39/src/cchardet
      creating build/temp.macosx-10.9-universal2-cpython-39/src/ext
      creating build/temp.macosx-10.9-universal2-cpython-39/src/ext/uchardet
      creating build/temp.macosx-10.9-universal2-cpython-39/src/ext/uchardet/src
      creating build/temp.macosx-10.9-universal2-cpython-39/src/ext/uchardet/src/LangModels
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Isrc/ext/uchardet/src -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/cchardet/_cchardet.cpp -o build/temp.macosx-10.9-universal2-cpython-39/src/cchardet/_cchardet.o
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cchardet
  Running setup.py clean for cchardet
Failed to build lxml cchardet
ERROR: Could not build wheels for lxml, cchardet, which is required to install pyproject.toml-based projects

**Comment by datawhores** [comment]
The script doesn't work with 3.9 anymore

You will need to upgrade to python3.11 or 3.10.11

**Comment by ipcaldwell** [comment]
ok. I'm trying to update with pip and it seems to revert back to 3.9 I installed 3.11 and even when I show pip python version it still has it but is still messing up...

**Comment by datawhores** [comment]
are you on windows?
you should be able to do something like 
py -3.11 -m pip

**Comment by ipcaldwell** [comment]
I’m on mac unfortunately

**Comment by datawhores** [comment]
If your still having this issue please make a new issue
