### ISSUE TITLE
Script being force closed after starting to download files and stalling

### ISSUE THREAD

**Issue by hmmark1984** [datawhores/OF-Scraper#192]
just updated to 3.2.5, i made sure to uninstall first then install both times using pipx

The script starts up, i select the user i want to download and what content of theirs i want, it starts to download, but i hangs, then shows as failed with the script being force closed and showing this error.

![Untitled](https://github.com/datawhores/OF-Scraper/assets/98670010/a4f80431-ea22-433b-8676-ccc3810f9065)

When i look in my download location it's only managed to get the profile picture.

**Comment by datawhores** [comment]
It is probably crashing, but I need to push a fix that pushing the correct exception up the chain

**Comment by hmmark1984** [comment]
don't know if it'll help but here's the a debug logfile.
[ofscraper_main_profile_2023-09-03.log](https://github.com/datawhores/OF-Scraper/files/12506392/ofscraper_main_profile_2023-09-03.log)

**Comment by datawhores** [comment]
The last commit I made will print the traceback

So that should help in finding the cause

**Comment by hmmark1984** [comment]
Seems to just bee the same for me, when it gets to downloading it shows 2 photos under the progress section. it downloads maybe 3MB, basically the profile pic and then just sits there until eventually the number of failed items in the progress section starts going up and then the script closes.
[ofscraper_main_profile_2023-09-05.log](https://github.com/datawhores/OF-Scraper/files/12528009/ofscraper_main_profile_2023-09-05.log)
![Untitled](https://github.com/datawhores/OF-Scraper/assets/98670010/f9aef9e2-7d90-478f-a8c1-2aab54e2397e)

**Comment by datawhores** [comment]
See if that works otherwise share your config

**Comment by hmmark1984** [comment]
I feel like a proper idiot now, yep that fixed it.
