### ISSUE TITLE
Application doesn't closes after prompt for "continue with this script?"

### ISSUE THREAD

**Issue by Nostang3** [datawhores/OF-Scraper#196]
I didn't see it posted before. This has been happening on the past few versions. I'm on 3.2.5 now. I've also noticed temp files in the folders that aren't being cleaned up which I believe happens when you end the script. Once you click "No" it just sits there and you can't force close it, you have to exit out of the terminal window to get it to close. Although if I do one model it seems to close fine but doesn't when I do my normal run of 30+ models. I looked for logs but didn't see any.

**Comment by datawhores** [comment]
What do the temp files look like?

**Comment by Nostang3** [comment]
![image](https://github.com/datawhores/OF-Scraper/assets/25465114/797a95f1-d5e8-4917-86ff-d1038eec19f4)

**Comment by datawhores** [comment]
Yeah it's having issues because the files can be decrypted 

You need to setup a cdm

The cdrm2 and cdrm are both down
The only options are keydb and manual

**Comment by Nostang3** [comment]
I went through and set up cdm a couple hours ago so I think these are left overs from before as their date/time stamps are older.

**Comment by datawhores** [comment]
try 3.3.2

**Comment by datawhores** [comment]
Can you run with 
ofscraper --output debug

**Comment by datawhores** [comment]
Also what operating system are you on

**Comment by Nostang3** [comment]
Windows 11. 

I ran the above command and it didn't complete. It didn't spit out any extra debug after selecting "No." Is there anything you need from the terminal before the selection?

**Comment by datawhores** [comment]
try 
ofscraper --log debug

see if the issue still happens 
If it does if you could send the log file.

**Comment by Nostang3** [comment]
So weirdly enough it finished after selecting no with --log debug set. But I did leave it alone for a few hours because I started it at work and couldn't get back to my pc till now. I'm gong to upgrade to the latest and give it a go now again and see what happens.

**Comment by Nostang3** [comment]
Upgraded to latest and ran with debug and it worked fine. Ran it immediately after without debugging and it hangs after selecting no.

**Comment by datawhores** [comment]
Can you show the log file there might be something useful

**Comment by Nostang3** [comment]
[ofscraper_main_profile_2023-09-05.log](https://github.com/datawhores/OF-Scraper/files/12529179/ofscraper_main_profile_2023-09-05.log)

**Comment by datawhores** [comment]
run 3.3.5
with --output debug 

There are now some special log statements with information about open threads

**Comment by Nostang3** [comment]
I updated to the latest and ran the script with output on and it worked as normal. I then tried after normally and it completed as normal as well. I'll keep an eye on it and report if it happens again.

**Comment by fightcancer2** [comment]
> I've also noticed temp files in the folders that aren't being cleaned up which I believe happens when you end the script.

Same issue here.  I have 78 tempaudio and 78 tempvid files. Been trying to resolve it in Discord for days. Using 3.3.10.

**Comment by datawhores** [comment]
@fightcancer2 
Please update 

Make a new issue if your still having issue
