### ISSUE TITLE
Too Many Open Files issue

### ISSUE THREAD

**Issue by BosonHair** [datawhores/OF-Scraper#199]
Hello,
Still getting a "too many open files" issue. Both by the db.lock and then just in the config.json. Things are fine for about 18 min, then failures begin with these errors and they just grow in number. This was mostly not an issue pre v 3.0.

Using v3.3.6 on Mac Monterey. This is going to my NAS so I've changed the db to json like your docs suggest. I'm no longer getting IO issues, just these issues. I get a few forbidden every now and then but other than that, everything is the same.

1st error:
TRACEBACK  [logger.inner:191]  Traceback (most recent call last):                                          logger.py:191
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 382, in process_dicts_split                                                            
              pack = await coro                                                                                         
                     ^^^^^^^^^^                                                                                         
            File                                                                                                        
          "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11              
          /asyncio/tasks.py", line 605, in _wait_for_one                                                                
              return f.result()  # May raise f.exception().                                                             
                     ^^^^^^^^^^                                                                                         
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 450, in download                                                                       
              raise e                                                                                                   
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 444, in download                                                                       
              return await main_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id)                   
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 490, in main_download_helper                                                           
              await                                                                                                     
          operations.update_media_table(ele,filename=path_to_file,model_id=model_id,username=username,down              
          loaded=True)                                                                                                  
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/db/oper              
          ations.py", line 70, in inner                                                                                 
              raise E                                                                                                   
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/db/oper              
          ations.py", line 54, in inner                                                                                 
              await loop.run_in_executor(LOCK_POOL, lock.acquire)                                                       
            File                                                                                                        
          "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11              
          /concurrent/futures/thread.py", line 58, in run                                                               
              result = self.fn(*self.args, **self.kwargs)                                                               
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/filelock/_api.py"              
          , line 220, in acquire                                                                                        
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/filelock/_unix.py              
          ", line 39, in _acquire                                                                                       
          OSError: [Errno 24] Too many open files:                                                                      
          '/Users/your_username/.config/ofscraper/main_profile/db.lock' 
          
  2nd error:         
          
          TRACEBACK  [logger.inner:191]  Traceback (most recent call last):                                          logger.py:191
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 382, in process_dicts_split                                                            
              pack = await coro                                                                                         
                     ^^^^^^^^^^                                                                                         
            File                                                                                                        
          "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11              
          /asyncio/tasks.py", line 605, in _wait_for_one                                                                
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 450, in download                                                                       
              raise e                                                                                                   
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 442, in download                                                                       
              with paths.set_directory(placeholder.Placeholders().getmediadir(ele,username,model_id)):                  
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                    
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/classes              
          /placeholder.py", line 22, in wrapper                                                                         
              args[0].create_variables()                                                                                
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/classes              
          /placeholder.py", line 26, in create_variables                                                                
              my_profile=profiles.get_my_info()                                                                         
                         ^^^^^^^^^^^^^^^^^^^^^^                                                                         
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/p              
          rofiles.py", line 33, in get_my_info                                                                          
              if currentProfile==get_active_profile():                                                                  
                                 ^^^^^^^^^^^^^^^^^^^^                                                                   
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/p              
          rofiles.py", line 134, in get_active_profile                                                                  
              return get_current_config_profile()                                                                       
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                       
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/p              
          rofiles.py", line 128, in get_current_config_profile                                                          
              return config_.get_main_profile(config_.read_config())                                                    
                                              ^^^^^^^^^^^^^^^^^^^^^                                                     
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/c              
          onfig.py", line 38, in read_config                                                                            
              with open(p , 'r') as f:                                                                                  
                   ^^^^^^^^^^^^^                                                                                        
          OSError: [Errno 24] Too many open files: '/Users/your_username/.config/ofscraper/config.json'

TRACEBACK  [logger.inner:191]  Traceback (most recent call last):                                          logger.py:191
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 382, in process_dicts_split                                                            
              pack = await coro                                                                                         
                     ^^^^^^^^^^                                                                                         
            File                                                                                                        
          "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11              
          /asyncio/tasks.py", line 605, in _wait_for_one                                                                
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 450, in download                                                                       
              raise e                                                                                                   
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 444, in download                                                                       
              return await main_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id)                   
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/d              
          ownloadbatch.py", line 490, in main_download_helper                                                           
              await                                                                                                     
          operations.update_media_table(ele,filename=path_to_file,model_id=model_id,username=username,down              
          loaded=True)                                                                                                  
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/db/oper              
          ations.py", line 61, in inner                                                                                 
              raise E                                                                                                   
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/db/oper              
          ations.py", line 58, in inner                                                                                 
              return await loop.run_in_executor(PROCESS_POOL, partial(func,*args,**kwargs,conn=conn))                   
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   
            File                                                                                                        
          "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11              
          /concurrent/futures/thread.py", line 58, in run                                                               
              result = self.fn(*self.args, **self.kwargs)                                                               
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               
            File                                                                                                        
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/db/oper              
          ations.py", line 219, in update_media_table                                                                   
              conn.execute(queries.mediaUpdate,insertData)                                                              
          sqlite3.OperationalError: unable to open database file  

Config:
       "threads": 3,
        "code-execution": true,
        "custom": null,
        "mp4decrypt": "/usr/local/Cellar/bento4/1.6.0-640/bin/mp4decrypt",
        "ffmpeg": "/usr/local/Cellar/ffmpeg/6.0/bin/ffmpeg",
        "discord": "#####",
        "private-key": null,
        "client-id": null,
        "key-mode-default": "keydb",
        "keydb_api": "#####",
        "dynamic-mode-default": "deviint",
        "partfileclean": true,
        "backend": "aio",
        "download-sems": 4,
        "maxfile-sem": 8,
        "downloadbars": false,
        "cache-mode": "json",

Should I keep adjusting the maxfile or anything? I've also tried this not going to my NAS and locally and same deal. I assume it's a mac issue.

**Comment by ilovep4k** [comment]
I have this issue as well and did some googling to find a solution. I came across this post which suggests a limitation of the OS of 256. Limit of what I'm not exactly sure! 😅 

[The site suggests the following:](https://stackoverflow.com/questions/56843659/oserror-errno-24-too-many-open-files-os-mojave)
> The number of open files you're allowed can be increased by using ulimit e.g. in bash you could do: ulimit -n This will probably print out 256 meaning that at one time a maximum of 256 file descriptors are allowed to be open.
> 
> **Increase the limit: ulimit -n 30000 # 30,000 open files allowed**

This worked for me :), but is not a solution for the app.

**Comment by BosonHair** [comment]
Please give yourself a high five for me because this fixed it and it also mostly fixed my threads/max download-sems issue too #yayMacs. This helped grab a ton of missing files also. 

The only issue is I think you need to run **ulimit -n 30000** each time before you run of scraper. Maybe @datawhores could add this as a config option to auto run before execution of the overall script. Then when you exit, maybe it could turn it back to default for safety.

**Comment by datawhores** [comment]
Made some changes that should limit the number of open files

checkout the 
fd branch which is the original code, put it prints information on number of open files
fd2 branch has new code that I've tested at least on my machine to reduce the number of open files

The main branch does not have some of these logs, but it will print some information when these errors occur

**Comment by datawhores** [comment]
@BosonHair 

Can you test if 
fd2 or main fixes the issue for you

On my end I have been able to reduce my limit to 256, and trigger the error on fd
With fd2/main the error no longer appears

**Comment by BosonHair** [comment]
FD2 branch? I've updated 3.3.6 with pipx. To stress test this, I'm downloading all my purchased content.

Without the no unlimit, I get these errors:

1.  /aiohttp/client_reqrep.py", line 1005, in raise_for_status                                  
              raise ClientResponseError(                                                              
          aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden',                    
          url=URL('https://cdn3.onlyfans.com/dash/files/f/f2/f2bda14388ca84eb08fca0b508e              
          fb73c/0hic9y1yx4zm7rj24s1vx.mpd?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR              
          0cHM6XC9cL2NkbjMub25seWZhbnMuY29tXC9kYXNoXC9maWxlc1wvZlwvZjJcL2YyYmRhMTQzODhjY              
          Tg0ZWIwOGZjYTBiNTA4ZWZiNzNjXC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M              
          6RXBvY2hUaW1lIjoxNjk2NDI4OTg2fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjQ1LjE1M              
          S45OS4xNTlcLzMyIn19fV19&Key-Pair-Id={hidden}&Signature={hidden}')   -- Is this a CDM issue?
2.  "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages              
          /httpx/_models.py", line 749, in raise_for_status                                           
              raise HTTPStatusError(message, request=request, response=self)                          
          httpx.HTTPStatusError: Client error '429 Too Many Requests' for url                         
          'https://onlyfans.com/api2/v2/users/OFCREATOR'                                           
          For more information check: https://httpstatuses.com/429       -- I guess hit a OF limit?
3.                             ^^^^^^^^^^^^^^^^^^^^^                                                 
            File                                                                                    
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packag              
          es/ofscraper/utils/of.py", line 191, in process_all_paid                                  
              username=operations.get_profile_info(model_id=model_id,username=username              
          ) or username                                                                             
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^              
          ^                                                                                         
            File                                                                                    
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packag              
          es/ofscraper/db/operations.py", line 95, in inner                                         
              raise E                                                                               
            File                                                                                    
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packag              
          es/ofscraper/db/operations.py", line 92, in inner                                         
              return func(*args,**kwargs,conn=conn)                                                 
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                  
            File                                                                                    
          "/Users/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packag              
          es/ofscraper/db/operations.py", line 204, in get_profile_info                             
              modelinfo=cur.execute(queries.profileDupeCheck,(model_id,)).fetchall()                
          or [(None,)]                                                                              
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                           
          sqlite3.OperationalError: no such table: profiles                  -- No clue

With unlimit, I get these:

1.        File                                                                                    
          "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions              
          /3.11/lib/python3.11/logging/__init__.py", line 1032, in handleError                      
              traceback.print_exception(t, v, tb, None, sys.stderr)                                 
              ^^^^^^^^^^^^^^^^^^^^^^^^^                                                             
          AttributeError: 'function' object has no attribute 'print_exception'   -- Not sure what this is.

**Comment by datawhores** [comment]
Yeah the changes were merge in the main branch anyways

Please make a new issue if this still persists in newer versions
