### ISSUE TITLE
Script Finished                                                                  Run Time:  0:00:11                                                               ||| ofscraper  --after 2000 --dupe

### ISSUE THREAD

**Issue by orithecapper** [datawhores/OF-Scraper#200]
**ofscraper  --after 2000 --dupe**
2000
 [start.startvalues:145]  config path:                              start.py:145
/home/your_username/.config/ofscraper/config.json                               
 [start.startvalues:146]  profile path:                             start.py:146
/home/your_username/.config/ofscraper/main_profile                              
 [start.startvalues:147]  log folder:                               start.py:147
/home/your_username/.config/ofscraper/logging                                   
Welcome to OF-Scraper Version 3.3.6
 [paths.cleanup:72]  Cleaning up temp files                          paths.py:72
                                                                                
                                                                                
 CDM service seems to be working

WARNING:Make sure you have all the correct settings for choosen cdm
https://of-scraper.gitbook.io/of-scraper/cdm-option

? What would you like to do? Download content from a user
Welcome, Ori  k | im4sad

╭──────────────────────────────────────────────────────────────────────────────╮
╰──────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
╰──────────────────────────────────────────────────────────────────────────────╯
? Which models do you want to scrape
: kitalovexoxovip
 [scraper.scrape_context_manager:369]                             scraper.py:369
==============================                                                  
starting script                                                                 
==============================                                                  
                                                                                
 [profiles.print_current_profile:138]  Using profile:            profiles.py:138
main_profile                                                                    
Status - UP
 [scraper.normal_post_process:177]  Progress 1/1 model            scraper.py:177
? Scrape entire paid page

[Warning: initial Scan can be slow]
[Caution: You should not need this unless your looking to scrape paid content fr
om a deleted/banned model] False
? Which area(s) would you like to scrape? ['Timeline']
 [timeline.get_timeline_media:129]                               timeline.py:129
Setting initial timeline scan date for kitalovexoxovip to                       
2000.01.01                                                                      
Hint: append ' --after 2000' to command to force scan of all                    
timeline posts + download of new files only                                     
Hint: append ' --after 2000 --dupe' to command to force scan of                 
all timeline posts + download/re-download of all files                          
                                                                                
                                                                                
╭──────────────────────────────────────────────────────────────────────────────╮
╰──────────────────────────────────────────────────────────────────────────────╯
 [filters.dupefilter:56]  Removing duplicate media                 filters.py:56
 [filters.posts_type_filter:89]  filtering Media to                filters.py:89
images,audios,videos                                                            
 [misc.medialist_filter:32]  forcing all downloads media count 0      misc.py:32
 [misc.download_picker:39]  kitalovexoxovip (0 photos, 0 videos, 0    misc.py:39
audios,  0 skipped, 0 failed)                                                   
 [scraper.scrape_context_manager:380]                             scraper.py:380
===========================                                                     
Script Finished                                                                 
Run Time:  0:00:11                                                              
===========================                                                     
                                                                                
? Do you want to continue with script 
❯ Yes
  No

SHOW INSTRUCTIONS: [ALT+V] or [CTRL+V]

**Comment by datawhores** [comment]
What exactly is wrong here

**Comment by orithecapper** [comment]
> What exactly is wrong here please use a paste site if you need to paste a long log

Hey I managed to fix it :( 

it was the CDM

I tried this given api
and it didnt work 


why does a different CDM makes it work ????
![image](https://github.com/datawhores/OF-Scraper/assets/131520229/7d1841d4-7435-4fbf-8034-4a1a138d6f62)

**Comment by datawhores** [comment]
Well manual will usually be more stable since it only requires one extra request, and not two 

I'd have to see a clear log file to really get a sense of the issue though

**Comment by orithecapper** [comment]
even if its my problem and I didnt noticed it... it certainlly means its a UI problem

**Comment by datawhores** [comment]
Well manual will usually be more stable since it only requires one extra request, and not two 

I'd have to see a clear log file to really get a sense of the issue though

**Comment by datawhores** [comment]
Please follow the issue template
