### ISSUE TITLE
New version doesnt work [[Version 3.3.3 working]]

### ISSUE THREAD

**Issue by orithecapper** [datawhores/OF-Scraper#205]
Hey I think last version fucked up something 

![image](https://github.com/datawhores/OF-Scraper/assets/131520229/a72a31b0-30ac-456b-88cd-90b48e462b36)

--------
command used on both screenshots
[ori@npc_onlyfans_girl ~]$ ofscraper -u kitalovexoxovip --after 2000 --dump

---------

===================================

-------
^CERROR: Operation cancelled by user
^[[A[ori@user ~]$ pip install ofscraper==3.3.3
Collecting ofscraper==3.3.3
-----------------
fixed the issue 

-------------
**SCREENSHOT WITH ISSUE (THE LATEST VERSION)**
![image](https://github.com/datawhores/OF-Scraper/assets/131520229/2d0f2a61-d2a6-461e-9616-d4088da6184f)

**Comment by orithecapper** [comment]
UPDATE 
in version 3.3.3 
TWO DIFFERENT FOLDER NAMES 


![image](https://github.com/datawhores/OF-Scraper/assets/131520229/c9add82a-343f-4608-8d70-8d4090d554cf)

**Comment by orithecapper** [comment]
DUPE ISSUE WITH CDM / DRM VIDEOS

**Comment by datawhores** [comment]
try 3.4
