### ISSUE TITLE
Anyway to download the text content of messages?

### ISSUE THREAD

**Issue by BakedOcclusion** [datawhores/OF-Scraper#210]
Any way to include the text messages of chats along w/ video/images?

**Comment by Puk0** [comment]
Con FastStone Capture > Capturar ventana con desplazamiento 

![2023-09-17 22-36-44](https://github.com/datawhores/OF-Scraper/assets/138377242/cd6a6a50-5094-4143-b8cb-17f9a11943ae)

o solo el texto en las imágenes o videos con {text} en "file_format":

![2023-09-17 22-41-25](https://github.com/datawhores/OF-Scraper/assets/138377242/d1857bb6-b6af-48bd-953e-a999f657c1c1)

**Comment by BakedOcclusion** [comment]
Let me clarify, I'm looking for output in the fashion of     Model: texthere    User: textresponse  saved to a txt file, in a very similar way it does this for the images/videos, just need to chat logs.

**Comment by datawhores** [comment]
Not built in everything is should be the database
So at this point sql would be the only way

**Comment by datawhores** [comment]
This has been added to 3.9
