### ISSUE TITLE
Select less filters and userlist error?

### ISSUE THREAD

**Issue by lemyqross** [datawhores/OF-Scraper#213]
2023.09.11_00:44_main_a9734ae_package and [ofscraper_windows_a9734ae.zip](https://github.com/datawhores/OF-Scraper/releases/download/a9734ae/ofscraper_windows_a9734ae.zip)
 - Browser: Chrome, version: Version 117.0.5938.92 (Official Build) (64-bit)
- Downloaded and Installed Python from the https://www.python.org/downloads/   and 3.11.5 version
- Windows 10 pro

![Screenshot_11](https://github.com/datawhores/OF-Scraper/assets/140381523/66b97c65-1715-40d0-bc3e-9450350b628c)

**Comment by datawhores** [comment]
what arguments did you pass
are you subscriped or have subscriped to any users on this account
