### ISSUE TITLE
Scraping Of Profile

### ISSUE THREAD

**Issue by deadbeatdandylyon** [datawhores/OF-Scraper#214]
Is there an easier way that when you go to select on a person to scrape the whole profile, is there a way for it to automatically download the whole profile without having to go to each individual item? 

- Timeline
- Pinned
- Archived
etc

**Comment by Puk0** [comment]
- 1.- pones en "variables del entorno" la carpeta donde esta ofscraper 

- 2.- abres el "simbolo del sistema"

- 3.- ofscraper -u <user> -o all

**Comment by deadbeatdandylyon** [comment]
Thank you for the information, however I am not entirely sure on how to do that exactly.

**Comment by datawhores** [comment]
Discord should be able to help with this
