### ISSUE TITLE
Stuck while scraping

### ISSUE THREAD

**Issue by deadbeatdandylyon** [datawhores/OF-Scraper#216]
I am stuck at this screen and not sure what to do?

![image](https://github.com/datawhores/OF-Scraper/assets/59564520/2a4a3556-e9b3-45c0-beef-b7c095443d95)

**Comment by Vasault** [comment]
same here, it took like 22 mins to download the whole batch, but it's been stuck in 99% for like 15 mins

**Comment by deadbeatdandylyon** [comment]
I found what I did was just closed out and re ran it and it worked but still took a bit

**Comment by Vasault** [comment]
it worked but i have no idea where is the downloaded content located at lol

**Comment by deadbeatdandylyon** [comment]
The download location should be located in your `.config` file it will tell you at the top just open it up in notepad. 

you can find the `.config` file `c:\Users\<Username>\.config\ofscraper\config`

that is also where you can edit the download location to change where you want it to download. 

but by default the download location can be found `c:\Users\<Username>\Data\Ofscraper`

**Comment by Vasault** [comment]
found it, thanks, tho i noticed is not downloading everything from some of the content creators

**Comment by deadbeatdandylyon** [comment]
Well when the download is completed - it will tell you exactly what was download , it breaks it down to videos / pictures / audio / etc depending on what you selected to download, and it also doesn't download any duplicates. so if it didn't download everything make sure that you are selecting everything to download 

so when you come to this screen make sure everything is enabled by `shift+right arrow`

![image](https://github.com/datawhores/OF-Scraper/assets/59564520/92eea71c-c75f-4674-9030-e933ae3c3113)

**Comment by datawhores** [comment]
Please update and mention if this still occurs
the new versions should be better about shutting down
