### ISSUE TITLE
Download deleted purchase

### ISSUE THREAD

**Issue by TheSinfulKing** [datawhores/OF-Scraper#218]
So I am subbed to a model whose account is active (not deleted). I bought a video from her a few days ago. She suddenly deleted the video but it appears in my Purchased still. How do I download this? The blob url does not work for manual download, and there is no copy link to video since she deleted it

**Comment by Puk0** [comment]
No tiene copiar enlace?


![2023-09-28 00-49-11](https://github.com/datawhores/OF-Scraper/assets/138377242/1ef2e96c-0180-4878-9e8e-7aa8824f6b3a)

**Comment by datawhores** [comment]
You have to select the scrape paid arg. Read the docs. In the command ref page 

Or select yes when asked to scrape the entire paid page
