### ISSUE TITLE
429 and model missing

### ISSUE THREAD

**Issue by CannotTouch** [datawhores/OF-Scraper#224]
Hi,
from yesterday the error 429 is back (i think they changed again something) while the initial scraping of the list of subscriptions.
And when it pass I notice that there are several missing model in the list.
thanks for support

**Comment by n30liberal** [comment]
I'm also missing a handful of models. Didn't notice the issue until a new one wasn't showing up.

**Comment by datawhores** [comment]
Can you create a log file and send it here

Only need the retrieval of username section

**Comment by CannotTouch** [comment]
can you pass me an email to send to you all the debug log privately, plz

**Comment by datawhores** [comment]
datawhores@riseup.net

**Comment by datawhores** [comment]
@CannotTouch 

Do you have a specific model that is missing

The numbers are not accurate on the onlyfans site

expired seems to include deactivated accounts. I've manually checked the count a few times and it always off at least by 100 for me, and I have less then a 1000 account. 

You can see how much that would effect your numbers

Active should be more accurate, but I've notice the number displayed on the site might be off by a few compared to the actual number if you scroll donw

**Comment by datawhores** [comment]
@n30liberal 

Do you have a  specific model missing or just issue with numbering

**Comment by CannotTouch** [comment]
sadly the browser find didn't work with the count (with all the active page loaded it just count 21 @. I have tryed other search but nothing). I have tryed to print to pdf, but nothing too. Tryed to load only text, and nothing. But using the OF search bar the models that i noticed that are missing in the scraper are all in the active section. No disabled for any of them.

**Comment by CannotTouch** [comment]
i don't know where is the problem yet, but i have found a workaround... i have insert the models (that I noticed that aren't in the scraped list) in an OF list and than with 'ofscraper --sub-status active -ul LIST_NAME' the scraper saw them and so from there scraped it normally.
the strange is that it don't scrape it with the 'ofscraper --posts all --username model_user_name'

**Comment by datawhores** [comment]
Yeah I did this 3 months ago

But from what I'm seeing I think they changed it to make the list load dynamically
 
I don't have any missing models so this is hard to diagnose 
It would be helpful to know the offset on onlyfans and match that to what of-scraper is outputting for example

![image](https://github.com/datawhores/OF-Scraper/assets/67020411/294d0b04-4252-44cb-bcff-03f571512f16)
compare the results of that  to see if of-scraper gets the same name

**Comment by CannotTouch** [comment]
Is there a way using the `ofscraper --posts all --username model_name` to avoid to retrive all the list of names before the scraping? @datawhores

**Comment by original-copy** [comment]
Would appear that only models without DRM are showing up.

@CannotTouch , how do you get the -ul function to work?
I created a list within OF called Test but get the following error.

ofscraper --sub-status active -ul Test
usage: OF-Scraper [-v] [-cg CONFIG] [-r PROFILE] [-l {OFF,STATS,LOW,NORMAL,DEBUG,TRACE}]
                  [-dc {OFF,STATS,LOW,NORMAL,DEBUG,TRACE}] [-p {PROMPT,STATS,LOW,NORMAL,DEBUG,TRACE}] [-h]
                  [-u USERNAME] [-eu EXCLUDED_USERNAME] [-d DAEMON] [-g] [-c] [-a {like,unlike}] [-e] [-o POSTS] [-sk]
                  [-ft FILTER] [-sp] [-dt {protected,normal}] [-lb LABEL] [-at {paid,free}] [-rw {active,disabled}]
                  [-ss {active,expired}] [-be BEFORE] [-af AFTER] [-st {name,subscribed,expiring,price}] [-ds] [-uf]
                  [-nc] [-k {auto,manual}] [-dr {dc,deviint}] [-pc]
                  {post_check,msg_check,paid_check,story_check,manual} ...
OF-Scraper: error: argument command: invalid choice: 'Test' (choose from 'post_check', 'msg_check', 'paid_check', 'story_check', 'manual')

**Comment by datawhores** [comment]
@264

**Comment by j-ktz** [comment]
I've noticed this with one specific model. I can only download when   I do manual URL pulls  but the model doesn't display  in the  list.
