### ISSUE TITLE
Is it possible to retroactively decrypt .part files?

### ISSUE THREAD

**Issue by blacknyellow758** [datawhores/OF-Scraper#227]
Hey, so i've scraped an account without properly setting CDM private key/client id, therefore downloading lots of .part files. I have only now gotten around to doing it properly, but my subscription to this content creator has now expired.
It doesn't look that way in the documentation (specifically, the command reference doesn't seem to mention a functionality that would allow for this), so I'm asking here directly: Is it possible to retroactively decrypt .part files?

If so; how?
If not, consider this issue resolved.

**Comment by SpoogLord** [comment]
There is a chance the file fully downloaded before the scraper marked it as "failed" in which case you can either rename it to [filename].mp4 or .jpg. If that results in an unusable or "corrupt" file it is likely unsalvageable, though I'm no expert

**Comment by datawhores** [comment]
No you need to have access to the file on onlyfans so you can get the key
