### ISSUE TITLE
Specific model not downloading

### ISSUE THREAD

**Issue by hammerheaddf** [datawhores/OF-Scraper#232]
I tried to download content from one specific model, from 2 different computers, and all I get is metadata. The content seems to be scraped, but when it comes to download, nothing comes. I have an active subscription to her page. Other models, whether free or paid, can be downloaded just fine.

**Comment by SpoogLord** [comment]
The model could have their content DRM protected, in which case the files will output as .part files in your "base-directory" (a setting in the config), by default it seems to be C:/

**Comment by hammerheaddf** [comment]
I turned the log in for a new attempt and got this. Looks like a database issue.

2023-10-14 18:44:37:\[logger.inner:193]  failed with exception: UNIQUE constraint failed: labels.id, labels.post_id
                                      2023-10-14 18:44:37:\[logger.inner:193]  Traceback (most recent call last):                            File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/commands/scraper.py", line 185, in normal_post_process        combined_urls=OF.process_areas( ele, model_id)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/of.py", line 281, in process_areas
    labels_dicts = process_labels(model_id,username)                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/of.py", line 222, in process_labels
operations.write_labels_table(labelled_post,list(filter(lambda post:(labelled_post.label_id,post.id) not in curr,labelled_post.posts)), model_id=model_id,username=username)                              File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/db/operations.py", line 105, in inner                         raise E                                          File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/db/operations.py", line 92, in inner
    return func(*args,**kwargs,conn=conn)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^             File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/db/operations.py", line 336, in write_labels_table
    curr.executemany(queries.labelInsert,insertData)
sqlite3.IntegrityError: UNIQUE constraint failed: labels.id, labels.post_id
2023-10-14 18:44:37:\[scraper.scrape_context_manager:380]                                            ===========================
Script Finished
Run Time:  0:03:51
===========================                        
 2023-10-14 19:07:33:\[start.main:63]  Finished Script

**Comment by pirate-cpu** [comment]
> 

Are you willing to edit this post to remove the model's name? Just to avoid any potential takedown requests.

**Comment by hammerheaddf** [comment]
> > 
> 
> Are you willing to edit this post to remove the model's name? Just to avoid any potential takedown requests.

Done

**Comment by datawhores** [comment]
This is a very strange error
Try to upgrade to 3.4 or 3.4.1
Make a new issue if this persists
