### ISSUE TITLE
Loads and shuts down when accessing  list of subscriptions 

### ISSUE THREAD

**Issue by lushlabrador** [datawhores/OF-Scraper#233]
Two days ago the program worked fine, and I managed to do my daily scrape. But when I tried it again the same afternoon, the program first failed to log in. I then noticed I had been logged out of Onlyfans on this machine. Logged back in, updated all the files with fresh cookies etc. Started the program again, log in works fine but then it get stuck gathering list of models for a good 5 minutes and then quickly display this text before closing the program:

> ? What would you like to do? 
> 
> Download content from a user
> 
> Warning: Numbering on OF site can be iffy
> Example Including deactived accounts in expired
> See: https://of-scraper.gitbook.io/of-scraper/faq#number-of-users-doesnt-match-account-number
> 
> Traceback (most recent call last):
> File "__main__.py", line 15, in <module> 
> File "__main__.py", line 10, in main File "start.py", line 129, in main 
> File "start.py", line 126, in main File "start.py", line 62, in main
> File "commands\scraper.py", line 416, in main File "commands\scraper.py", line 398, in main 
> File "commands\scraper.py", line 429, in scrapper File "utils\exit.py", line 89, in inner
> File "utils\exit.py", line 82, in inner
> File "commands\scraper.py", line 58, in process_prompts
> File "commands\scraper.py", line 274, in run
> File "commands\scraper.py", line 332, in run_helper
> File "commands\scraper.py", line 316, in run_helper
> File "utils\userselector.py", line 37, in getselected_usernames
> File "utils\userselector.py", line 54, in parsed_subscriptions_helper File "utils\userselector.py", line 112, in filterNSort
> Exception: You have filtered the user list to zero
> Please Select less restrictive filters and userlists
> [968] Failed to execute script '__main__ due to unhandled exception!
> 

Tried the program again yesterday and  today, Same issue. Downloaded latest version of the scraper and the issue remains. Anyone know what the issue may be? Flying by the seats of my pants when it comes to coding, but so far I managed to run this script and it's predecessor for a few years

**Comment by datawhores** [comment]
If you run with --output debug you should get the number of accounts as the filters are applied

Try with 3.4.2

**Comment by datawhores** [comment]
This was change to force change of filters rather then crash
