### ISSUE TITLE
Cannot retrieve cookies from Edge

### ISSUE THREAD

**Issue by Arko109** [datawhores/OF-Scraper#234]
**Describe the bug**
When attempting to retrieve cookies from Edge, the script has an error because the path contains a `..` that is not parsed correctly.

It seems like the script is attempting to access the local app data folder by using the roaming app data path and then backtracking one step (`AppData\\Roaming\\..\\Local`), instead of direct access (`AppData\\Local`).

**To Reproduce**
1. Start script
2. Select `Edit auth.json file`
3. Select `Edge`
4. The script will terminate with error

**Expected behavior**
The script should retrieve cookies from Edge without errors

**Screenshots/Logs**
[Traceback](https://paste.passtheheadphones.me/?153d2ec49e692941#4caKZAuu4LvBNFGDXpZvESZ8VvF2yH2C6bDC9WJu4iEd)

**Desktop:**
 - OS: Windows 11 Pro 22621.2428
 - Browser: Edge 118.0.2088.46
 - installed with pip, Python 3.10.12

**Comment by datawhores** [comment]
This would be better placed in the browser cookie repo
https://github.com/borisbabic/browser_cookie3

I have not change any of the paths in the module from the defaults
