### ISSUE TITLE
KeysDB Help?

### ISSUE THREAD

**Issue by tallgirlsfinishlast** [datawhores/OF-Scraper#239]
So I went to the website and his FAQ wasnt too easy to understand to say the least. I have an API key on my profile when I look, at it, but how do I verify my discord? I followed the link to discord on the site but it said invite was invalid... Do I just post my API key in my config file?

Any help would be super appreciated!

**Comment by Puk0** [comment]
Si usas "key-mode-default": "keydb",
ocupas la api en "keydb_api": "",
la api esta en https://keysdb.net/api (entras con tu cuenta Discord)
![2023-10-19 00-47-30](https://github.com/datawhores/OF-Scraper/assets/138377242/6631238a-6080-432e-9a57-ff72713d1b6a)

**Comment by tallgirlsfinishlast** [comment]
> Si usas "key-mode-default": "keydb", ocupas la api en "keydb_api": "", la api esta en https://keysdb.net/api (entras con tu cuenta Discord) ![2023-10-19 00-47-30](https://user-images.githubusercontent.com/138377242/276513892-6631238a-6080-432e-9a57-ff72713d1b6a.jpg)

Youre a saint! :) thank you so much! Marking as solved :)
