### ISSUE TITLE
Downloading user's content doesn't work the 2nd time

### ISSUE THREAD

**Issue by MickMod** [datawhores/OF-Scraper#240]
Hello, when I first downloaded the media from user "XYZ", it worked fine but had some issues with file naming.
I deleted the downloaded folder and fixed the error in the config file, but when I try to download this same account again, it seems to know the amount of photos/videos from the account.
Sadly it doesn't download anything and finishes in ~20 seconds.

I've tried moving download directories and deleting account config files but to no avail.

I also tried running the program with the "--after 2000 --dupe" flag (through CMD) to see if that would fix the issue, but that doesn't seem to make any difference.

Does anyone know how to resolve this issue?

**Comment by Puk0** [comment]
- ¿qué "archivos de configuración borraste"?
- ¿borraste la carpeta ".data\xyz" ?

**Comment by CannotTouch** [comment]
have you try to delete the XYZ's metadata directory too? you found it in the C:\Users\user_name\.config\ofscraper\main_profile\.data (if you don't have changed it)

**Comment by MickMod** [comment]
> have you try to delete the XYZ's metadata directory too? you found it in the C:\Users\user_name.config\ofscraper\main_profile.data (if you don't have changed it)

I have tried this as well, as well as restarting the computer, re-downloading the EXE, running it both as an admin and normally.
It doesn't seem that launching the EXE through CMD with the --dupe flag actually does anything.
What folders does the EXE generally make/use? I'll try deleting everything and starting over to see if that works, because it worked fine for the first download.

**Comment by zxcvb3** [comment]
any fix to this? i'm seemingly encountering the exact same problem...
i'm using ver 3.3.10, which is the latest that pip will serve to me
when trying to download from the same profile again the script finishes in 2 seconds, seemingly without even checking anything. i have tried all the suggestions above

>  ` [filters.dupefilter:56]  Removing duplicate media                                                        filters.py:56
>  [filters.posts_type_filter:89]  filtering Media to images,audios,videos                                  filters.py:89
>  [misc.download_picker:39]  ---------- (0 photos, 0 videos, 0 audios,  0 skipped, 0 failed)                misc.py:39
>  [scraper.scrape_context_manager:380]                                                                    scraper.py:380
> ===========================
> Script Finished
> Run Time:  0:00:02
> ===========================`

my internet connection is horrible and when i use this script it typically stalls after awhile with no more downloading, but the timer still ticking, that's when i force close it and try it again and get whatever files were missed (to be safe i remove all .part files just in case they're corrupted or something) and this usually works for me
but this time the script just dies immediately

as a test i tried it on another profile and i was able to run the script more than once without issue (doing a partial download, ctl+c, then trying again), so i'm not sure what triggers the problem

i am getting this error message when starting up, and wasn't sure if that was related, but ignoring this i was still able to run the script somewhat successfully on the problem account until trying it a second time

> CDM service cdrm2 timed out and seems to be down
> This may cause a lot of failed downloads
> Please confirm by checking the url:http://172.106.17.134:8080/wv
>  Consider switching
> https://of-scraper.gitbook.io/of-scraper/cdm-options

**Comment by Witty-tent** [comment]
I have this issue as well.  Updated to 3.3.13 but had the issue on the previous version.  MacOS with Python 3.10.12.

Command ran `ofscraper --after 2000 --dupe --log debug -nc -u "$ofprofile"`, but issue also occurs when running application interactively.  $ofprofile is a OF account I was able to scrape previously

I've deleted the ~/.config/ofscraper/main_profile directory.
I've deleted the ~/.config/ofscraper/cache_* directories, as well as trying json and sqlite caching
I've moved/deleted the ~/Data/ofscraper/"$ofprofile" directory

Even with doing all three of those deletions, I still run into the issue.  Letting the application run eventually will cause it to error out.  

I've attached a sanitized and truncated debug log.  The "locking protocol" error repeats for every post attempted to download, I've truncated the log to only show one of the errors.

[ofscraper_main_profile_2023-11-DD.log](https://github.com/datawhores/OF-Scraper/files/13384686/ofscraper_main_profile_2023-11-DD.log)

**Comment by JimPick123** [comment]
I had a similar issue with the "CDM service cdrm2 timed out and seems to be down" message and content from specific creators not downloading and freezing the program. Deleted their metadata folders and ran "ofscraper --key-mode cdrm --no-cache" and it worked for me
