### ISSUE TITLE
Appending the --after2000 rule

### ISSUE THREAD

**Issue by tallgirlsfinishlast** [datawhores/OF-Scraper#241]
Im downloading all of my content onto an external hard drive that I also use for other stuff, and so to avoid overloading it Ill sometimes terminate the scraper to use it for something else.

I seen that appending the --after-2000 rule (or however its syntaxed) gives me an error when I run "ofscraper" but theres no other time that I see in which Im able to add any sort of arguement. Maybe Im missing something? Thanks!

**Comment by SpoogLord** [comment]
Syntax is very important when working with command line scripts, the syntax you need would be `ofscraper --after 2000`, any other way would not work, spaces or dashes and such in the wrong places ruin everything. 

(you can also stack arguments by adding a space between them, ex `ofscraper --after 2000 --dupe`)

If that info alone isn't enough to solve your problem then more info would be needed, something like a log or a screenshot of the specific error would likely be enough for someone to know the answer to your problem. (add the `--log debug` argument to produce a log in C:\Users\USERNAME\.config\ofscraper\logging)

**Comment by tallgirlsfinishlast** [comment]
Okay so I managed to get my syntax right on my own! Thank you so much for your help :)

This will hopefully be my last question for awhile.

I couldnt find the proper way to scrape just a select few users in one command. I tried putting them both as strings, seperated by commas, one  full string... and nothing hahaha any help is very much loved and appreciated!

**Comment by SpoogLord** [comment]
It seems to work for me as 2 separate arguments, so something like `ofscraper -u [model name] -u [model name] --after 2000`. The documentation on that argument is kinda lacking, so I'm not sure if you _can_ do it as a string, but it works as multiple arguments

**Comment by SpoogLord** [comment]
alternatively you can do `ofscraper -ss active -u ALL --after 2000` to scrape everyone you're subbed to, skipping expired subs
