### ISSUE TITLE
Purchased content

### ISSUE THREAD

**Issue by rciptv2019** [datawhores/OF-Scraper#242]
I don't see the option in the config file that purchased content can be separated from the rest of the content in the download. Let's say there is an audio, video and photo folder, but there is no way for the purchased content to go into a folder called "paid" for example. Isn't there a way to do it?

**Comment by cjb900** [comment]
there is no option in the config but there are options as referenced here on how to scrape paid content https://of-scraper.gitbook.io/of-scraper/command-reference

**Comment by datawhores** [comment]
{value}=Value of the content. Paid or Free
https://of-scraper.gitbook.io/of-scraper/config-options/customizing-save-path#dir_path
