### ISSUE TITLE
Setting initial date

### ISSUE THREAD

**Issue by CannotTouch** [datawhores/OF-Scraper#243]
Probably this is not a bug but a feature request.

When you use `ofscraper --sub-status active --posts all -ul collection_name` without the `--after`  it set the initial date automatically at the 1970 even if that model was yet scraped before.

So, if not a bug, my suggest is to set the initial date (if `-- before/after` isn't user ofc)  automatically to the latest scraped done for that model.

thanks for support

**Comment by datawhores** [comment]
I would have to see the logs, but some data isn't acquired via dates

part of the check is to make sure all the data has been downloaded previously, otherwise it will mess things up  if we skip to the latest date
