### ISSUE TITLE
Unable to get current active subs

### ISSUE THREAD

**Issue by ShadowSteve1** [datawhores/OF-Scraper#247]
I have version 2.4.6 installed on windows 11

every time i try and search for active renewal dates, active subscriptions, paid only

it gets to the end of the search Boolean and the script just exits

and doesn't display anything

if i try and leave the search defaults all i get is expired accounts and not ones i've subbed to

**Comment by cjb900** [comment]
version 2.4.6 is a really old version of the scraper. Its currently on 3.3.11. I would first try upgrading to a newer version and see if that helps.

**Comment by datawhores** [comment]
please update to a newer version
make a new issue if this persist
