### ISSUE TITLE
Help Request: Downloading metadata only

### ISSUE THREAD

**Issue by Dark-Obsidian** [datawhores/OF-Scraper#251]
I have a few thousand videos that I got before using `OF-Scraper`.

**Is there a parameter (or some other way) for OF-Scraper to just scrape the metadata**, and not download the videos themselves?... (I don't really want to download 2TB of videos over again! 🙂)

**Comment by datawhores** [comment]
yeah that shouldn't be too hard to add

**Comment by datawhores** [comment]
added
It will added metadata for posts,messages, etc

Also if you have the media already downloaded it will add metadata for that otherwise, it will still add a entry to the media table, but it will be set to not downloaded, and won't have the filename information
