### ISSUE TITLE
[Minor issue] URL error in help text

### ISSUE THREAD

**Issue by Dark-Obsidian** [datawhores/OF-Scraper#253]
### In CLI, there is a warning
```
Numbering on OF site can be iffy
Example Including deactived accounts in expired
See: https://app.gitbook.com/o/KULkvbsBAkF5q8PRvd1h/s/OlkVHnCqS3EnmDo4hGKm/~/changes/174/faq#number-of-users-doesnt-match-account-number
     ⬆️ However this URL is private
```
### Correction
For the URL above, presumably...
- Instead of: `https://app.gitbook.com/o/KULkvbsBAkF5q8PRvd1h/s/OlkVHnCqS3EnmDo4hGKm/~/changes/174/faq#number-of-users-doesnt-match-account-number`
- It should be: `https://of-scraper.gitbook.io/of-scraper/faq#number-of-users-doesnt-match-account-number`

**Comment by Bun-Bun** [comment]
Looks like this was already corrected. 

https://github.com/datawhores/OF-Scraper/commit/34c7f6cf733681f8004d0a22c419431bf0358684
