### ISSUE TITLE
Missing Model in List 

### ISSUE THREAD

**Issue by j-ktz** [datawhores/OF-Scraper#258]
**Describe the bug**
In list of users, I am missing a model I actively subscribe too. I can manually download a  post with a URL but unable to find user in  list to  download content. I've reset filter multiple times. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 12.6
 - Browser [e.g. chrome, safari] Chrome

**Comment by datawhores** [comment]
Make sure your using there  @name

**Comment by j-ktz** [comment]
Thanks for responding! Correct, I'm using their name. I start script, choose download from a user, my list of user populates, and they're not in the list. Even if I type in their name. Happy to attach log, but I'm not  downloading from the user so when should I have the log output?

**Comment by datawhores** [comment]
Just in show the log up to the username selection

You can ctrl c quit after
Make sure to use --log debug
So we can see a log file

**Comment by j-ktz** [comment]
Thank you! Log attached. Let me know if I can provide anything else. 
[ofscraper_main_profile_2023-11-27.log](https://github.com/datawhores/OF-Scraper/files/13476173/ofscraper_main_profile_2023-11-27.log)

**Comment by j-ktz** [comment]
Sure I messaged on discord but also the username is saltyboys

**Comment by datawhores** [comment]
Yeah you should upgrade
2.6.4 is very old

**Comment by datawhores** [comment]
I add a note to the docs to upgrade

**Comment by datawhores** [comment]
what version of python do you have

**Comment by j-ktz** [comment]
Python 3.10.12

**Comment by j-ktz** [comment]
I've tried  `pipx install ofscraper==3.3.3 --force` and  I get this error:

`Some possibly relevant errors from pip install:
    ERROR: Ignored the following yanked versions: 1.82, 1.83
    ERROR: Ignored the following versions that require a different python version: 1.4.1 Requires-Python >=3.9.0,<3.11.0; 1.4.2 Requires-Python >=3.9.0,<3.11.0; 2.7.1 Requires-Python >=3.7.0,<3.12; 2.7.10 Requires-Python >=3.7.0,<3.12; 2.7.11 Requires-Python >=3.7.0,<3.12; 2.7.12 Requires-Python >3.7.0,<3.12; 2.7.13 Requires-Python >=3.7.0,<3.12; 2.7.14 Requires-Python >=3.7.0,<3.12; 2.7.2 Requires-Python >=3.7.0,<3.12; 2.7.3 Requires-Python >=3.7.0,<3.12; 2.7.4 Requires-Python >=3.7.0,<3.12; 2.7.5 Requires-Python >=3.7.0,<3.12; 2.7.6 Requires-Python >=3.7.0,<3.12; 2.7.7 Requires-Python >=3.7.0,<3.12; 2.7.8 Requires-Python >=3.7.0,<3.12; 2.7.9 Requires-Python >=3.7.0,<3.12; 3.0 Requires-Python >3.7.0,<3.12; 3.0.1 Requires-Python >3.7.0,<3.12; 3.0.10 Requires-Python >3.7.0,<3.12; 3.0.11 Requires-Python >3.7.0,<3.12; 3.0.12 Requires-Python >3.7.0,<3.12; 3.0.2 Requires-Python >3.7.0,<3.12; 3.0.3 Requires-Python >3.7.0,<3.12; 3.0.4 Requires-Python >3.7.0,<3.12; 3.0.5 Requires-Python >3.7.0,<3.12; 3.0.6 Requires-Python >3.7.0,<3.12; 3.0.7 Requires-Python >3.7.0,<3.12; 3.0.8 Requires-Python >3.7.0,<3.12; 3.0.9 Requires-Python >3.7.0,<3.12; 3.1.1 Requires-Python >=3.8.0,<3.12; 3.1.2 Requires-Python >=3.10.0,<3.12; 3.2 Requires-Python >=3.10.0,<3.12; 3.2.1 Requires-Python >=3.10.0,<3.12; 3.2.2 Requires-Python >=3.10.0,<3.12; 3.2.3 Requires-Python >=3.10.0,<3.12; 3.2.4 Requires-Python >=3.10.0,<3.12; 3.2.5 Requires-Python >=3.10.11,<3.12; 3.3 Requires-Python >=3.10.11,<3.12; 3.3.1 Requires-Python >=3.10.11,<3.12; 3.3.10 Requires-Python >=3.10.11,<3.12; 3.3.12 Requires-Python >=3.10.11,<3.12; 3.3.2 Requires-Python >=3.10.11,<3.12; 3.3.3 Requires-Python >=3.10.11,<3.12; 3.3.4 Requires-Python >=3.10.11,<3.12; 3.3.5 Requires-Python >=3.10.11,<3.12; 3.3.6 Requires-Python >=3.10.11,<3.12; 3.3.7 Requires-Python >=3.10.11,<3.12; 3.3.8 Requires-Python >=3.10.11,<3.12; 3.4 Requires-Python >=3.10.11,<3.12; 3.4.1 Requires-Python >=3.10.11,<3.12
    ERROR: Could not find a version that satisfies the requirement ofscraper==3.3.3 (from versions: 0.0.0, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.51, 1.60, 1.61, 1.62, 1.63, 1.65, 1.70, 1.71, 1.72, 1.73, 1.74, 1.75, 1.80, 1.81, 1.86, 1.87, 1.95, 1.95.1, 1.95.2, 2.0, 2.0.1, 2.1, 2.4, 2.4.1, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5, 2.6, 2.6.1, 2.6.3, 2.6.4)
    ERROR: No matching distribution found for ofscraper==3.3.3

Error installing ofscraper from spec 'ofscraper==3.3.3'.
`

**Comment by j-ktz** [comment]
Installing 3.4.3 worked and resolved my issue! Thank you!
