### ISSUE TITLE
Program hangs when scraping and stops downloading

### ISSUE THREAD

**Issue by adam-gh94** [datawhores/OF-Scraper#259]
When scraping, the program hangs after a certain amount of time and does not download anything further, although it still shows as downloading. The only way to fix this is to close the program and restart it where it will work for a while before hanging again. 

![Screenshot 2023-11-26 130642 copy](https://github.com/datawhores/OF-Scraper/assets/152073253/7490ec68-5a66-48f5-b793-4481344cb6e5)

In the screenshot, the program has been stuck at 65/2161 for over ten minutes.

After leaving for long enough, the program sometimes gives the error 'An existing connection was forcibly closed by the remote host'.

Any idea what could be causing this?

**Comment by jxmorrow** [comment]
I see this fairly regularly, but I've never caught any explanation for why it happens in logs. I don't think I've ever seen the "connection forcibly closed" message. My best guess is that it's something OF is doing on their server side, trying to block scraping. I've adjusted the threads and download semaphores to see if slowing down might help, but that doesn't seem to have any effect one way or the other. For the most part, restarting the container will cause it to run all the way through on my 2nd or 3rd attempt.

**Comment by adam-gh94** [comment]
The majority of the time when it hangs it doesnt give the connection forcibly closed error, i've had it running for hours in the past and it stays on the downloading screen with no error but just hangs, so not sure if it is to do with the OF server side. The connection forcibly closed error has only happened a handful of times and might be a separate issue, or just an occasional bug.

It's a pain though as when you're scraping a creator with thousands of posts and you have to sit and watch it to keep restarting it when it hangs and this takes forever.

**Comment by adam-gh94** [comment]
Upgrading to 3.4 looks to have fixed this now, thanks for your help!
