### ISSUE TITLE
Asyncio Error?

### ISSUE THREAD

**Issue by dq-heard** [datawhores/OF-Scraper#267]
Apologies for any formatting issues or for not having a log. I don't know how to capture one, but will figure out how to do so if needed. For reference, I'm using Manjaro Linux, Chromium 120, & Python 3.11.6 as my setup.

At first, I was having a Traceback error similar to #263 where the mp4decrypt and ffmpeg weren't defined. Already had ffmpeg on my PC, but downloaded the Bento4 package and copied it to the same spot as defined in #263.

With that being fixed, this became the new error: 
![Screenshot_20231209_102800](https://github.com/datawhores/OF-Scraper/assets/111152363/85925a6e-c249-479d-89bf-53a5110715d0)

...and there was another Exception that came after it:
![Screenshot_20231209_102907](https://github.com/datawhores/OF-Scraper/assets/111152363/1fd6d100-7ad6-456f-a784-71b65e293e32)

With mp4decrypt being in the right location, I think (?) that isn't the problem anymore. It still comes up in the error, so I'm not sure. Also, I have no idea what Asyncio is or how it's affecting anything, but I see it came up a bit while reading the traceback.

Any help with this is greatly appreciated.

**Comment by datawhores** [comment]
Yeah I seen this error a few times

But it is not something I've experienced yet
What version of the script are you on

**Comment by dq-heard** [comment]
I was running 3.4.4 at first, but I recently updated to the most recent one. Same thing.

**Comment by datawhores** [comment]
Yeah I think it is good enough just to remove patch_print here
It is not meant to be used in the way I have it here.

See latest commit
