### ISSUE TITLE
What happens if the destination runs out of space?

### ISSUE THREAD

**Issue by avekifes** [datawhores/OF-Scraper#268]
Is it just my imagination, or is it possible to end up with missing files if you accidentally run out of space on the destination drive during a session? What I mean is this:

1. Run script, destination runs out of space
2. Clear up space on destination drive
3. Run script again
4. Account still has missing files because the script has logged them as having been downloaded already

Is this what's happening?

**Comment by cjb900** [comment]
From my experience, if the drive runs out of space it should have stopped working. Meaning the scraper should not have continued.  If you know what is missing you can download it manually by adding `manual --url <post URL>`. If you do not know what is missing now that you have freed up space you may be better off deleting everything downloaded and also deleting the model DB file and starting over.

**Comment by datawhores** [comment]
Well depends on what files your clearing up

**Comment by datawhores** [comment]
So writing to the disk is based on what python has to interact with the operating calls

It should raise an ioerror
https://stackoverflow.com/questions/62795369/what-happens-when-disk-space-runs-out

But it might retry the download until the retry count is filled

**Comment by avekifes** [comment]
Interesting. The script keeps going for me if the destination is out of space...or, at least, I think it does, as the script doesn't throw any errors and ends like it normally does (i.e., "Do you want to continue with the script?").

Anyway, two more questions:

1. Is there a command that I can use to verify whether my files line up with what's on OF server-side?
2. If I use the --dupe command, are files that I previously downloaded but no longer exist (e.g., Stories) retained?

**Comment by datawhores** [comment]
I added a space checker

It check before scanning for content
and just before downloading to disk

downloads are batched together with async, so if your limited on space it is a good idea to set this fairly high amount
