### ISSUE TITLE
pushing to discord only works once when running in daemon mode 

### ISSUE THREAD

**Issue by cjb900** [datawhores/OF-Scraper#271]
**Describe the bug**
it doesn't seem like the push to discord is working properly. It work once when i start the scraper but since i'm running it in daemon mode when it runs again its not pushing to discord. It was working on 3.3.3 and stopped working on 3.5.4. I even tried with the latest ofscraper_linux_1258192s.

**To Reproduce**
Steps to reproduce the behavior: Use the latest pip version 3.5.4 and add a discord web hook to your config then run the scraper in daemon mode with --discord low. It will push to discord once but never seems to do it the next time the scraper runs
Hint: The full command i'm normally using is `ofscraper --daemon 120 --username ALL --sub-status active --posts all --discord low` but i also tried with just one model running `ofscraper --daemon 5 --username <model username> --post all --discord low`

**Expected behavior**
prior to updating to 3.5.4 was on 3.3.3 when running the scraper in daemon mode with --discord low it would push to discord every time the scraper re-ran. 

**Desktop (please complete the following information):**

- OS: Ubuntu server 22.04.3 and Ubuntu 23.10
- Browser: Firefox 120.01
- binary or python both were tried 
- python version if installed via pip or pypi on Ubuntu server 3.10.12 and on Ubuntu 3.11.6

let me know if any additional information is needed.

**Comment by datawhores** [comment]
This has been fixed
