### ISSUE TITLE
Pre-select sorting before starting the lengthy profile search?

### ISSUE THREAD

**Issue by mm125Y** [datawhores/OF-Scraper#272]
Is there an option to pre-select how accounts are sorted **before** the lengthy searching phase?  There's a ton of time spent calling up old expired profiles that I have no interest in, so it be nice to default to a sorting option that cuts that out from the search completely.  Does a feature like this exist already?

**Comment by datawhores** [comment]
The only real control over data fetching we have is 
--user-list 
You can do 
-- userlist  "ofscraper.active"

This will restrict your account to only getting active accounts

There is also the sort options but these only effect what is seen by the user, the full user list is stored in memory, to allow dynamic changing of the filters.
-- sort
