### ISSUE TITLE
Verison on Welcome Screen Not reflecting Release Number

### ISSUE THREAD

**Issue by basketballhead6** [datawhores/OF-Scraper#274]
Minor visual issue but with the latest version of the scraper, when you start the script it is showing the incorrect version number. I am using the latest release on pipx (3.5.4) and it still shows as version 3.3.10.

![image](https://github.com/datawhores/OF-Scraper/assets/121851530/9ade23ee-4b41-4656-8795-6285f81b997a)

**Comment by basketballhead6** [comment]
Alt + D doesn't do anything. Only have these options when in the modle selection screen.

![image](https://github.com/datawhores/OF-Scraper/assets/121851530/19eb71cf-5812-434a-9134-14d799c7400f)

**Comment by basketballhead6** [comment]
Interesting... when i run the --version command it says it's 3.3.10 despite pipx saying I am on version 3.5.4.

PS C:\Users\x> pipx upgrade ofscraper
⚠️  Overwriting file C:\Users\x\.local\bin\ofscraper.exe with C:\Users\x\.local\pipx\venvs\ofscraper\Scripts\ofscraper.exe
ofscraper is already at latest version 3.5.4 (location: C:\Users\x\.local\pipx\venvs\ofscraper)
PS C:\Users\x> ofscraper --log debug --after 2000 --version
3.3.10

**Comment by datawhores** [comment]
Try to uninstall and reinstall
Also try pip uninstall ofscraper


3.5.4 would have the alt D option, as that was added to provide more details that can't fit into the menu

Also the 
--promo args

**Comment by basketballhead6** [comment]
Running pip uninstall ofscraper fixed the issue. Somehow I had installed the pip version and doing that removed it.

Welcome screen reflects the latest version.
