### ISSUE TITLE
Logging stops working if time rolls over to the next day in daemon mode

### ISSUE THREAD

**Issue by dunngitter** [datawhores/OF-Scraper#275]
**Describe the bug**
If, while running in daemon mode, the datestamp rolls over to the next day (i.e. a new log file would be required), the new file is not created and logging output stops in the existing file.

**To Reproduce**
Run ofscraper in daemon mode when the datestamp is about to roll over to the following day

**Expected behavior**
New log file should be created for the new date, and logging should continue there

**Desktop:**

- OS: RockyLinux
- Browser: none
- Version: main
- docker

**Comment by dunngitter** [comment]
Actually, it looks like logging stops working after the first run in daemon mode. The last log entry I see is that the task will run again after the specified time. Not sure if the date issue is real, maybe that was just a coincidence

**Comment by datawhores** [comment]
It was both

The issue should  be fixed
although if run crossing between two days, then the next log will be created for the next day

new logs will also be created for each daemon run if appendlog is set to false
