### ISSUE TITLE
Post ID Issue with mediadir

### ISSUE THREAD

**Issue by datawhores** [datawhores/OF-Scraper#279]
**Describe the bug**
Post IDs may be incorrect for media dir

**To Reproduce**
Hint: enter the command and args would be a good idea
Use the post id place holder for mediadir

Example

**Expected behavior**

**Screenshots/Logs**

Hint: Please make sure that the log formatting is readable, use a paste site
like https://paste.passtheheadphones.me/

Hint2 : add " --log debug" this will create a log file with debug messages
Hint3 : add " --output debug" this will show debug messages in the terminal output, a log file is preferred. If your're doing this make your presentation readable

**Desktop (please complete the following information):**

- binary or python
- python version if installed via pip or pypi

**Smartphone (please complete the following information):**

**Additional context**

**Comment by toddhow** [comment]
Will you be pushing this fix soon?

**Comment by datawhores** [comment]
Yeah I can do it tomorrow

I need to double check that the change I made works

**Comment by toddhow** [comment]
I added the fix to my PR for post text.
