### ISSUE TITLE
Deleted model content checker

### ISSUE THREAD

**Issue by 6R1M4C3** [datawhores/OF-Scraper#280]
I'm creating reference page 
https://github.com/datawhores/OF-Scraper/wiki/Command-Reference 
which should help with creating the correct command

_Originally posted by @datawhores in https://github.com/datawhores/OF-Scraper/issues/65#issuecomment-1602822350_
            

if I use this to content check a deleted model that I have purchased from it throws a lot of errors doesn't even find anything, and the normal scrape method doesn't have them listed on the subpage or expired page either, is there a reason even with the model number it cant find the content

**Comment by datawhores** [comment]
If a model is completely deleted
and not just renamed or hidden 
It should not be possible to use the API to retrieve the content 

It might be possible to use the database to visualize information, but download urls are somewhat dynamic. So there would be be no way to retrieve new content

**Comment by datawhores** [comment]
this won't work with the way only fans is setup, the only way it will work possibly is with the filling the table with data from the scrape paid response
but this would only be in 3.9
