### ISSUE TITLE
no x-bc cookie anymore

### ISSUE THREAD

**Issue by tweety231323** [datawhores/OF-Scraper#282]
**Describe the bug**
ofscraper asks for a "x-bc" token, but OF doesn't provide one anymore.
Login not possible (auth error 401)

**Screenshots/Logs**
![2023-12-23 16_22_59-Haley (NO PPV) OnlyFans – Mozilla Firefox](https://github.com/datawhores/OF-Scraper/assets/98708681/41231831-a17d-4c29-b066-482ef54a6542)
![grafik](https://github.com/datawhores/OF-Scraper/assets/98708681/25415411-93a6-4a40-bd8c-b0f1fcf8a6b7)

**Desktop

- OS: Win11
- Browser firefox
- Version 121
- python
- python version if installed via pip or pypi: 3.12.1

**Comment by itsbighead** [comment]
look at it on google chrome. its 100% there on chrome because i just did it this morning

**Comment by toddhow** [comment]
This is not an issue with OF-Scraper, this is an issue with [OnlyFans-Cookie-Helper](https://github.com/M-rcus/OnlyFans-Cookie-Helper)
