### ISSUE TITLE
Unable to Authenticate

### ISSUE THREAD

**Issue by pripus** [datawhores/OF-Scraper#284]
I'm unable to log into OF with the program. Even when I updated the auth file with the OF cookie helper it and it give error: 

Trying to login attempt:1/10
 [scraper.check_auth:390]  Auth Failed                                                                   scraper.py:390

**To Reproduce**
1. Open OFScraper
2. Select Download content from a user
3. Error

**Expected behavior**
Expecting to select download content and get a list of subscriptions to scrape

**Desktop (please complete the following information):**

- Browser Mozilla Firefox
- Version Firefox 121.0
- python
- python 3.11

**Comment by cjb900** [comment]
Clear your browsers cookies and cache. then enter the auth information into the auth.json file directly **NOT IN THE SCRAPER** and **DO NOT** use the browser extension. Also make sure your auth file is formatted correctly as the example below.

```
{
    "auth": {
        "app-token": "33d57ade8c02dbc5a333db99ff9ae26a",
        "sess": "",
        "auth_id": "",
        "auth_uid_": "",
        "user_agent": "",
        "x-bc": ""
    }
}
```

**Comment by pripus** [comment]
Hi I just tried that, wiped my cookies and cache out of browser, re-entered the auth info formatted as shown from the network page fdirectly into the auth file and I still get the same error.

**Comment by spike63995** [comment]
> Clear your browsers cookies and cache. then enter the auth information into the auth.json file directly **NOT IN THE SCRAPER** and **DO NOT** use the browser extension. Also make sure your auth file is formatted correctly as the example below.
> 
> ```
> {
>     "auth": {
>         "app-token": "33d57ade8c02dbc5a333db99ff9ae26a",
>         "sess": "",
>         "auth_id": "",
>         "auth_uid_": "",
>         "user_agent": "",
>         "x-bc": ""
>     }
> }
> ```

Where do you get app token from?

> Clear your browsers cookies and cache. then enter the auth information into the auth.json file directly **NOT IN THE SCRAPER** and **DO NOT** use the browser extension. Also make sure your auth file is formatted correctly as the example below.
> 
> ```
> {
>     "auth": {
>         "app-token": "33d57ade8c02dbc5a333db99ff9ae26a",
>         "sess": "",
>         "auth_id": "",
>         "auth_uid_": "",
>         "user_agent": "",
>         "x-bc": ""
>     }
> }
> ```

Is that app token the one we're all supposed to use? If it is, mine isn't working either with this setup. If it isn't, could you please tell me how to find it? Thanks.

**Comment by mefistos** [comment]
I am having the same issue, same app-token, same troubleshooting done. Looks like maybe it got flagged?

**Comment by datawhores** [comment]
It should be the same for everyone but you can go through the manual steps to check

**Comment by HommeBenny** [comment]
It happened to me too. Turned out that `digitalcriminals` keys are not working. Updated the `config.json` to `"dynamic-mode-default": "deviint",` and it works like a charm.

**Comment by anthonyphua** [comment]
Tested and works.

Thank you very much for your help @HommeBenny .

Deeply appreciated.

> It happened to me too. Turned out that `digitalcriminals` keys are not working. Updated the `config.json` to `"dynamic-mode-default": "deviint",` and it works like a charm.
> 
> Same discussion here [UltimaHoarder/UltimaScraper#2054 (comment)](https://github.com/UltimaHoarder/UltimaScraper/issues/2054#issuecomment-1870109267)
> 
> @datawhores may be it needs an update?

**Comment by datawhores** [comment]
They both break at points

If digitialcriminals keys are broken now they should be fixed soon

**Comment by pripus** [comment]
Switching to deviint worked, thanks!
