### ISSUE TITLE
I want to know what this error means

### ISSUE THREAD

**Issue by lucacham** [datawhores/OF-Scraper#285]
**Describe the bug**

**To Reproduce**
When I enter the command ofscraper manual --url copied_link
The error in the picture below appears

**Expected behavior**
This is my first time using it and I hope someone can tell me how to do it

**Screenshots/Logs**
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/f6b2a328-7e9d-41a2-88e2-6178b17c0fa7)

![image](https://github.com/datawhores/OF-Scraper/assets/25399625/7ee2703e-405e-40a6-89e6-9d6193824df9)

**Desktop (please complete the following information):**

- OS: windows11 22H2
- Browser :chrome
- binary or python: python
- python version if installed via pip or pypi  Python 3.11.5

**Comment by cjb900** [comment]
Basically telling you that the command is wrong. If you are trying to download a post manually you have to use `ofscraper manual --url <post url>` where the actual post url is put where `<post url>` is in that command

**Comment by lucacham** [comment]
> Basically telling you that the command is wrong. If you are trying to download a post manually you have to use `ofscraper manual --url <post url>` where the actual post url is put where `<post url>` is in that command


Thanks, it worked. But the download progress stays at 0%, what causes this?
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/f7a906a2-04e4-4809-95f9-40b3265c609e)

After waiting for about 3 minutes, the download was completed, but there were no files. Only user_data.db and other files could be found in the .data/user/ folder.
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/9397027b-94d7-4a43-909d-02501d16ffda)

**Comment by datawhores** [comment]
It says failed run 
With --log debug

**Comment by lucacham** [comment]
> It says failed run With --log debug
When I execute `ofscraper --log debug`, it doesn't seem like there are any logs
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/1c4a4330-817d-469b-bfe5-3808970d38a7)

**Comment by lucacham** [comment]
> It says failed run With --log debug

When I run this command ofscraper --output debug, it appears the following message
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/a7b20d33-44ba-4d33-8ce1-8558a7c3bec9)

**Comment by datawhores** [comment]
Oh sorry I should be more clear

append --output debug to the manual command

**Comment by lucacham** [comment]
> Oh sorry I should be more clear
> 
> append --output debug to the manual command

I'm sorry to say that I'm new to this. Can you help me see what is causing the error?
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/a6c37329-4fb4-4323-9c59-5cef36766b3c)

**Comment by datawhores** [comment]
Please do
ofscraper manual --url <post url> --output debug

**Comment by lucacham** [comment]
> Please do
> 
> ```
> ofscraper manual --url <post url> --output debug
> ```


Thank you. Please help me.
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/f3643f6d-d7d6-41b6-a169-a41e5b9b0e0e)

**Comment by datawhores** [comment]
Did the output just stop there?

I need to see everything

**Comment by lucacham** [comment]
> Did the output just stop there?
> 
> I need to see everything

Sorry, here's the full log, I didn't realize that debugging takes a certain amount of time
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/0f0e9657-be89-41aa-ae8c-a59270b0a955)
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/c964ad76-c52e-44a9-9822-1379ed1103de)
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/938bc5fe-80e9-4255-8ce2-b197cd609262)
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/446c1328-83a5-4260-936e-039305e7639e)
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/82a1062d-494f-4a7e-9b8b-bc80ff094947)
![image](https://github.com/datawhores/OF-Scraper/assets/25399625/773e0cba-3ced-4d11-8d52-4bb547842396)

**Comment by datawhores** [comment]
Are you on a vpn 
your ip is getting blocked

**Comment by lucacham** [comment]
> Are you on a vpn your ip is getting blocked

Yes, I use VPN, how do I set the proxy in config.json?

**Comment by Puk0** [comment]
> After waiting for about 3 minutes, the download was completed, but there were no files. Only user_data.db and other files could be found in the .data/user/ folder.

Borra la carpeta cache y la carpeta de la modelo (.data/modelo_12345) y vuelve a poner el comando

**Comment by datawhores** [comment]
At the moment 
You'll have to find a unblocked connection or use a regular connection

**Comment by datawhores** [comment]
proxy can be added by change the const value here
        proxy = proxy or constants.getattr("PROXY")
        proxy_auth = proxy_auth or constants.getattr("PROXY_AUTH")
        
        PROXY and PROXY_AUTH which values depends on which downloader aio or httpx is used
        
        come to the discord for more information
