### ISSUE TITLE
Some onlyfans models not visible in OF-scraper

### ISSUE THREAD

**Issue by Fall0n** [datawhores/OF-Scraper#289]
Is it possible to do so that the list of what follows on OF will be updated So that missing models will be possible scrapt from?

did have full list the day before yesterday but now 15 plus models are missing from the list. If I go to the OF website, it is there and can see video and pictures and listen to audio messages

**Comment by datawhores** [comment]
What command are you using?

**Comment by Fall0n** [comment]
I used ofscraper in powershell as command and clicked on Download content from a user and selected from the list that comes up.

**Comment by datawhores** [comment]
Can you run of scraper --log debug --post all

Provide log file up to username selection

Also the username your looking for

You can provide this on the discord
