### ISSUE TITLE
Script cleans part/temp files regardless of config

### ISSUE THREAD

**Issue by dia-val** [datawhores/OF-Scraper#290]
**Describe the bug**
Since upgrading to a recent commit (hosted on Docker in Unraid) the script attempts to clean the part/temp files, even though its set to "false" in config. This results in a significantly longer execution time since it seems to search for these files before starting the processing of the downloads.

**To Reproduce**
Any start of the script triggers the cleanup, example:
ofscraper --posts ALL --mediatype Videos --after 2000 --sort Subscribed --desc --log debug --username MODELNAME

**Expected behavior**
Normal execution of the script

**Screenshots/Logs**
![image](https://github.com/datawhores/OF-Scraper/assets/142575839/df853d08-6e76-477e-9380-7f500a923096)
![image](https://github.com/datawhores/OF-Scraper/assets/142575839/85a354c3-c2df-4f7a-834e-c2dc83140316)

Hint: Please make sure that the log formatting is readable, use a paste site
like https://paste.passtheheadphones.me/

**Desktop (please complete the following information):**

- OS: Unraid / Docker
- Version: 3.6.3
-image: datawhores/of-scraper:latest

**Comment by datawhores** [comment]
partfileclean has been removed

It is now
auto_resume

Your config file should have nested values now

**Comment by dia-val** [comment]
Yes, thanks for the heads up, I saw that in the documentation. Adding "auto_resume": true to the config has no effect. It still tries to cleanup part files. Not sure what you mean by "nested values". My config currently looks like this (sensitive info omitted):

{
    "config": {
        "main_profile": "main_profile",
        "save_location": "/of_media",
        "file_size_limit": 0,
        "file_size_min": 0,
        "dir_format": "{model_username}/{mediatype}/",
        "file_format": "{filename}.{ext}",
        "textlength": 0,
        "space-replacer": " ",
        "date": "MM-DD-YYYY",
        "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}/Metadata",
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "threads": 5,
        "code-execution": false,
        "custom": null,
        "mp4decrypt": "/root/.config/ofscraper/bin/mp4decrypt",
        "ffmpeg": "/root/.config/ofscraper/bin/ffmpeg",
        "discord": "{DISCORDWEBHOOK}",
        "private-key": null,
        "client-id": null,
        "key-mode-default": "keydb",
        "keydb_api": "{APIKEY}",
        "dynamic-mode-default": "deviint",
        "partfileclean": false,
        "backend": "aio",
        "download-sems": 1,
        "maxfile-sem": 0,
        "downloadbars": true,
        "cache-mode": "json",
        "appendlog": true,
        "avatar": true,
        "auto_resume": true,
        "responsetype": {
            "timeline": "posts",
            "message": "messages",
            "archived": "archived",
            "paid": "paid",
            "stories": "stories",
            "highlights": "highlights",
            "profile": "profile",
            "pinned": "posts"
        }
    }
}

Is there something wrong with this config? Thanks a lot for your help, really appreciate it.

**Comment by datawhores** [comment]
I made some changes to force autoupdating to the new schema

It is in the latest commit and will be in 3.6.7

**Comment by dia-val** [comment]
You are right. After updating the Docker to 3.6.8 and auto upgrading config it's working normally again without the cleanup. Thank you for resolving this so quickly :)
