### ISSUE TITLE
Storage location after running exe

### ISSUE THREAD

**Issue by jamesle3199** [datawhores/OF-Scraper#293]
I'm having issues finding files after downloads. I've checked and changed my directory so far it's C:\Users\XXX\Data\ofscraper
When I go into the folders it show's nothing, there's no downloads in there but it shows as it's download over 1gb of data.

**Comment by datawhores** [comment]
Please provide a log

**Comment by jamesle3199** [comment]
[startvals.printStartValues:24]  config path: C:\Users\your_username\.config\ofscraper\config.json     startvals.py:24
 [startvals.printStartValues:25]  profile path: C:\Users\your_username\.config\ofscraper\main_profile   startvals.py:25
 [startvals.printStartValues:26]  log folder: C:\Users\your_username\.config\ofscraper\logging          startvals.py:26
 Welcome to OF-Scraper Version 0.0.0
Key Mode: cdrm2


CDM service cdrm2 timed out and seems to be down
This may cause a lot of failed downloads
Please confirm by checking the url:http://172.106.17.134:8080/wv
 Consider switching
https://of-scraper.gitbook.io/of-scraper/cdm-options


? What would you like to do? Edit Profile
? Select one of the following: View profiles


Current Profiles

[profiles.print_current_profile:146]  Using profile: main_profile                                      Profile: profiles.pymain_profile:
146
? Do you want to continue with script Yes
? What would you like to do? Edit auth.json file
 Hint: Select 'Enter Each Field Manually' to edit your current config
[
auth.edit_auth:83]  Auth Path C:\Users\your_username\.config\ofscraper\main_profile\auth.json              auth.pyFor an example of how your auth file should look see             :
83
https://of-scraper.gitbook.io/of-scraper/auth#example
If you still can't authenticate after editing from script consider manually edit the file at
C:\Users\Username\.config\ofscraper\main_profile\auth.json

Note: Browser Extractions only works with default browser profile


Warning: Numbering on OF site can be iffy
Example Including deactived accounts in expired
See: https://of-scraper.gitbook.io/of-scraper/faq#number-of-users-doesnt-match-account-number
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
? Which models do you want to scrape
: u221739466
 [scraper.scrape_context_manager:434]                                                                    scraper.py:434
==============================
 starting script
==============================

 [profiles.print_current_profile:146]  Using profile: main_profile                                      profiles.py:146
Status - UP
 [scraper.normal_post_process:196]  Progress 1/1 model                                                   scraper.py:196
 [scraper.normal_post_process:198]  Avatar :                                                             scraper.py:198
https://public.onlyfans.com/files/p/p5/p51/p51takygzzx9npliwwqej7qlox2fonu11705190385/221739466/avatar.j
pg
? Scrape entire paid page

[Warning: initial Scan can be slow]
[Caution: You should not need this unless your're looking to scrape paid content from a deleted/banned model] False
? Which area(s) would you like to scrape? ['Profile', 'Timeline', 'Pinned', 'Archived', 'Highlights', 'Stories', 'Messa
ges', 'Purchased', 'Labels']
 [profile.scrape_profile_helper:51]  Attempt 1/10 to get profile u221739466                               profile.py:51
 [profile.print_profile_info:121]  Name: SugarSugargal | Username: u221739466 | ID: 221739466 | Joined:  profile.py:121
2022-03-01T00:00:00+00:00
- 42 posts
 -- 60 photos
 -- 7 videos
 -- 0 audios
- 0 archived posts
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
 [timeline.get_timeline_media:188]                                                                      timeline.py:188
Setting initial timeline scan date for u221739466 to 1970.01.01
Hint: append ' --after 2000' to command to force scan of all timeline posts + download of new files
only
Hint: append ' --after 2000 --dupe' to command to force scan of all timeline posts +
download/re-download of all files


┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
 [archive.get_archived_media:196]                                                                        archive.py:196
Setting initial archived scan date for u221739466 to 1970.01.01
Hint: append ' --after 2000' to command to force scan of all timeline posts + download of new files only
Hint: append ' --after 2000 --dupe' to command to force scan of all timeline posts +
download/re-download of all files

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
 [messages.get_messages:137]                                                                            messages.py:137
Setting initial message scan date for u221739466 to 1970.01.01
Hint: append ' --after 2000' to command to force scan of all messages + download of new files only
Hint: append ' --after 2000 --dupe' to command to force scan of all messages + download/re-download of
all files


┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Attempt 1/10                                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
⠋ Getting highlight...
   Pages Progress: 0
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
 [helpers.dupefilter:19]  Removing duplicate media                                                        helpers.py:19
 [helpers.posts_type_filter:64]  filtering Media to images,audios,videos                                  helpers.py:64
Progress: (60 photos, 7 videos, 0 audios, 0 skipped, 0 failed || 67/67||398.93 MB/398.93 MB) ------------- 100% 0:00:30
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
 [common.setDirectoriesDate:459]  Setting Date for modified directories                                   common.py:459
 [downloadbatch.process_dicts:205]  u221739466 (398.93 MB) (67 downloads total [7 videos, 0        downloadbatch.py:205
audios, 60 photos], 0 skipped, 0 failed)
 [scraper.scrape_context_manager:443]                                                                    scraper.py:443
===========================

**Comment by jamesle3199** [comment]
That's what i'm getting when I run the exe but i'm unable to find the files for the user in the allocated location

**Comment by datawhores** [comment]
Can you use -- log output and provide a file from the config location

This is very hard too read

**Comment by jamesle3199** [comment]
Hey sorry, I tried it with a few others and it seems to be downloading most users just one in particular it's not downloading anything which the user is "taliah_nugg". I've also noticed that it's downloading files in "part" format, anyway to make decode these?

**Comment by datawhores** [comment]
Please provide a log file

**Comment by jamesle3199** [comment]
[ofscraper_main_profile_2024-01-19.log](https://github.com/datawhores/OF-Scraper/files/14053555/ofscraper_main_profile_2024-01-19.log)

**Comment by datawhores** [comment]
I would try to upgrade the issue is from the cdrm

ultametly
The best thing to do would be to try to setup the manual key

**Comment by datawhores** [comment]
no response
