### ISSUE TITLE
Bold Styling in Script Not Working

### ISSUE THREAD

**Issue by basketballhead6** [datawhores/OF-Scraper#295]
**Describe the bug**
In some sections of the script, the bold styling tag arere shown and is not making text bold. 
What I have found so far is below in the screenshots / logs section but there could be more.

**To Reproduce**
Run the scriptand scrape a model's profile.

**Expected behavior**
That text should be bold where those bold tags exist and are not shown back to the user.

**Screenshots/Logs**

[bold] starting script [/bold]

[bold]Model Name Here[/bold] (Download Size) (x downloads total [x videos, x audios, x photos]  x skipped, x failed)

[bold]Subscription Active:[/bold] True

[bold] Script Finished [/bold]
Run Time:  [bold]Time Here/bold]

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 3.6.6
- Python
- Pipx

**Additional context**
N/A

**Comment by datawhores** [comment]
This is a good reminder to remove them from discord

**Comment by datawhores** [comment]
The bold would only work on the console since it is processed through rich

**Comment by basketballhead6** [comment]
This is using powershell not discord though

**Comment by datawhores** [comment]
Okay I'll have to look into it

**Comment by basketballhead6** [comment]
@datawhores Don't know if you pushed a fix for this in the latest version but in 3.6.8 the bold text is working as intended.
