### ISSUE TITLE
cmd Args broken

### ISSUE THREAD

**Issue by CannotTouch** [datawhores/OF-Scraper#297]
Hi with the latest commit the cmd args --* doesn't works (the -* instead works instead are accepted).
but the -af 20231228 is accepted but not works correctly (the start date is always setted at the 1970)

I have previoslyused this:
ofscraper --sub-status active --after 20231228 --posts all -ul COLLECTION_NAME

today i have changed it in

ofscraper -ts -af 20231228 -o all -ul COLLECTION_NAME

it scrapes correctly but just the start date isn't right

**Comment by datawhores** [comment]
It has been change 

  -ts, --active-subscription
                        Filter accounts to those with non-expired status
  -es, --expired-subscription
                        Filter accounts to those with expired status

**Comment by datawhores** [comment]
Which post type does it not work for?

**Comment by datawhores** [comment]
after should work after  the next commit

The issue is that if you use after then the next time the script has to do a full scan to prevent missing posts 

Because of auto after

**Comment by CannotTouch** [comment]
i think that -ul (to scrape user list) is changed in -lb (to scape labels) too... but neither -ul or -lb or --label accept the name of the collection after it.
So probably i'm doing it wrong... i have read all the https://of-scraper.gitbook.io/of-scraper/command-reference but sorry i'm not able to understand which is the correct command to scrape lists.

ofscraper -ts -af 20231228 -o all -ul LIST_NAME
ofscraper -ts -af 20231228 -o all -lb LIST_NAME

**Comment by CannotTouch** [comment]
I have done several try with -ul --userlist --user-list but still nothing. I'm not able to find a way to use the collection from the site.

**Comment by datawhores** [comment]
Can you show a screen shot of how your entering the command

**Comment by CannotTouch** [comment]
> Can you show a screen shot of how your entering the command

@datawhores  I have wrote you the command, anyway with the latest commit the -lb is exchanged for a log plus B and go in error.

![lb](https://github.com/datawhores/OF-Scraper/assets/84774326/08cd4a22-069e-4311-89f3-58380f9ca3c3)

**Comment by datawhores** [comment]
Yeah this issue is very weird

Can you show what happens when you do the full names -- and not the short - ones

**Comment by CannotTouch** [comment]
"invalid choice"
![label](https://github.com/datawhores/OF-Scraper/assets/84774326/6cd16926-9417-4ce7-9da4-6492bcf65377)

**Comment by datawhores** [comment]
To be honest

I suspecting this to be an issue with argparse or powershell

**Comment by CannotTouch** [comment]
same error on cmd too

**Comment by datawhores** [comment]
Okay I pushed a change 

Can you try again and please show the screen with the error 

So I can see what it looks like
It should say something like Arguments

**Comment by CannotTouch** [comment]
Sorry for the dalay I have done several testing about and i found more than one problem.
the -ts didn't work, i have repaced id with: -ss active
if I pass the command:

`ofscraper -ss active -af 20231228 -o all --log debug`

all works correctly (the after too).

If I pass the command:

`ofscraper -ss active -af 20231228 -o all -l debug --label PIN`

no log is generted and i receive the follow:

```
C:\Windows\system32>ofscraper -ss active -af 20231228 -o all -l debug --label PIN
20231228
usage: OF-Scraper [-v] [-cg CONFIG] [-r PROFILE] [-l {OFF,STATS,LOW,NORMAL,DEBUG}] [-dc {OFF,STATS,LOW,NORMAL,DEBUG}]
                  [-p {PROMPT,STATS,LOW,NORMAL,DEBUG}] [-h] [-u USERNAME] [-eu EXCLUDED_USERNAME] [-d DAEMON] [-g] [-c] [-a {like,unlike}]
                  [-e] [-o POSTS] [-sk] [-ft FILTER] [-sp] [-dt {protected,normal}] [-at {paid,free}] [-rw {active,disabled}]
                  [-ss {active,expired}] [-be BEFORE] [-af AFTER] [-st {Name,Subscribed,Expiring,Price}] [-ds] [-uf] [-nc]
                  {post_check,msg_check,paid_check,story_check,manual} ...
OF-Scraper: error: argument command: invalid choice: 'PIN' (choose from 'post_check', 'msg_check', 'paid_check', 'story_check', 'manual')

C:\Windows\system32>
```

**Comment by datawhores** [comment]
Somehow you scraper isnt updating

**Comment by datawhores** [comment]
Your error should have looked like this

usage: OF-Scraper [-v] [-cg CONFIG] [-r PROFILE] [-l {OFF,STATS,LOW,NORMAL,DEBUG,TRACE}]
                  [-dc {OFF,STATS,LOW,NORMAL,DEBUG,TRACE}] [-p {PROMPT,STATS,LOW,NORMAL,DEBUG,TRACE}] [-h]
                  [-u USERNAME] [-eu EXCLUDED_USERNAME] [-d DAEMON] [-g] [-c] [-a {like,unlike}] [-e] [-o POSTS]
                  [-eo EXCLUDED_POSTS] [-ft FILTER] [-nf NEG_FILTER] [-sp] [-to | -no] [-lb LABEL] [-be BEFORE]
                  [-af AFTER] [-mt MEDIATYPE] [-sx SIZE_MAX] [-sm SIZE_MIN] [-mm | -ms] [-sk | -ok]
                  [-cp {paid,free}] [-rp {paid,free}] [-gp {paid,free}] [-pp {paid,free}] [-lo | -ls] [-fo | -fs]
                  [-po | -ps] [-ao | -as] [-ts | -es] [-ro | -rf] [-ul USER_LIST] [-bl BLACK_LIST]
                  [-ppn PROMO_PRICE_MIN] [-ppm PROMO_PRICE_MAX] [-gpn REGULAR_PRICE_MIN] [-gpm REGULAR_PRICE_MAX]
                  [-cpn CURRENT_PRICE_MIN] [-cpm CURRENT_PRICE_MAX] [-rpn RENEWAL_PRICE_MIN]
                  [-rpm RENEWAL_PRICE_MAX] [-lsb LAST_SEEN_BEFORE] [-lsa LAST_SEEN_AFTER] [-ea EXPIRED_AFTER]
                  [-eb EXPIRED_BEFORE] [-sa SUBSCRIBED_AFTER] [-sb SUBSCRIBED_BEFORE]
                  [-st {name,subscribed,expired,current-price,renewal-price,regular-price,promo-price,last-seen}]
                  [-ds] [-uf] [-nc] [-k {cdrm,cdrm2,manual,keydb}] [-dr {dc,deviint}] [-ar] [-db]
                  [-sd DOWNLOADSEMS] [-dp DOWNLOADTHREADS] [-md]
                  {post_check,msg_check,paid_check,story_check,manual} ...
OF-Scraper: error: argument command: invalid choice: 'dd' (choose from 'post_check', 'msg_check', 'paid_check', 'story_check', 'manual')

**Comment by datawhores** [comment]
I think you have to update your python your script seems very old

**Comment by CannotTouch** [comment]
I have updated python some day ago to the 3.12.1

i download your code, expand it and than I do:

`python -m pip install ofscraper --upgrade`

than i execute the command listed up. Don't is it the correct procedure to update?

**Comment by CannotTouch** [comment]
```
C:\Windows\system32>pip install ofscraper==3.6.8
ERROR: Ignored the following yanked versions: 1.82, 1.83
ERROR: Ignored the following versions that require a different python version: 1.4.1 Requires-Python >=3.9.0,<3.11.0; 1.4.2 Requires-Python >=3.9.0,<3.11.0; 2.7.1 Requires-Python >=3.7.0,<3.12; 2.7.10 Requires-Python >=3.7.0,<3.12; 2.7.11 Requires-Python >=3.7.0,<3.12; 2.7.12 Requires-Python >3.7.0,<3.12; 2.7.13 Requires-Python >=3.7.0,<3.12; 2.7.14 Requires-Python >=3.7.0,<3.12; 2.7.2 Requires-Python >=3.7.0,<3.12; 2.7.3 Requires-Python >=3.7.0,<3.12; 2.7.4 Requires-Python >=3.7.0,<3.12; 2.7.5 Requires-Python >=3.7.0,<3.12; 2.7.6 Requires-Python >=3.7.0,<3.12; 2.7.7 Requires-Python >=3.7.0,<3.12; 2.7.8 Requires-Python >=3.7.0,<3.12; 2.7.9 Requires-Python >=3.7.0,<3.12; 3.0 Requires-Python >3.7.0,<3.12; 3.0.1 Requires-Python >3.7.0,<3.12; 3.0.10 Requires-Python >3.7.0,<3.12; 3.0.11 Requires-Python >3.7.0,<3.12; 3.0.12 Requires-Python >3.7.0,<3.12; 3.0.2 Requires-Python >3.7.0,<3.12; 3.0.3 Requires-Python >3.7.0,<3.12; 3.0.4 Requires-Python >3.7.0,<3.12; 3.0.5 Requires-Python >3.7.0,<3.12; 3.0.6 Requires-Python >3.7.0,<3.12; 3.0.7 Requires-Python >3.7.0,<3.12; 3.0.8 Requires-Python >3.7.0,<3.12; 3.0.9 Requires-Python >3.7.0,<3.12; 3.1.1 Requires-Python >=3.8.0,<3.12; 3.1.2 Requires-Python >=3.10.0,<3.12; 3.2 Requires-Python >=3.10.0,<3.12; 3.2.1 Requires-Python >=3.10.0,<3.12; 3.2.2 Requires-Python >=3.10.0,<3.12; 3.2.3 Requires-Python >=3.10.0,<3.12; 3.2.4 Requires-Python >=3.10.0,<3.12; 3.2.5 Requires-Python >=3.10.11,<3.12; 3.3 Requires-Python >=3.10.11,<3.12; 3.3.1 Requires-Python >=3.10.11,<3.12; 3.3.10 Requires-Python >=3.10.11,<3.12; 3.3.12 Requires-Python >=3.10.11,<3.12; 3.3.2 Requires-Python >=3.10.11,<3.12; 3.3.3 Requires-Python >=3.10.11,<3.12; 3.3.3.1 Requires-Python >=3.10.11,<3.12; 3.3.3.2 Requires-Python >=3.10.11,<3.12; 3.3.4 Requires-Python >=3.10.11,<3.12; 3.3.5 Requires-Python >=3.10.11,<3.12; 3.3.6 Requires-Python >=3.10.11,<3.12; 3.3.7 Requires-Python >=3.10.11,<3.12; 3.3.8 Requires-Python >=3.10.11,<3.12; 3.4 Requires-Python >=3.10.11,<3.12; 3.4.1 Requires-Python >=3.10.11,<3.12; 3.4.2 Requires-Python >=3.10.11,<=3.12; 3.4.3 Requires-Python >=3.10.11,<=3.12; 3.4.4 Requires-Python >=3.10.11,<=3.12; 3.5 Requires-Python >=3.10.11,<=3.12; 3.5.1 Requires-Python >=3.10.11,<=3.12; 3.5.2 Requires-Python >=3.10.11,<=3.12; 3.5.3 Requires-Python >=3.10.11,<=3.12; 3.5.4 Requires-Python >=3.10.11,<=3.12; 3.6.0 Requires-Python >=3.10.11,<=3.12; 3.6.1 Requires-Python >=3.10.11,<=3.12; 3.6.2 Requires-Python >=3.10.11,<=3.12; 3.6.3 Requires-Python >=3.10.11,<=3.12; 3.6.4 Requires-Python >=3.10.11,<=3.12; 3.6.5 Requires-Python >=3.10.11,<=3.12; 3.6.6 Requires-Python >=3.10.11,<=3.12; 3.6.7 Requires-Python >=3.10.11,<=3.12; 3.6.8 Requires-Python >=3.10.11,<=3.12
ERROR: Could not find a version that satisfies the requirement ofscraper==3.6.8 (from versions: 0.0.0, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.51, 1.60, 1.61, 1.62, 1.63, 1.65, 1.70, 1.71, 1.72, 1.73, 1.74, 1.75, 1.80, 1.81, 1.86, 1.87, 1.95, 1.95.1, 1.95.2, 2.0, 2.0.1, 2.1, 2.4, 2.4.1, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5, 2.6, 2.6.1, 2.6.3, 2.6.4, 2.6.4.1)
ERROR: No matching distribution found for ofscraper==3.6.8

C:\Windows\system32>
```

**Comment by datawhores** [comment]
Can you try to uninstall and reinstall
3.6.8 doesn't even appear on the list of available versions

**Comment by CannotTouch** [comment]
> Can you try to uninstall and reinstall 3.6.8 doesn't even appear on the list of available versions

it's in the list, is just discarded for my python that is more advanced. i have downgrade python to the allowed version for the 3.6.8 
I have resetted the keydb and pass the following code:
`ofscraper -ts -af 20231228 -o all -l debug --label PIN`
sadly seems that it is retriving the list of all the models instead of just the label one... we will see it take time to take all the list (and it's the reason because I usually prefer use collection/label)

**Comment by datawhores** [comment]
Oh no you want the --userlist option

**Comment by datawhores** [comment]
It may be broken on the release 
there have been a few commits since then

**Comment by CannotTouch** [comment]
how is the right procedure to use the lastest commit? without --after it's quite insane :p

**Comment by datawhores** [comment]
You have to use action download in the latest commit
"--action download --posts all" is the simplistic

**Comment by CannotTouch** [comment]
Is there a way to bypass the full check if you use --after more than once? I prefer use it everytime and when it is skipped (to prevent losses) it's take ages on some creators with many many pages (over 300)

**Comment by datawhores** [comment]
You want to only use --after sometimes
And bypass the full check when not using after

I'll have to see a log

But now it should set the date to the latest date possible, which is the post with the earliest date.

Which should be pretty close to the latest post date

**Comment by datawhores** [comment]
Oh that is what your talking about 
try the dev release

https://pypi.org/project/ofscraper/3.7.0.dev0/

**Comment by CannotTouch** [comment]
on dev9 it works correctly, thanks.
