### ISSUE TITLE
Discord notifications no longer work

### ISSUE THREAD

**Issue by ChillyP** [datawhores/OF-Scraper#300]
Running the latest version, and discord notifications no longer seem to be working.

**Comment by datawhores** [comment]
Yeah they were broken 
Should be fix in repo or next version

**Comment by datawhores** [comment]
Can you specify what you mean by latest version?

What args are you using 
Also show your config

**Comment by ChillyP** [comment]
I’m using version 3.6.8 was working fine on 3.5.4.

I pass through arg —discord low

**Comment by datawhores** [comment]
Can you show a log with 
--log debug

**Comment by ChillyP** [comment]
Ok interestingly when I pass through argh —log debug the script creates the log file the script completes ok but the log file is empty?

**Comment by datawhores** [comment]
Can you run with --output debug 

and just show the first part with the system information and config

**Comment by ChillyP** [comment]
![Screenshot 2024-01-07 134818](https://github.com/datawhores/OF-Scraper/assets/74262804/e3ab4c2d-1208-4e6f-83cd-22e7a671c67b)

**Comment by datawhores** [comment]
Can you show the part with OS and number of processors

**Comment by ChillyP** [comment]
![Screenshot 2024-01-07 150508](https://github.com/datawhores/OF-Scraper/assets/74262804/cdbef65d-9542-4fac-a0b4-8fd099ac90cc)

**Comment by datawhores** [comment]
Something is wrong with your config file
did you install with pipx or pip

**Comment by ChillyP** [comment]
Ok I’ve fixed it, when I upgraded I must have used pip instead pipx, removed the pip install and it’s working again
