### ISSUE TITLE
CDM Service Error When attempting to scrape OF

### ISSUE THREAD

**Issue by jonatino** [datawhores/OF-Scraper#303]
**Describe the bug**
First time attempting to run this, downloaded the windows .exe from the release page. Scraper attempts to login but fails. auth.json has been populated with the Onlyfans cookie exporter firefox plugin.

Example

1. Run ".\ofscraper_windows_2aa90fd.exe --posts all"

**Expected behavior**
Should work according to documentation.

**Screenshots/Logs**
```
PS C:\Users\user\Downloads\ofscraper> .\ofscraper_windows_2aa90fd.exe --posts all
 [startvals.printStartValues:26]  config path: C:\Users\your_username\.config\ofscraper\config.json      startvals.py:26
 [startvals.printStartValues:27]  profile path: C:\Users\your_username\.config\ofscraper\main_profile    startvals.py:27
 [startvals.printStartValues:28]  log folder: C:\Users\your_username\.config\ofscraper\logging           startvals.py:28
 Welcome to OF-Scraper Version 0.0.0
 [paths.cleanup:62]  Cleaning up temp files                                                                  paths.py:62


Key Mode: cdrm2


CDM service cdrm2 has an issue RetryError[<Future at 0x20b7c82c410 state=finished raised KeyError>]
This may cause a lot of failed downloads
Please confirm by checking the url:http://172.106.17.134:8080/wv
 Consider switching
https://of-scraper.gitbook.io/of-scraper/cdm-options
```

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Firefox
- Version [2024.01.07_593583_main_2aa90fd_package](https://github.com/datawhores/OF-Scraper/releases/tag/2aa90fd)
- binary or python binary

**Comment by datawhores** [comment]
You have to follow the syntax in the auth example in the documentation

You can't paste the literally string from cookie helpwr

**Comment by jonatino** [comment]
> You have to follow the syntax in the auth example in the documentation
> 
> You can't paste the literally string from cookie helper

Apologies. My mistake. Closed issue
