### ISSUE TITLE
Windows Path / File name length ruins some file names, textlength in .config doesn't do anytrhing, the text from the OF post will still be too long

### ISSUE THREAD

**Issue by BeachNL** [datawhores/OF-Scraper#306]
**Describe the bug**
Windows Path / File name length ruins some file names.
 Changing "textlength" in .config doesn't do anytrhing, the text from the OF post will still be too long even when you reduce it to 2 for example. "truncation_default" on true in config doesn't change anything, the text keeps being the same.
 
**To Reproduce**
Download an user that has long text in the OF post, my fileformat is {date}_{text}_{filename}.{ext}

**Expected behavior**
Short the text from the OF post based on the textlength setting in the config when you change 0 to something else

**Screenshots/Logs**
Not relevant, this is an easy to figure out issue

**Desktop (please complete the following information):**
Windows 11, python 3.11, installed via pip ofscraper 3.6.8

**Comment by datawhores** [comment]
Are you on the commit version or a release

**Comment by BeachNL** [comment]
3.6.8, latest from the install guide

**Comment by datawhores** [comment]
You can switch
text_type_default to letter in the commit version or 3.7 when it comes out
