### ISSUE TITLE
Failed Downloads After Switching to Linux

### ISSUE THREAD

**Issue by JSylvia007** [datawhores/OF-Scraper#308]
**Describe the bug**
I was running this on a windows box without issues (and I noticed that Windows builds don't use CDRM settings), but I've converted my install over to a Linux box for ease of management, and now I'm getting failed downloads.

It looks like mp4decrypt was all that was needed on Windows, but I'm honestly unsure.  I'm also not exactly sure that encrypted videos are the issue, but hopefully this shakes something free.

**To Reproduce**
Here is the command I'm using:
`/opt/ofscraper/bin/ofscraper --config /opt/ofscraper/.config/ofscraper/config.json --username amaleiigh --after 2000 --output debug --posts all`

**Expected behavior**
I think the videos/images should just download without issue.

**Screenshots/Logs**
https://paste.passtheheadphones.me/?28a6065aa95fc2c1#2KHKNULYSwoNGq9YBJKKZVHdSeuV4P9p3u8ANJyqAcfb

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser: N/A - Command Line Only
- Version: 3.6.8
- binary or python: Python version installed through PIP
- python version if installed via pip or pypi: Python 3.10.12 (running in a VENV)

**Additional context**
Note I tried the manual method of decryption using the device_id and privkey, and I'm seeing the same things.

**Comment by BathingGorilla** [comment]
Same issue here on linux Ubuntu Server. Did you solve this?

**Comment by JSylvia007** [comment]
> Same issue here on linux Ubuntu Server. Did you solve this?

Still having the issue here.  Nobody has said anything.

**Comment by datawhores** [comment]
For some reason these downloads are being marked as 0 bytes

But It seems other downloads where working

Maybe update to 3.7.0 and try to see if downloads and try to monitor the .part files being created

**Comment by JSylvia007** [comment]
> For some reason these downloads are being marked as 0 bytes
> 
> But It seems other downloads where working
> 
> Maybe update to 3.7.0 and try to see if downloads and try to monitor the .part files being created

I tried 3.7, and the same thing happened.  It looks like the PART files are being created and they are not zero bytes in size.

**Comment by datawhores** [comment]
actually can you do

/opt/ofscraper/bin/ofscraper --config /opt/ofscraper/.config/ofscraper/config.json --username amaleiigh --after 2000 --output debug --posts all --log trace

Lets at least see if python thinks the files are growing

the log your looking for will be something like
Media:2113161072783 Post:8333387922 Download:  1/100000000

It should get closer to 100000000 in this case as the download is progressing

**Comment by JSylvia007** [comment]
> actually can you do
> 
> /opt/ofscraper/bin/ofscraper --config /opt/ofscraper/.config/ofscraper/config.json --username amaleiigh --after 2000 --output debug --posts all --log trace
> 
> Lets at least see if python thinks the files are growing
> 
> the log your looking for will be something like Media:2113161072783 Post:8333387922 Download: 1/100000000
> 
> It should get closer to 100000000 in this case as the download is progressing

https://paste.passtheheadphones.me/?6c2a56d55bc522f0#A85vnUPk1XeQDHmTxQqkYpbhqAaNtnJbpttRPhZUM423

**Comment by datawhores** [comment]
You log file should have more data then that
Are you looking at the file system and not the console

**Comment by JSylvia007** [comment]
> You log file should have more data then that Are you looking at the file system and not the console

Sorry about that.  This should be the one from the filesystem.

https://paste.passtheheadphones.me/?4e98207d42a4869a#EvbaNGStyb9ZQZL1SmsCo2SNGiMixUeA2cCNTGhoTKEV

**Comment by JSylvia007** [comment]
I KNOW THAT THE PROBLEM IS!!!!

OF-Scraper does NOT like to download to a mounted SMB share... My downloads directory is on an SMB Share that is mounted with systemd-mount, and something is making that cranky.  

I'm going to try an NFS mount to see if that works.

**Comment by BathingGorilla** [comment]
Mine is also mounted to an smb share. You might have solved it

**Comment by JSylvia007** [comment]
> Mine is also mounted to an smb share. You might have solved it

I wonder if there are some characters that it's trying to use in the filenames that SMB hates...  I'd really rather use SMB for... reasons... but at least for now it's back to working again.

**Comment by datawhores** [comment]
Okay I took another look at the log file 
It failing because of some issue with the downloader

Please check out the next commit
