### ISSUE TITLE
How to move to next item in prompt for "Edit advanced config.json settings"

### ISSUE THREAD

**Issue by spa123sea** [datawhores/OF-Scraper#309]
As the title says, I cannot figure out which key / key combination is needed to move to the next item in the "Edit advanced config.json settings" prompt sequence. I answer the first question "Number of Download processes/threads:", with enter or end, and instead of moving to the next item, it asks me if I want to continue with the script. Search all of the FAQs and guide and cannot find the controls for this. Please help

**Comment by datawhores** [comment]
What version are you on

**Comment by spa123sea** [comment]
version 3.6.8

**Comment by datawhores** [comment]
It was probably a bug
But it should work in 3.7
