### ISSUE TITLE
User list only shows Active == False -> Shows no accounts whose Active == True; Filtering crashes script

### ISSUE THREAD

**Issue by phaelon74** [datawhores/OF-Scraper#314]
**Describe the bug**
When I select Download content from a user and then Reset user list, the user list is **only** Subscriptions that are no longer active.  I scroll through the list and Active Subscriptions do not appear.  When I go to edit the criteria to Active == True, it acts like it loads it and then bombs out.  Relaunching the script, it defaults the filter and I again, only get Active == False subscriptions.

**To Reproduce**
Launch the script, tell it to download content, see all the Active == False and none of the true's

**Expected behavior**
The main list should show Active == True and Active == False until I set filtering criteria and then it should follow my guidance on filter criteria.

**Screenshots/Logs**

![ofscraper-FilterFail](https://github.com/datawhores/OF-Scraper/assets/33295008/9c517820-a647-4b89-a279-c61beb2570d7)
![ofscrapper-ActiveFalse](https://github.com/datawhores/OF-Scraper/assets/33295008/0388316e-3506-4d60-800c-56ff74886d6c)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
- Python
- OFScrapper 2.6.4.1 with Python 3.12.1

**Smartphone (please complete the following information):**
Not applicable

**Comment by cjb900** [comment]
That is a very old version if the scraper. You will need to uninstall the scraper, uninstall pip/pipx, then uninstall python. Then install python 3.11.6, then pip/pipx then install the scraper to get the latest version where you should not have this issue.

**Comment by phaelon74** [comment]
> That is a very old version if the scraper. You will need to uninstall the scraper, uninstall pip/pipx, then uninstall python. Then install python 3.11.6, then pip/pipx then install the scraper to get the latest version where you should not have this issue.

First off, thank you so much for your feedback.  I will do this.

Second, did I do something wrong?  I followed the official install guide, and yet I installed a very old version.  How do I not repeat this mistake?

**Comment by phaelon74** [comment]
Whoa, just did all of the above and installed it via PIP and now it's 3.6.8.  It might be that PIPX install is using a very old version?  I did it via PIPX before.

**Comment by cjb900** [comment]
This is not something you did wrong. Its something with python 3.12/3.12.1 that when installing via pip/pipx you somehow get old version of the scraper. Until what ever that issue is gets fixed i would just stay on python version 3.11.6

**Comment by phaelon74** [comment]
> This is not something you did wrong. Its something with python 3.12/3.12.1 that when installing via pip/pipx you somehow get old an version of the scraper. Until what ever that issue is gets fixed i would just stay on python version 3.11.6

Sounds good.  Would it make sense in the guide to then say not to use python 3.12.X as updates need to occur?

Also, I am good to go now, filter working like a dream, thanks so much for all you all are doing with this!!

**Comment by cjb900** [comment]
> > This is not something you did wrong. Its something with python 3.12/3.12.1 that when installing via pip/pipx you somehow get old an version of the scraper. Until what ever that issue is gets fixed i would just stay on python version 3.11.6
> 
> Sounds good. Would it make sense in the guide to then say not to use python 3.12.X as updates need to occur?
> 
> Also, I am good to go now, filter working like a dream, thanks so much for all you all are doing with this!!

I'm not the owner of this scrips so saying not to use python 3.12 is not my call to make lol
