### ISSUE TITLE
[3.7.0.dev5] No account found during scan

### ISSUE THREAD

**Issue by CannotTouch** [datawhores/OF-Scraper#318]
If I use
`ofscraper -a download -o all -ts`
it create correctly the list of names.

If I use
`ofscraper -a download -o all -ts -ul list_name`
or
`ofscraper -a download -o all -ts --user-list list_name`
it login correctly, check correctly the CDM on keydb, but than it give me the error
No account found during scan
and ask to rescan (rescan return the same error too).

I'm on Python 3.12.1 (I have try 3.13 like you wrote in the wiki, but on the requirements there is `3.7.0.dev5 Requires-Python >=3.11,<3.13` so it don't works with it)

**Comment by datawhores** [comment]
I just ran the command with out issue

With that send can you provide a log of the run
with the problem arguments

**Comment by CannotTouch** [comment]
maybe i'm using bad again than... after some changes.
-ul is still the command to us the collection list from the site? reading the [wiki ](https://of-scraper.gitbook.io/of-scraper/command-reference/account-filter-args#ul-user-list)seems it changed in something else

**Comment by datawhores** [comment]
as far as I can tell it is not finding the list
can you try the latest commit?

**Comment by CannotTouch** [comment]
with https://github.com/datawhores/OF-Scraper/commit/56d58ff496835ba1f2b7d40f3c09d7104d35d918
[ofscraper_main_profile_2024-02-06_07.41.18.log](https://github.com/datawhores/OF-Scraper/files/14175681/ofscraper_main_profile_2024-02-06_07.41.18.log)

**Comment by datawhores** [comment]
Where you able to see the list in the log
Or was that how they where originally

**Comment by datawhores** [comment]
I have an idea of what might be going on try the latest commit

**Comment by CannotTouch** [comment]
the last commit https://github.com/datawhores/OF-Scraper/commit/0604b656d972ffbe5097d65a9fc64f0d41b88d7e didn't work, but reading what you was doing on the commit i wrote the list_name all in lower case and it works correctly (on the site is all in uppercase and in the pass it worked correctly with the uppercase too.)
Anyway thanks a lot for the support.

**Comment by CannotTouch** [comment]
solved on https://github.com/datawhores/OF-Scraper/releases/tag/3.8.0dev3
