### ISSUE TITLE
Some Videos Not Downloading

### ISSUE THREAD

**Issue by CynicalPlatapus** [datawhores/OF-Scraper#321]
Howdy, as the title says i'm unable to get certain videos to download, i suspect they're DRM protected ones as it only includes some of more recent videos on the timeline and in messages, and no matter what i do the same specific downloads keep failing.

I've installed the latest stable version via pipx, the auth is set up correctly as i am able to download all photos and some older videos without issue, i've switch from CDRM2 to CDRM as was suggested by some people which didn't work.

I've checked all the previous similar issue reports and skimmed through the discord but i'm completely out of ideas now, hopefully someone might be able to help out, because my next step is to just use nvidia shadowplay to record the videos manually.

**Comment by cjb900** [comment]
Assuming you are using the latest version 3.6.8 of this scraper if CDRM is not working try using keydb. If you can't get that to work, Try using version 3.5.4 of the scraper and see if that works.

**Comment by CynicalPlatapus** [comment]
> Assuming you are using the latest version 3.6.8 of this scraper if CDRM is not working try using keydb. If you can't get that to work, Try using version 3.5.4 of the scraper and see if that works.

Cheers I'll give em a shot when i turn on my pc tomorrow, i stayed up way later than i should have to try and fix the problem

**Comment by CynicalPlatapus** [comment]
> Assuming you are using the latest version 3.6.8 of this scraper if CDRM is not working try using keydb. If you can't get that to work, Try using version 3.5.4 of the scraper and see if that works.

Finally got around to trying it out, switching to 3.5.4 did indeed solve the problem, thanks a lot for the suggestion, it is much appreciated.
