### ISSUE TITLE
Scrape a single chat media message

### ISSUE THREAD

**Issue by bollerdominik** [datawhores/OF-Scraper#323]
I want to scrape a specific post.

For posts I use 

`ofscraper manual -u https://onlyfans.com/{postId}/{username}`

For chats I use

`ofscraper manual -u https://onlyfans.com/my/chats/chat/{userId}/?firstId={postId}`

The chat link does work. How can I download a specific chat message?

**Comment by datawhores** [comment]
you can run with 
ofscraper --manual -u https://onlyfans.com/my/chats/chat/{userId}/?firstId={postId}

to try to see why it is failing
but that format should be okay

But make sure you are on the latest version 3.7.1 before that

**Comment by datawhores** [comment]
ofscraper --output debug manual --url https://onlyfans.com/my/chats/chat/{userId}/?firstId={postId}
