### ISSUE TITLE
Authentication in CMD doesn't work

### ISSUE THREAD

**Issue by henkiefie0** [datawhores/OF-Scraper#324]
I cant authenticate myself with the cmd, when I fill in my sess i have to confirm it but it doesnt seem to do anything. When I use the submit buttons like end+enter or esc nothing happens. The only thing that keeps working in the CMD is the enter(which is return). 

Do you guys have any idea how to fix this? I tried the cookie helper aswell but it does the same thing.

I'm running the latest version of OFSCRAPER with windows 10. I also added an image here below:

![image](https://github.com/datawhores/OF-Scraper/assets/123672721/c2954729-7881-4389-ab39-deed665b4189)

**Comment by cjb900** [comment]
If adding the auth information into the scraper is not working enter the information into the auth.json file directly. Also **DO NOT** use the cookie helper browser extension. I've seen many have issues using it for whatever reason.

**Comment by henkiefie0** [comment]
Oh fair enough, I also just saw that there isn't a auth.json file yet. Is there a command that does that for me or should I make one myself in notepad?

Thanks so far!

**Comment by cjb900** [comment]
the scraper should automatically create one for you. But if you are on the latest 3.7.1 I haven't tested that version personally so not sure if it creates one for you like the previous version did or if you have to somehow get information for the auth into the scraper for it to create it. I don't know if you create your own auth.json file it that would work though.

**Comment by henkiefie0** [comment]
I made my own file and it seems to work, thanks for your help.

Closed this issue
