### ISSUE TITLE
SQL Error in Labels Downloader: UNIQUE constraint failed

### ISSUE THREAD

**Issue by Adam759** [datawhores/OF-Scraper#326]
**Describe the bug**

I've been running scraper with the metadata update option and all posts to get all my folders up to date with the db's. However, on some accounts the labels scrape will succeed but when it tries to put them in the DB it fails, based on the debug logs. It will also terminate the download / metadata update loop, leading to a partially populated db with a lot of NULL fields, including Downloaded.

**To Reproduce**

ofscraper --log debug -mu --posts all --username userImScraping --action download

**Expected behavior**

It to run through all media successfully.

**Screenshots/Logs**

https://paste.passtheheadphones.me/?189aa025269ad731#FRLiqHT4CZtE5B4bSA5GVkCpm7mCrNMHLuGVPvuBrnPP

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome 121
- Python 3.11.4

**Comment by Adam759** [comment]
Just noticed this might be a duplicate of https://github.com/datawhores/OF-Scraper/issues/287. I'll leave this open in case it can help. The same error occurs on 3.7.1 and 3.8.0dev0.

**Comment by datawhores** [comment]
I made a dupelabel branch 
Unable to tell why this is happening currently

**Comment by datawhores** [comment]
This issue is referenced in 287 so I close it
so things can be consolidated
