### ISSUE TITLE
MPD videos ignore --quality flag

### ISSUE THREAD

**Issue by sixinchfootlong** [datawhores/OF-Scraper#330]
MPD videos always download the highest quality video (https://github.com/datawhores/OF-Scraper/blob/012529bfaca5dc0c6aad7baf432c65ec41388735/ofscraper/download/alt_download.py#L176-L186) regardless of the `--quality` flag setting.  For regular videos it goes with the _minimum_ allowed quality (https://github.com/datawhores/OF-Scraper/blob/012529bfaca5dc0c6aad7baf432c65ec41388735/ofscraper/classes/media.py#L47-L53) but MPD downloads do the opposite.

**Comment by datawhores** [comment]
Hmm
Good catch looks like I have some things to move around
