### ISSUE TITLE
#Trying to login attempt:1/10 

### ISSUE THREAD

**Issue by DVLM** [datawhores/OF-Scraper#331]
Version 3.7.1
Key Mode: manual

WARNING:Make sure you have all the correct settings for choosen cdm
https://of-scraper.gitbook.io/of-scraper/cdm-options

? Main Menu: What would you like to do? Perform Action(s)
? Action Menu: What action(s) would you like to take? Download content from a user
? Which area(s) would you like to download ['Profile', 'Timeline', 'Pinned', 'Archived', 'Highlights', 'Stories', 'Mess
ages', 'Purchased', 'Labels']
 [process.scrape_context_manager:47]                                                                       process.py:47
==============================
 starting script
==============================

 [tools.print_current_profile:38]  Using profile: main_profile                                               tools.py:38
Trying to login attempt:1/10
Trying to login attempt:2/10
Trying to login attempt:3/10
Status - DOWN
Trying to login attempt:1/10
Trying to login attempt:2/10
Trying to login attempt:3/10
 [paths.cleanup:46]  Cleaning up temp files

and my platform is Windows11,I am sure my auth.json is correct.

**Comment by Puk0** [comment]
Sal de tu cuenta de OF, vuelve a entrar para que genere otra cookies, y le cambias los datos en el programa o en el auth.json

**Comment by DVLM** [comment]
Yap, I did it, but it still failed.

**Comment by datawhores** [comment]
Try switching dynamic rules between digital and deviint

**Comment by datawhores** [comment]
Come to discord
