### ISSUE TITLE
make_headers() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by CannotTouch** [datawhores/OF-Scraper#335]
Version 3.8.0.dev6
Key Mode: keydb

CDM service keydb has an issue make_headers() takes 0 positional arguments but 1 was given
This may cause a lot of failed downloads
Please confirm by checking the url:https://keysdb.net/api
 Consider switching
https://of-scraper.gitbook.io/of-scraper/cdm-options
Trying to login attempt:1/10
Trying to login attempt:2/10
Trying to login attempt:3/10
 [checkers.check_auth:20]  Auth Failed

the auth file is correct (double checked it).

**Comment by CannotTouch** [comment]
i have try with python 3.11 and python 3.12.2 but i always receive the same make_headers() error... ant it don't login

**Comment by CannotTouch** [comment]
I have try to switch dynamic rules between digital and deviint like @datawhores suggest in the #331 but nothing to do.. i'm still stuck on this

**Comment by Adam759** [comment]
I seem to be having the same issue. Happens with any of the CDM services. I'm on Python 3.11.4. I did try to revert back to ofscraper 3.8.0dev0 (previously working) and it is happening on that version. Haven't yet tried on a clean install, just using pip uninstall and install to switch versions.
![image](https://github.com/datawhores/OF-Scraper/assets/15002550/ff888b31-28b5-464a-a025-2f418bade660)

**Comment by CannotTouch** [comment]
with the https://github.com/datawhores/OF-Scraper/releases/download/62144b5/ofscraper_windows_62144b5.exe all works correctly... with the python nope... mystery

**Comment by datawhores** [comment]
This should be fixed
