### ISSUE TITLE
Invalid option when selecting area to download

### ISSUE THREAD

**Issue by dvkrav** [datawhores/OF-Scraper#338]
**Describe the bug**
Updated paths for ffmpeg and mp4decrypt. When I select "download content for a user", it shows the list of area(s) to download. Selecting any gives "invalid input" error. Does not ask for model selection. 

**To Reproduce**
1. Run ofscraper
2. Programs ask for path of mp4decrpyt and ffmpeg binaries
3. Enter the local path of these binaries
4. Program prompt for action: select download content for user
5. Program prompts which area(S) to download: select any one
6. Invalid input error shown

**Expected behavior**
It should ask for model selection

**Screenshots/Logs**
<img width="590" alt="Screen Shot 2024-02-23 at 4 25 41 PM" src="https://github.com/datawhores/OF-Scraper/assets/94836027/e158b2df-9108-4e13-9e91-9e685f182165">

**Desktop (please complete the following information):**
- OS: MacOS BigSur v11.7.10
- Browser Firefox v123.0
- Version 3.7.1
- binary or python: installed through pipx v1.4.1
- python version if installed via pip or pypi: 3.12.2

**Additional context**
My config.json looks like 
{
    "main_profile": "main_profile",
    "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}",
    "discord": "",
    "file_options": {
        "save_location": "/Users/username/Data/ofscraper",
        "dir_format": "{model_username}/{responsetype}/{mediatype}/",
        "file_format": "{filename}.{ext}",
        "textlength": 0,
        "space-replacer": " ",
        "date": "MM-DD-YYYY",
        "text_type_default": "letter",
        "truncation_default": true
    },
    "download_options": {
        "file_size_limit": 0,
        "file_size_min": 0,
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "auto_resume": true,
        "system_free_min": 0
    },
    "binary_options": {
        "mp4decrypt": "",
        "ffmpeg": ""
    },
    "cdm_options": {
        "private-key": null,
        "client-id": null,
        "key-mode-default": "cdrm",
        "keydb_api": ""
    },
    "performance_options": {
        "download-sems": 6,
        "threads": 2
    },
    "advanced_options": {
        "code-execution": false,
        "dynamic-mode-default": "deviint",
        "backend": "aio",
        "downloadbars": false,
        "cache-mode": "sqlite",
        "appendlog": true,
        "custom_values": null,
        "sanitize_text": false,
        "temp_dir": null,
        "infinite_loop_action_mode": false,
        "disable_after_check": false,
        "default_user_list": "main",
        "default_black_list": ""
    },
    "responsetype": {
        "timeline": "Posts",
        "message": "Messages",
        "archived": "Archived",
        "paid": "Messages",
        "stories": "Stories",
        "highlights": "Stories",
        "profile": "Profile",
        "pinned": "Posts"
    },
    "mp4decrypt": "/Users/username/Downloads/Bento4-SDK-1-6-0-641.universal-apple-macosx/bin/mp4decrypt",
    "ffmpeg": "/Users/username/Downloads/ffmpeg"
}

**Comment by sixinchfootlong** [comment]
I think those are checkboxes.  Use _space_ to select which categories you want downloaded then press _enter_ to continue.

**Comment by dvkrav** [comment]
Thank you, for me _tab_ worked in Mac. can you tell me how to select a particular model to download ? it lists all in alphabetical order
