### ISSUE TITLE
API Rate Limit (HTTP 429)

### ISSUE THREAD

**Issue by sixinchfootlong** [datawhores/OF-Scraper#339]
It looks like OnlyFans has started imposing a rate-limit on API requests.  I'm not sure what the limit is set to but it starts to return HTTP 429 responses once reached.

The media listing logic doesn't have any rate limit options and always runs in parallel when multiple users are selected.  Adding an exponential retry delay (https://stackoverflow.com/a/35504626) or being able to limit the number of concurrent timeline scrapes would greatly help.  For reference, scraping a single user at a time usually doesn't trigger the rate limit.

**Comment by datawhores** [comment]
You can change the following const values
MAX_REQUEST_WORKERS # number of threads to run at same time
MAX_SEMAPHORE # semaphore limit
OF_MIN  # random retry time min sec
OF_MAX  # random retry time max sec

**Comment by datawhores** [comment]
no response and reports of 429 errors have been rare

**Comment by datawhores** [comment]
I'm reopening this

**Comment by datawhores** [comment]
I've been able to recreate the issue here on my machines

Which makes it a lot easier to test for

I think the closest thing I've been able to find

**Comment by datawhores** [comment]
There is a sleeper class that handles increasing the wait between requests
