### ISSUE TITLE
MP4Decrypt Error for Mac Users

### ISSUE THREAD

**Issue by Knowledger1** [datawhores/OF-Scraper#340]
For my mac users out there, have you all been able to successfully install MP4decrypt? When I attempt to run the ofscraper, I get the following error: There is an issue with the mp4decrypt path

 [check.mp4decryptpathcheck:22]  path to mp4decrypt is not valid     check.py:22
? mp4decrypt not found would you like to auto install? 
❯ Yes
  No

If I choose "yes" to auto-install the mp4decrypt, nothing is actually installed. I keep running the ofscraper again, only to receive the same message.

If I choose "no," and manually enter the filepath, I get the error: 

Certain content requires decryption to process please provide the full path to m
Linux version [mp4decrypt] and windows version [mp4decrypt.exe] are provided in 
Path to mp4decrypt is not valid filepath or does not exists

_________________

I'm trying to get the ofscraper to successfully run before my subscriptions expires lol, but at this point I'm not even sure if it can work with a mac or not.

**Comment by cjb900** [comment]
If mp4decrypt is not properly installing for what ever reason just download the zip file, extract it and then provide the path to it in the config.json file.

**Comment by Knowledger1** [comment]
> If mp4decrypt is not properly installing for what ever reason just download the zip file, extract it and then provide the path to it in the config.json file.

Thanks for the response. I gave that a try, but I'm still receiving the same error.

I first chose "edit config.json file."
When asked "which area would you like to change?" I chose "Binary Options"
Finally, when asked for the mp4decrypt path, I chose the mp4decrypt filepath from the "bin" folder which is located inside the Bento4 macosx folder.

**Comment by cjb900** [comment]
I said to add the file path to mp4decrypt in the config.json file not edit the config in the scrape.

**Comment by Knowledger1** [comment]
> I said to add the file path to mp4decrypt in the config.json file not edit the config in the scraper.

Ok, thanks

**Comment by Knowledger1** [comment]
Soooo my default shell has been changed to zsh, and now I'm getting the error: 

zsh: command not found: ofscraper

FML

**Comment by datawhores** [comment]
This is getting out of scope
maybe look into the zsh documentation
