### ISSUE TITLE
user_id fields in the messages table is always set to the model's ID regardless of who sent the message

### ISSUE THREAD

**Issue by departure18** [datawhores/OF-Scraper#341]
**Describe the bug**
The `user_id` field in the `messages` table is always set to the model's ID.

**To Reproduce**
When you scrape the messages between a user and a model, the `user_id` in the `messages` table in user_data.db is always set to the model's id, no matter who sent the message. 

**Expected behavior**
Messages in the `messages` table should have their `user_id` field set to whoever sent the message.  So any messages i've sent to a model should have my `user_id` and any sent to me by a model should have their `user_id`. This is the behaviour of Digital Criminal's script.

**Comment by datawhores** [comment]
fixed with 
https://github.com/datawhores/OF-Scraper/commit/de035d2591c795392cb79b33193f2aedf2a51b7e
