### ISSUE TITLE
Windows binary release doesn't open a menu past version 3.8.0

### ISSUE THREAD

**Issue by jupham** [datawhores/OF-Scraper#346]
**Describe the bug**
When trying to run the windows version past 3.8.0 there is no output and the program just exists. I've tried executing with '--output debug' and '--log debug' and neither produce any output. If running with '-v' it does print the current version as expected.

I have tried using the pipx install and downloading the release from Github.

**To Reproduce**
Run the Windows release

**Expected behavior**
Download and run the release on windows.

**Comment by cjb900** [comment]
That version of the scraper is buggy. I would use any of these version which have known to be stable and work with little to no issues. 3.5.4, 3.6.8 or 3.7.1

**Comment by jupham** [comment]
> That version of the scraper is buggy. I would use any of these version which have known to be stable and work with little to no issues. 3.5.4, 3.6.8 or 3.7.1

Any way to get pipx to install a specific version?

**Comment by jupham** [comment]
nevermind, the pip notation works (ie pipx install ofscraper==3.7.1)
