### ISSUE TITLE
Where is auth_uid_=????? I use 2FA authentification i am using 3.11.6 python and i am using your OF scrapper 3.7.1 I can not find the auth _uid

### ISSUE THREAD

**Issue by olstice** [datawhores/OF-Scraper#347]
I dont see the auth_uid_=

all i see is this                  _cfuvid=

is this it? otherwise i have no idea where the auth_uid_= is?

**Comment by datawhores** [comment]
maybe try copying the entire cookie value and searching for auth_uid
it might just be hard to see

**Comment by Puk0** [comment]
**auth_uid** y **auth_id** es tu numero de usuario
por ejemplo:
Mi perfil en OF > **only fans com/u12345678**
o
en firefox > inspeccionar > red > chats > encabezados > *hasta abajo en > **user-id**
