### ISSUE TITLE
Download stuck at 0% across any build, no matter what args

### ISSUE THREAD

**Issue by ujicos** [datawhores/OF-Scraper#349]
**Describe the bug**
No matter what, it gets stuck at 0%.
I have tried to run as admin, run as admin via cmd, run without admin, testing 3.9.0dev2, aswell as the previous stable release prior to 3.9.0dev2, changing paths multiple times, and using --after 2000 --dupe args (which actually retrieves the 479 posts, (some are paid for) but doesn't actually start downloading, it will get filesize, but will just be at 0%)

**To Reproduce**
Open cmd, run the command: "E:\test\ofscraper_windows_3.9.0dev2.exe" --after 2000 --dupe"
Change to your path, obviously

**Expected behavior**
I expect it to download, like it did before, but obviously nothing happens

**Screenshots/Logs**
[DEBUG BUILD - Stuck at 0/479 || 0B/8.77MB - 0% ~~6min](https://pastebin.com/raw/4mQnuGmV)

Hint2 : add " --log debug" this will create a log file with debug messages
Hint3 : add " --output debug" this will show debug messages in the terminal output, a log file is preferred. If your're doing this make your presentation readable

**Desktop (please complete the following information):**

- OS: Windows 11 213H2
- Browser: Opera GX with the cookie plugin
- Version: seemingly any, but tested with 3.9.0dev2, and the most recent (5 days as of writing) stable release
- Binary
- Python 3.10.10

**Additional context**
This only started happening today after i got new PC parts, though i don't see that being the issue.
Unsure if this might be a problem, but it tells me "Setting initial timeline (/archived) scan date for babivmpr to 1970.01.01"
To test the free posts to see if this is a user, and not API fault; the user is "babivmpr"

Last script it runs is at "download.py:32"

**Comment by cjb900** [comment]
Part of your issue is that your Python version is incompatible. As noted here, the newer version of this scraper requires 3.11 or higher https://of-scraper.gitbook.io/of-scraper/requirements I would also not recommend using any of the dev versions along with any of the 3.8.x version they are unstable and may not work. I would recommend using either 3.7.1, 3.6.8, or 3.5.4

**Comment by ujicos** [comment]
My apologies for the oversight. I'll try 3.7.1, and see if it works again.
It worked before, so maybe i had 3.7.1, idk, i just suffered a HDD death, so i am trying to regain the files this way lmao

**Comment by ujicos** [comment]
So 3.7.1 just crashes on launch.
3.6.8 invalidates my config, and doesnt give an option to reinstall ffmpeg and all that, 3.5.4 same thing.
I updated to py3.11 and i still cant download with newer versions :(

**Comment by ujicos** [comment]
After a lot of time (and uninstalling python 3.10)
running 3.6.8 finally made it work, i apologize. This issue can be deleted
