### ISSUE TITLE
Need Help. Models not downloading. Not sure what im doing wrong

### ISSUE THREAD

**Issue by thechef95** [datawhores/OF-Scraper#351]
i have everything configured how i like it and the program works. the issue is that it will download 1 models profile and then does this for the rest of the models

![20240320_035852](https://github.com/datawhores/OF-Scraper/assets/139814711/4281591b-6a28-4a17-8525-387e08ebe8e4)
 any help would be greatly appreciated

**Comment by datawhores** [comment]
Try 3.8.10

**Comment by datawhores** [comment]
closing because lack of op response
