### ISSUE TITLE
Decrypting issue

### ISSUE THREAD

**Issue by TheMissingPort** [datawhores/OF-Scraper#352]
My content isnt decrypting 

I've tried both cdrm and keydb. It was working fine before until I tried updating and it stopped  working. 

I've tried uninstalling ofscraper completely and reinstalling my previous versions. Can't get it to work

Any suggestions or ideas?

Thanks

**Comment by cjb900** [comment]
Well you didn't fill out the issue template and gave practically no information that's helpful. So what are we supposed to do just pull out a 🔮 and just guess everything here 🤔

**Comment by datawhores** [comment]
In the future reports without logs will be closed
please use the tickets channel in the discord if you desire to share logs privately

**Comment by datawhores** [comment]
lack of needed info
closing
