### ISSUE TITLE
Not downloading.

### ISSUE THREAD

**Issue by Chazy12** [datawhores/OF-Scraper#353]
When try to download someting with the .exe file, nothing happens.
Script found the list of models, selected one, download profile, gave me the list of files, but ends after 2 seconds and nothing downloaded.
Tryed various .exe version, but it's the same.
Tryed to execute as admiistrator too, but nothing.

![2024-03-25_142014](https://github.com/datawhores/OF-Scraper/assets/6653347/a03d486d-01ed-4c1a-9b97-f36c675fd28c)

**Comment by datawhores** [comment]
In the future reports without logs will be closed
please use the tickets channel in the discord if you desire to share logs privately

**Comment by Chazy12** [comment]
It's just my problem?

**Comment by Chazy12** [comment]
> In the future reports without logs will be closed please use the tickets channel in the discord if you desire to share logs privately

how to make logs?
tried again with last build, but same problem.

**Comment by Chazy12** [comment]
> In the future reports without logs will be closed please use the tickets channel in the discord if you desire to share logs privately

did the log.
here it is:
https://privatebin.io/?b250abbe8c553d19#CLKViePzTeL24E67nd63J4DBWGuqttAN6bqkVzZ8hPii

**Comment by datawhores** [comment]
I missed the log but I believe we were able to fix some common issues in 3.8.13
I will be closing for now
make a new issue reopen if the issue persists
