### ISSUE TITLE
Downloading of Purchased Videos fail with tempvideo and tempaudio

### ISSUE THREAD

**Issue by cs2xzst** [datawhores/OF-Scraper#354]
![2024-03-25_10-18-04](https://github.com/datawhores/OF-Scraper/assets/164919911/f6b733e6-eb2f-4399-8b9a-58aca09ca4f3)

Firefox. 

Says the CDM using KeysDB is fine. 

Using latest EXE.

**Comment by datawhores** [comment]
In the future reports without logs will be closed
please use the tickets channel in the discord if you desire to share logs privately

**Comment by datawhores** [comment]
closing because of lack of response
