### ISSUE TITLE
OF Scraper refusing to download new and existing files.

### ISSUE THREAD

**Issue by IrisEspinoza** [datawhores/OF-Scraper#356]
**PIP VERSION:  21.3.1
OF SCRAPER VERSION: 3.8.1**

**LOG**
[ofscraper_main_profile_2024-03-27_20.03.58.log](https://github.com/datawhores/OF-Scraper/files/14782361/ofscraper_main_profile_2024-03-27_20.03.58.log)

**ISSUE**
After coming back from some time, I fired up the program and reset my auth. credentials and everything runs as normal. Going through the menu and nothing seems out of the ordinary, though as the download process begins, the script seems to skip everything, including the scan. Up until this point, I have reinstalled a newer version of OFSCRAPER and updated the PIP Version as well. I even went as far as reinstalling a newer version of Python. Though still no luck. I have tried to remove the cache files, delete and rename folders, etc. Though no changes. I'm pretty stumped. Any help?

**ADDITIONAL INFO**
Running on Windows 10

**Comment by datawhores** [comment]
out of curiosity is the content on the desired profile unlocked

**Comment by El-tra** [comment]
Latest stable is 3.8.12. That might or might not fix it.

Have you tried --dupe --no-cache ?

**Comment by datawhores** [comment]
3.8.13 should fix it

**Comment by datawhores** [comment]
No response
