### ISSUE TITLE
No 'init' file 

### ISSUE THREAD

**Issue by Emmo41** [datawhores/OF-Scraper#357]
**Describe the bug**
As there is no post about this, the 'init' section / file is no longer there since two months now. Is this just a problem for me or why does no one bother? I used Firefox and Chrome and with both browsers I cannot see the 'init' file anymore. I used the scraper for over a year now.

![Unbenannt](https://github.com/datawhores/OF-Scraper/assets/148868821/d8609659-38ae-4281-8770-17581967220f)

**Comment by vintagelock** [comment]
Just use something else.  It is the cookie information that you are after.  Here I used "me"
<img width="1170" alt="Screenshot_832" src="https://github.com/datawhores/OF-Scraper/assets/63687292/a4200ae4-6abb-401d-97b2-d8b00034c841">


Anyone feel free to correct me if I am wrong ;)

**Comment by datawhores** [comment]
yeah another onlyfans url should work
