### ISSUE TITLE
jpeg instead of jpg

### ISSUE THREAD

**Issue by El-tra** [datawhores/OF-Scraper#368]
The last two or three stable releases store images as jpeg instead of jpg as it used to be before.
Just a heads up, not a real issue.

**Comment by datawhores** [comment]
The extensions are not changed and are kept in the original format

If your in a situation where you really need them all to be the same do an overwrite for photos

https://of-scraper.gitbook.io/of-scraper/getting-started/config-options/advanced-config-options/mediatype-overwrites

**Comment by Puk0** [comment]
En el config.json :

En "file_format" > **.{custom.get(ext,ext)}**

**"code-execution": true,**

**"custom_values": {"jpeg": "jpg"},**

**Comment by El-tra** [comment]
Thanks!

**Comment by El-tra** [comment]
@Puk0 Works like a charm, as soon as I found out, where to place it all. Thanks again.

**Comment by El-tra** [comment]
Did some more research. The log shows the "original" filenames as OF seems to deliver them. It's some quite cryptic path with the filename being a combination of the dimensions and and an ID. At this point the extension is still "jpg". The renaming to whatever is set in "file_format" happens later on but is not logged (at least not at the level that's used by default). The change to "jpeg" must happen here. Re-downloading the files for one subscription with --force-all --no-cache gave me a bunch of duplicate files. Previously downloaded files with "jpg" and the new ones with "jpeg".

**Comment by Puk0** [comment]
> Re-downloading the files for one subscription with --force-all --no-cache

Solo tenias que renombrar con algún programa como "Renamer" y cambiar .jpeg por .jpg

Añadir > remplazar > jpeg jpg, y quitar >ignorar extensión,

**Comment by El-tra** [comment]
Sure, that would work. And it's easily resolvable with your custom.get-hint. But it's still strange.

**Comment by DonaldTPP** [comment]
> Sure, that would work. And it's easily resolvable with your custom.get-hint. But it's still strange.

What did you config look like after the changes in those particular areas?
