### ISSUE TITLE
Change default location of config

### ISSUE THREAD

**Issue by Mareckyyy** [datawhores/OF-Scraper#372]
As above, how can i change location of ./config/ofscraper to be current working directory of exe file? Main reason is to have OF-Scraper on external HDD.

**Comment by Puk0** [comment]
en lugar de darle click al exe, tienes que hacer lo siguiente, En windows con versión .exe o zip, usando la opción **-cg**

1. abres el **simbolo del sistema**

2. luego pones la **ruta donde está el .exe**
. por ejemplo 
cd /d D:\Programas\OFR\OF-Scraper

3. luego el **nombre del .exe + la ruta de la carpeta** donde se guardara el perfil
por ejemplo
ofscraper_windows_3.8.17.exe -cg D:\Programas\OFR\OF-Scraper\Config_3_8_17

4. O todo junto por ejemplo
cd /d D:\Programas\OFR\OF-Scraper & ofscraper_windows_3.8.17.exe cg D:\Programas\OFR\OF-Scraper\Config_3_8_17

5.Y asi cada vez que lo uses, sino te creara el perfil en .config/ofscraper

**Comment by datawhores** [comment]
This is in the docs
