### ISSUE TITLE
Download Activity Progress not Clearing when Download is Completed

### ISSUE THREAD

**Issue by basketballhead6** [datawhores/OF-Scraper#385]
## Describe the bug

The section which shows download activity in the script is not clearing competed download activity from the view. It gets stuck and stays there and nothing overrides it.

They persists when moving to a new model as well.

## To Reproduce

Run the script and download content. (I suggest running on a model not scraped before to ensure that there is enough items to fill the download screen)

## Expected behavior

Completed downloads are removed from the screen.

## Screenshots/Logs

![Screenshot 2024-05-27 135526](https://github.com/datawhores/OF-Scraper/assets/121851530/b12bb51c-9d92-42bf-94a4-4269bf98f0ae)

## Config

https://pastebin.com/bb2TX5Ae

## System Info

- OS: Windows 11
- Version: 3.10dev4
- Pipx installation

**Comment by datawhores** [comment]
Hopefully this is fix
in the latest commits

**Comment by basketballhead6** [comment]
This is fixed in later releases
