### ISSUE TITLE
Metadata options seem to be broken in 3.10.dev5

### ISSUE THREAD

**Issue by Adam759** [datawhores/OF-Scraper#386]
## Describe the bug

I've been testing out 3.10.dev5 to check out the new activity progress bars (awesome!) and can't seem to get the metadata options to work. I am using 3.9.8 regularly, just thought I'd point this out with dev5 if it is not yet known, and I'd love to start using it as being able to see the activity is much more useful, especially with problem models. 

## To Reproduce

I am running the latest docker image, 3.10.dev5, on my Ubuntu server. I am running the following command:

`ofscraper metadata --metadata update --posts all -p debug -u <user>`

## Expected behavior

Update the metadata based on folder contents and available posts to download. 

## Screenshots/Logs

https://pastebin.com/9SZ0efzu

<img width="815" alt="putty_QmPMOgRnjY" src="https://github.com/datawhores/OF-Scraper/assets/15002550/9f953b1c-69de-4783-a757-6a9f0ef96fb0">

## Config

https://pastebin.com/kXbqMQ3h

## System Info

- OS: Ubuntu Server 20.04
- Docker 3.10.dev5

**Comment by datawhores** [comment]
fixed
please update via the 3.10b branch

**Comment by Adam759** [comment]
forgot to close this, thanks!
