### ISSUE TITLE
https://cdrm-project.com/wv   404

### ISSUE THREAD

**Issue by cilium-cell** [datawhores/OF-Scraper#387]
It looks like https://cdrm-project.com/wv is returning a 404. I poked around the site, and I do not see any reference to that endpoint, while The API documentation currently identifies https://cdrm-project.com/ as the API url. Is it possible that the CDRM API has changed?

**Comment by cilium-cell** [comment]
According to their discord they did release a new API sometime around yesterday. The old API was moved to [https:/old.cdrm-project.com/wv](url) and works like before.

**Comment by S2imong** [comment]
What do I need to do to continue the program to start downloading?

**Comment by datawhores** [comment]
You can change the const value 
CDRM in older version

I will also change the default value in the the next dev release

**Comment by datawhores** [comment]
```
 "custom_values": {
            "CDRM": "https://old.cdrm-project.com/wv",
        },
```

**Comment by S2imong** [comment]
My computer's config file doesn't have this setting, what's going on?

**Comment by datawhores** [comment]
In regards to my previous post the value should be changed in the config file
https://of-scraper.gitbook.io/of-scraper/getting-started/config-options/advanced-config-options/changing-const#where-are-they
