### ISSUE TITLE
Downloads broken on recent versions

### ISSUE THREAD

**Issue by Jules-WinnfieldX** [datawhores/OF-Scraper#388]
## Describe the bug

Downloads appear broken and hang on 3.9.8 -> latest dev release (dev6 at this time). A single download completes, and the rest of the threads hang. 

## To Reproduce

Manual key mode
Start command: `ofscraper --active-subscription --username ALL --posts all --action download --no-cache --output debug`

## Expected behavior

Downloads not to hang. 

## Screenshots/Logs

https://privatebin.io/?4d0e08dd2d6f4179#9YtgNLDw4fQ6HQjrggx4E9iku278mzxvTAHofsvjNs6R

## Config

https://privatebin.io/?9c1fd4c97a5465e0#8mXDDaQYYzkwMaKHWGBMaSBRQV853Lheyj2gD3pH4s7A

## System Info

- OS: Win 11
- Browser: Firefox
- Python: 3.11.4
- 3.10Dev6

**Comment by datawhores** [comment]
Can you try the lastest dev release

**Comment by datawhores** [comment]
Can you turn off auto_resume and see if that helps?

**Comment by Jules-WinnfieldX** [comment]
Auto resume now off, uninstalled 3.11.4, removed any stagnant site packages, installed 3.11.8, fresh install of 3.10dev7, same thing. 

Except no downloads happen. Gets stuck on first model, 0B/7.88 MB

**Comment by Jules-WinnfieldX** [comment]
https://privatebin.io/?c2c0a2b2b2fe202d#4VBq6nbtChQBhnVJaeNE4Nz7sSBfmgywxfJ7xoNrpFEF

Here's a new log incase it helps

**Comment by datawhores** [comment]
Does it work if you change threads to 0

**Comment by Jules-WinnfieldX** [comment]
That does indeed solve it

**Comment by datawhores** [comment]
for the log file did you just pipe the output to a file or similar

**Comment by Jules-WinnfieldX** [comment]
Those were taken from .config/ofscraper/logging log files. Instead of attaching the entire files, I just attached the latest runs.

**Comment by Jules-WinnfieldX** [comment]
If you'd like an entire file, let me know. I can reset things to non-functioning and give a whole file.

**Comment by datawhores** [comment]
I added some more logs to 
3.10.dev8

**Comment by Jules-WinnfieldX** [comment]
Here is a full log, from start to hang. https://privatebin.io/?cda029af5947b3b9#GdNA27x58LW7jfMQzcvtSg8Z3277vWTFwF3YgH9jdKSf

To note, with visible download bars, around 8/10 appear, however all stay at 0. I'll leave the program open for around 30 minutes and see if any new lines are added.

**Comment by Jules-WinnfieldX** [comment]
That is indeed the last entry after around an hour

**Comment by datawhores** [comment]
Okay can you try the dev9 release

**Comment by Jules-WinnfieldX** [comment]
https://privatebin.io/?dd3c9410c6df4c22#4QNRsd6bbUmMKTsfwCRZ2j7pTdQtvS78aw5xQ5YHq1Lh

Got to two partial downloads, then another freeze.

**Comment by Jules-WinnfieldX** [comment]
Might be worth noting, none of the partial downloads are .mp4 or audio files. 

They are two image files. 

1284x1974_db43b3752525b6e2a1ad5d03d86cafa5_2469612556

2795x4032_45abdaf61b8417fd93c079946c09b077_2264638239

**Comment by CannotTouch** [comment]
with dev9 it stuck on downloading without error, last log line is
2024-05-29 09:17:34:[main_downloadbatch.send_req_inner:225]  Media:3117110786 Post:896377366  writing media to disk

**Comment by datawhores** [comment]
can you try this commit
https://github.com/datawhores/OF-Scraper/commit/6cf8b78bcd8f7a211e443ae1b3103ba8e20bf4f2

otherwise I'm making a new release
also this time try normal downloads only

"--normal-only"

this will skip widivine content

**Comment by datawhores** [comment]
I added a new const value 
SHOW_DL_CHUNKS

https://of-scraper.gitbook.io/of-scraper/getting-started/config-options/advanced-config-options/changing-const#where-are-they

**Comment by datawhores** [comment]
I increased the chunk size
It seems to be working better on my test system

**Comment by Jules-WinnfieldX** [comment]
I'll pull a recent commit and try it

**Comment by Jules-WinnfieldX** [comment]
Seems to be working using the python files on https://github.com/datawhores/OF-Scraper/commit/bc494469a0cdac1d6ab4d2faf328a162dfc4f658

**Comment by CannotTouch** [comment]
> Seems to be working using the python files on [bc49446](https://github.com/datawhores/OF-Scraper/commit/bc494469a0cdac1d6ab4d2faf328a162dfc4f658)

With this same commit, for me it still stucks :(
