### ISSUE TITLE
Downloads failed and skipped

### ISSUE THREAD

**Issue by Jar4ek** [datawhores/OF-Scraper#391]
Hello,
I have a question whether you have encountered problems with downloading from OF. While downloading, I get a failed download error, which means that new files are not downloaded but is skipped. Has anyone had a similar problem?

**Comment by cjb900** [comment]
This can happen for any number of reasons. Your CDM is not working or set correctly, you are missing the file paths for mp4decrypt and ffmpeg, you are using a VPN etc... So just saying that is like saying my car sometimes stalls when I drive has anyone experience that. Which is not very helpful.

**Comment by S2imong** [comment]
CDM return an error
This may cause a lot of failed downloads
 consider switching
https://of-scraper.gitbook.io/of-scraper/cdm-options

**Comment by cjb900** [comment]
If you are using `cdrm` as your `key-mode-default` option in your config. the CDM-Project that manages that recently change their API for using `cdrm` You will need to add `"CDRM":"https://old.cdrm-project.com/wv"` to your config under `"custom_values"`. So it should look like ``"custom_values":{
            "CDRM":"https://old.cdrm-project.com/wv"
   }``
