### ISSUE TITLE
Stuck at "Auth Menu: Select how to retrive auth information"

### ISSUE THREAD

**Issue by uneedjesus8** [datawhores/OF-Scraper#400]
Brand new install of ofscraper, but constantly stuck at entering Auth details. Tried the firefox extension and manually input. But after input, it shows the same menu again, with every input filled-in already.

log:
[ofscraper_main_profile_2024-06-06.log](https://github.com/user-attachments/files/15595332/ofscraper_main_profile_2024-06-06.log)

config:
[config.json](https://github.com/user-attachments/files/15595340/config.json)

1. Install ofscraper with pipx
2. run ofscraper
3. try to start scraping
4. input auth manually

Expected behavior:

Auth menu shows up again, with all the input filled-in with previous inputs.

System Info

- OS: Windows
- Browser: Chrome
- Version: v3.10
- Python v3.12.3

**Comment by DynamoPrime** [comment]
I'm seeing this same behaviour as well with a previously working install. 

1. I've updated my auth.json, both using the M-rcus' OnlyFans-Cookie-Helper and manually
2. I'm running a download action: 
    ```
    ofscraper \
        --action download \
        --posts all \
        --sort subscribed --desc \
        --username ALL
    ```
3. My logs almost immediately show a `Client error '400 Bad Request' for url 'https://onlyfans.com/api2/v2/users/me'`.

I've also noticed that if I refresh of.com immediately after running the scraper, that I've been logged out.

**Comment by marcintosch** [comment]
I can second that issue with current 3.10 on Python 3.11 on Mac, stuck in a loophole and repeated auto-sign-offs

**Comment by grummmmm** [comment]
Same behaviour on ofscraper 3.10, python 3.12.2.
I do not encounter the logout behaviour that @DynamoPrime has noticed, though.
Here is a log excerpt:
[error.txt](https://github.com/user-attachments/files/15595808/error.txt)

**Comment by datawhores** [comment]
update to new commit
https://github.com/datawhores/OF-Scraper/commit/51c48a2b001f9d17c3e2fa20b91b3e9a0c2c12db

or 

https://of-scraper.gitbook.io/of-scraper/getting-started/config-options/advanced-config-options/changing-const#where-are-they

the value to change is
{"SNEAKY":"https://raw.githubusercontent.com/Growik/onlyfans-dynamic-rules/main/rules.json"}

**Comment by datawhores** [comment]
https://gist.github.com/datawhores/8e8be131fb1b190b50c5324ab2ca5f89

**Comment by DynamoPrime** [comment]
That works great, thanks!

1. Updated to 3.10.2
1. Updated config.json to use `"dynamic-mode-default": "growik"`
1. Success!
