### ISSUE TITLE
Connection attempt exits OF session, no auth

### ISSUE THREAD

**Issue by jp1151419** [datawhores/OF-Scraper#401]
I'm confident the issue isn't limited to this scraper but does anyone else have issues with getting the scraper to login? I've been doing this for years by now, both with the cookie-helper extension and through the Network tools. I just can't get the authentication to work right now and if I keep my browser open it gets logged out as soon as I try with the scraper.

Anyone else having that issue at the moment?

**Comment by cjb900** [comment]
https://gist.github.com/datawhores/8e8be131fb1b190b50c5324ab2ca5f89
