### ISSUE TITLE
Auth issues beginning June 5

### ISSUE THREAD

**Issue by lordoffools** [datawhores/OF-Scraper#403]
Anyone else experiencing auth issues starting an hour or two ago? Everything's been working just fine up until now.

Re-authed and it still doesn't work. In fact, when trying to pull a list of creators, it yields an auth failure and a forced logout in the live browser by OF.

Tested with multiple browsers. Running latest 3.10 version.

## System Info

- OS: MacOS
- Browser: Chrome, Safari, Opera, Firefox
- Version: 3.10
- binary or python: binary
- python version: 3.11

**Comment by Nostang3** [comment]
FYI, Option 1 has isn't fully correct or at least didn't work for me till I made a change to the value. Without the quotes around the URL the script kept throwing json errors. 

```{"SNEAKY": "https://raw.githubusercontent.com/Growik/onlyfans-dynamic-rules/main/rules.json"}```
