### ISSUE TITLE
Init not showing in console

### ISSUE THREAD

**Issue by SpoogLord** [datawhores/OF-Scraper#404]
May just be me doing something wrong but when trying to get auth info init doesnt show in the network/xhr tab, I even tried firefox and its not there either. Possible onlyfans networking update or am i just dumb?

**Comment by datawhores** [comment]
if you filter the network requests with onlyfans and you should get a good hit
you should get a hit with the required information

**Comment by datawhores** [comment]
Example with github

![image](https://github.com/datawhores/OF-Scraper/assets/67020411/f90f8444-1bf1-489e-9098-49234dfdb15d)

Please don't take this example literally 
of course on onlyfans you would search for onlyfans, and look for  request url with onlyfans, typically api.onlyfans
but the idea remains the same between the two examples

**Comment by datawhores** [comment]
closing
