### ISSUE TITLE
Account Logged Out and Auth Failed Right After I Finish Choosing the Option

### ISSUE THREAD

**Issue by 666diabolus** [datawhores/OF-Scraper#405]
It was working fine until last night, when I got to the step to not making Slow Scan, I choose False, Enter and it didn't load the subcriptions, instead it said Auth Failed and kicked me out of the account.
Tried to upgrade to 3.10 but it still happens.
Is it possible that because I use it too much or because my manual key is dead ? Been on the account for 3 days straight with a lot of traffic.

Edit: some sort of 400 bad request error.

**Comment by El-tra** [comment]
Same here. Checked with 3.8 and 3.10.1

**Comment by datawhores** [comment]
This description is not very helpful
Provide a log

**Comment by Rustybrickc** [comment]
If you are using the Mozilla cookie helper, pay attention to the code. For instance, if I have two-factor authentication turned off, but the helper provides a code where "support_2fa": true. After changing it to "support_2fa": false -  the scraper runs, but it doesn't download anything.

**Comment by 666diabolus** [comment]
> This description is not very helpful Provide a log

This is the log from terminal, it appears to be a 400 bad request

` [menu.main_menu_action:29]   Running Prompt Menu Mode                                                        menu.py:29
? Main Menu: What would you like to do? Perform Action(s)
? Action Menu: What action(s) would you like to take? Download content from a user
 [write.setArgs:16]  args changing to {'output': 'DEBUG', 'config': None, 'profile': None, 'log': None,      write.py:16
'discord': 'OFF', 'no_rich': False, 'no_auto_resume': False, 'downloadbars': False, 'downloadsem': None,
'downloadthreads': None, 'quality': None, 'mediatype': [], 'size_max': None, 'size_min': None,
'protected_only': False, 'normal_only': False, 'original': False, 'text_type': 'word', 'space_replacer':
None, 'textlength': None, 'posts': [], 'download_area': [], 'like_area': [], 'filter': '.*', 'neg_filter':
None, 'scrape_paid': False, 'max_count': 0, 'item_sort': None, 'force_all': False, 'force_model_unique':
False, 'force_like': False, 'label': [], 'before_original': None, 'before': <Arrow
[2024-06-10T15:30:25.902763+07:00]>, 'after': None, 'mass_msg': None, 'timed_only': None, 'daemon': None,
'action': {'download'}, 'usernames': [], 'excluded_username': [], 'user_list': [], 'black_list': [],
'current_price': None, 'renewal_price': None, 'regular_price': None, 'promo_price': None, 'last_seen': None,
'free_trail': None, 'promo': None, 'all_promo': None, 'sub_status': None, 'renewal': None,
'promo_price_min': None, 'promo_price_max': None, 'regular_price_min': None, 'regular_price_max': None,
'current_price_min': None, 'current_price_max': None, 'renewal_price_min': None, 'renewal_price_max': None,
'last_seen_before': None, 'last_seen_after': None, 'expired_after': None, 'expired_before': None,
'subscribed_after': None, 'subscribed_before': None, 'sort': 'name', 'desc': False, 'users_first': False,
'individual': False, 'list': False, 'no_cache': False, 'no_api_cache': False, 'key_mode': None,
'dynamic_rules': None, 'update_profile': False, 'download_script': None, 'command': 'OF-Scraper'}
? Scrape entire paid page

[Warning: initial Scan can be slow]
[Caution: You should not need this unless you are looking to scrape paid content from a deleted/banned model] False
 [write.setArgs:16]  args changing to {'output': 'DEBUG', 'config': None, 'profile': None, 'log': None,      write.py:16
'discord': 'OFF', 'no_rich': False, 'no_auto_resume': False, 'downloadbars': False, 'downloadsem': None,
'downloadthreads': None, 'quality': None, 'mediatype': [], 'size_max': None, 'size_min': None,
'protected_only': False, 'normal_only': False, 'original': False, 'text_type': 'word', 'space_replacer':
None, 'textlength': None, 'posts': [], 'download_area': [], 'like_area': [], 'filter': '.*', 'neg_filter':
None, 'scrape_paid': False, 'max_count': 0, 'item_sort': None, 'force_all': False, 'force_model_unique':
False, 'force_like': False, 'label': [], 'before_original': None, 'before': <Arrow
[2024-06-10T15:30:25.902763+07:00]>, 'after': None, 'mass_msg': None, 'timed_only': None, 'daemon': None,
'action': {'download'}, 'usernames': [], 'excluded_username': [], 'user_list': [], 'black_list': [],
'current_price': None, 'renewal_price': None, 'regular_price': None, 'promo_price': None, 'last_seen': None,
'free_trail': None, 'promo': None, 'all_promo': None, 'sub_status': None, 'renewal': None,
'promo_price_min': None, 'promo_price_max': None, 'regular_price_min': None, 'regular_price_max': None,
'current_price_min': None, 'current_price_max': None, 'renewal_price_min': None, 'renewal_price_max': None,
'last_seen_before': None, 'last_seen_after': None, 'expired_after': None, 'expired_before': None,
'subscribed_after': None, 'subscribed_before': None, 'sort': 'name', 'desc': False, 'users_first': False,
'individual': False, 'list': False, 'no_cache': False, 'no_api_cache': False, 'key_mode': None,
'dynamic_rules': None, 'update_profile': False, 'download_script': None, 'command': 'OF-Scraper'}
 [request.get_request_auth:49]  getting new signature                                                      request.py:49
 [request.get_request_auth:49]  getting new signature                                                      request.py:49
 [sessionmanager.requests:356]  failed:  https://onlyfans.com/api2/v2/users/me                     sessionmanager.py:356
 [sessionmanager.requests:357]  status:  400                                                       sessionmanager.py:357
 [sessionmanager.requests:358]  response text : {"error":{"code":301,"message":"Wrong user."}}     sessionmanager.py:358
 [sessionmanager.requests:359]  headers: Headers([('date', 'Thu, 06 Jun 2024 08:30:46 GMT'),       sessionmanager.py:359
('content-type', 'application/json; charset=utf-8'), ('content-length', '46'), ('expires', 'Thu,
19 Nov 1981 08:52:00 GMT'), ('cache-control', 'no-store, no-cache, must-revalidate'), ('pragma',
'no-cache'), ('set-cookie', 'sess={hidden}; expires=Sun, 16-Jun-2024 08:30:46
GMT; Max-Age=864000; path=/; domain=.onlyfans.com; secure; HttpOnly'),
('access-control-allow-credentials', 'true'), ('access-control-allow-methods', 'GET, PUT, POST,
DELETE, OPTIONS, PATCH'), ('access-control-allow-headers', 'Origin, Content-Type, Authorization,
X-Requested-With, User-Agent, Access-Token, User-Id, Time, Sign, X-BC, App-Token, X-Of-Rev,
X-Hash, Csrf'), ('access-control-expose-headers', 'Content-Length, Content-Range, Date,
Access-Token, User-Id, X-OF-REV'), ('allow', 'PUT, GET, DELETE, POST'), ('x-of-rev',
'202406051438-9d39aa517c'), ('strict-transport-security', 'max-age=31536000; includeSubdomains;
preload'), ('x-frame-options', 'DENY'), ('cf-cache-status', 'DYNAMIC'), ('set-cookie',
'__cf_bm=L5ESBUZs_NvXtwPOUEh_sYFzaorn1FyI0NDb_OjYGCo-1717662646-1.0.1.1-dQ0s2aZJNnpCKDUcZlhhOOhTKx
WyALKXCclKAxvYa1x3I7G9tEzB50eE9D0SeBnunmGNn5FhPYLaoOXwyIkg6g; path=/; expires=Thu, 06-Jun-24
09:00:46 GMT; domain=.onlyfans.com; HttpOnly; Secure; SameSite=None'), ('set-cookie',
'_cfuvid=1DG04H5jo0UaBjskeKyjWuqTLEGIbLE.P84ck00VdfM-1717662646255-0.0.1.1-604800000; path=/;
domain=.onlyfans.com; HttpOnly; Secure; SameSite=None'), ('server', 'cloudflare'), ('cf-ray',
'88f70ad2af0e6900-DFW'), ('alt-svc', 'h3=":443"; ma=86400')])
TRACEBACK_  [helpers.inner:11]  Client error '400 Bad Request' for url                                     helpers.py:11
           'https://onlyfans.com/api2/v2/users/me'
           For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
TRACEBACK_  [helpers.inner:11]  Traceback (most recent call last):                                         helpers.py:11
             File
           "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionmanager
           .py", line 360, in requests
               r.raise_for_status()
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\httpx\_models.py", line
           761, in raise_for_status
               raise HTTPStatusError(message, request=request, response=self)
           httpx.HTTPStatusError: Client error '400 Bad Request' for url
           'https://onlyfans.com/api2/v2/users/me'
           For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

 [sessionmanager.<lambda>:320]  attempt: 2 for https://onlyfans.com/api2/v2/users/me               sessionmanager.py:320
 [sessionmanager.requests:356]  failed:  https://onlyfans.com/api2/v2/users/me                     sessionmanager.py:356
 [sessionmanager.requests:357]  status:  400                                                       sessionmanager.py:357
 [sessionmanager.requests:358]  response text : {"error":{"code":0,"message":"Something went       sessionmanager.py:358
wrong. [29141B1D]"}}
 [sessionmanager.requests:359]  headers: Headers([('date', 'Thu, 06 Jun 2024 08:30:49 GMT'),       sessionmanager.py:359
('content-type', 'application/json; charset=utf-8'), ('content-length', '65'), ('set-cookie',
'sess=1v7mtthek21ukmqgoaisf2nh4j; expires=Sun, 16-Jun-2024 08:30:49 GMT; Max-Age=864000; path=/;
domain=.onlyfans.com; secure; HttpOnly'), ('expires', 'Thu, 19 Nov 1981 08:52:00 GMT'),
('cache-control', 'no-store, no-cache, must-revalidate'), ('pragma', 'no-cache'), ('x-of-rev',
'202406051438-9d39aa517c'), ('strict-transport-security', 'max-age=31536000; includeSubdomains;
preload'), ('x-frame-options', 'DENY'), ('cf-cache-status', 'DYNAMIC'), ('set-cookie',
'sess=1v7mtthek21ukmqgoaisf2nh4j; expires=Sun, 16-Jun-2024 08:30:49 GMT; Max-Age=864000; path=/;
domain=.onlyfans.com; secure; HttpOnly'), ('set-cookie',
'__cf_bm=rX1pEkpXrwO_X9hNIOVrKnezO_JJ7qTEP4PIZH_eK9Y-1717662649-1.0.1.1-dQhl31xM796W7UincJ57yRNsDc
cysiUSDKOYrZxeE.ju2qMomTdD6kN5227Z3_9I.SkJ5otdQiyMRe3lqds2FQ; path=/; expires=Thu, 06-Jun-24
09:00:49 GMT; domain=.onlyfans.com; HttpOnly; Secure; SameSite=None'), ('set-cookie',
'_cfuvid=7WosOkeUusqSJUe0VqRhr1OiB3WVf06q5OQKlTAikcE-1717662649879-0.0.1.1-604800000; path=/;
domain=.onlyfans.com; HttpOnly; Secure; SameSite=None'), ('server', 'cloudflare'), ('cf-ray',
'88f70ae96e6f6900-DFW'), ('alt-svc', 'h3=":443"; ma=86400')])
TRACEBACK_  [helpers.inner:11]  Client error '400 Bad Request' for url                                     helpers.py:11
           'https://onlyfans.com/api2/v2/users/me'
           For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
TRACEBACK_  [helpers.inner:11]  Traceback (most recent call last):                                         helpers.py:11
             File
           "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionmanager
           .py", line 360, in requests
               r.raise_for_status()
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\httpx\_models.py", line
           761, in raise_for_status
               raise HTTPStatusError(message, request=request, response=self)
           httpx.HTTPStatusError: Client error '400 Bad Request' for url
           'https://onlyfans.com/api2/v2/users/me'
           For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

 [sessionmanager.<lambda>:320]  attempt: 3 for https://onlyfans.com/api2/v2/users/me               sessionmanager.py:320
 [request.get_request_auth:49]  getting new signature                                                      request.py:49
 [sessionmanager.requests:356]  failed:  https://onlyfans.com/api2/v2/users/me                     sessionmanager.py:356
 [sessionmanager.requests:357]  status:  400                                                       sessionmanager.py:357
 [sessionmanager.requests:358]  response text : {"error":{"code":301,"message":"Wrong user."}}     sessionmanager.py:358
 [sessionmanager.requests:359]  headers: Headers([('date', 'Thu, 06 Jun 2024 08:30:56 GMT'),       sessionmanager.py:359
('content-type', 'application/json; charset=utf-8'), ('content-length', '46'), ('set-cookie',
'sess=gpq9ab1p5t3m71thirshaddakh; expires=Sun, 16-Jun-2024 08:30:56 GMT; Max-Age=864000; path=/;
domain=.onlyfans.com; secure; HttpOnly'), ('expires', 'Thu, 19 Nov 1981 08:52:00 GMT'),
('cache-control', 'no-store, no-cache, must-revalidate'), ('pragma', 'no-cache'),
('access-control-allow-credentials', 'true'), ('access-control-allow-methods', 'GET, PUT, POST,
DELETE, OPTIONS, PATCH'), ('access-control-allow-headers', 'Origin, Content-Type, Authorization,
X-Requested-With, User-Agent, Access-Token, User-Id, Time, Sign, X-BC, App-Token, X-Of-Rev,
X-Hash, Csrf'), ('access-control-expose-headers', 'Content-Length, Content-Range, Date,
Access-Token, User-Id, X-OF-REV'), ('allow', 'PUT, GET, DELETE, POST'), ('x-of-rev',
'202406051438-9d39aa517c'), ('strict-transport-security', 'max-age=31536000; includeSubdomains;
preload'), ('x-frame-options', 'DENY'), ('cf-cache-status', 'DYNAMIC'), ('set-cookie',
'sess=gpq9ab1p5t3m71thirshaddakh; expires=Sun, 16-Jun-2024 08:30:56 GMT; Max-Age=864000; path=/;
domain=.onlyfans.com; secure; HttpOnly'), ('set-cookie',
'__cf_bm=pslpobyO8xpWvonM85gbs5e8usKoiBVZ0Q3ywxI_Qt8-1717662656-1.0.1.1-wPPWi7vWz8AVIW_XKEcMV8q5Kw
yC26bv6R0vuw3vIOQ7ECqmOQcKqu8XOsjcCv4M7jjSTlK0ns0Ke0O6.oMy9w; path=/; expires=Thu, 06-Jun-24
09:00:56 GMT; domain=.onlyfans.com; HttpOnly; Secure; SameSite=None'), ('set-cookie',
'_cfuvid=R57fyetXTPoWXbVDoG.LLZeskJHsqQ9n213SvBfrLMo-1717662656655-0.0.1.1-604800000; path=/;
domain=.onlyfans.com; HttpOnly; Secure; SameSite=None'), ('server', 'cloudflare'), ('cf-ray',
'88f70b13bdf26900-DFW'), ('alt-svc', 'h3=":443"; ma=86400')])
TRACEBACK_  [helpers.inner:11]  Client error '400 Bad Request' for url                                     helpers.py:11
           'https://onlyfans.com/api2/v2/users/me'
           For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
TRACEBACK_  [helpers.inner:11]  Traceback (most recent call last):                                         helpers.py:11
             File
           "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionmanager
           .py", line 360, in requests
               r.raise_for_status()
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\httpx\_models.py", line
           761, in raise_for_status
               raise HTTPStatusError(message, request=request, response=self)
           httpx.HTTPStatusError: Client error '400 Bad Request' for url
           'https://onlyfans.com/api2/v2/users/me'
           For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

TRACEBACK_  [helpers.inner:11]  Client error '400 Bad Request' for url                                     helpers.py:11
           'https://onlyfans.com/api2/v2/users/me'
           For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
TRACEBACK_  [helpers.inner:11]  Traceback (most recent call last):                                         helpers.py:11
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\me.py",
           line 38, in _scraper_user_helper
               with c.requests(constants.getattr("meEP")) as r:
             File "C:\Users\your_username\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line
           137, in __enter__
               return next(self.gen)
                      ^^^^^^^^^^^^^^
             File
           "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionmanager
           .py", line 313, in requests
               for _ in Retrying(
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py",
           line 435, in __iter__
               do = self.iter(retry_state=retry_state)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py",
           line 368, in iter
               result = action(retry_state)
                        ^^^^^^^^^^^^^^^^^^^
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py",
           line 410, in exc_check
               raise retry_exc.reraise()
                     ^^^^^^^^^^^^^^^^^^^
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py",
           line 183, in reraise
               raise self.last_attempt.result()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
             File
           "C:\Users\your_username\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py
           ", line 449, in result
               return self.__get_result()
                      ^^^^^^^^^^^^^^^^^^^
             File
           "C:\Users\your_username\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py
           ", line 401, in __get_result
               raise self._exception
             File
           "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionmanager
           .py", line 367, in requests
               raise E
             File
           "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionmanager
           .py", line 360, in requests
               r.raise_for_status()
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\httpx\_models.py", line
           761, in raise_for_status
               raise HTTPStatusError(message, request=request, response=self)
           httpx.HTTPStatusError: Client error '400 Bad Request' for url
           'https://onlyfans.com/api2/v2/users/me'
           For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

TRACEBACK_  [helpers.inner:11]  Client error '400 Bad Request' for url                                     helpers.py:11
           'https://onlyfans.com/api2/v2/users/me'
           For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
TRACEBACK_  [helpers.inner:11]  Traceback (most recent call last):                                         helpers.py:11
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\init.py",
           line 34, in getstatus
               me.scrape_user()
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\me.py",
           line 33, in scrape_user
               return _scraper_user_helper(c)
                      ^^^^^^^^^^^^^^^^^^^^^^^
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\me.py",
           line 53, in _scraper_user_helper
               raise E
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\me.py",
           line 38, in _scraper_user_helper
               with c.requests(constants.getattr("meEP")) as r:
             File "C:\Users\your_username\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line
           137, in __enter__
               return next(self.gen)
                      ^^^^^^^^^^^^^^
             File
           "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionmanager
           .py", line 313, in requests
               for _ in Retrying(
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py",
           line 435, in __iter__
               do = self.iter(retry_state=retry_state)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py",
           line 368, in iter
               result = action(retry_state)
                        ^^^^^^^^^^^^^^^^^^^
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py",
           line 410, in exc_check
               raise retry_exc.reraise()
                     ^^^^^^^^^^^^^^^^^^^
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py",
           line 183, in reraise
               raise self.last_attempt.result()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
             File
           "C:\Users\your_username\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py
           ", line 449, in result
               return self.__get_result()
                      ^^^^^^^^^^^^^^^^^^^
             File
           "C:\Users\your_username\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py
           ", line 401, in __get_result
               raise self._exception
             File
           "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionmanager
           .py", line 367, in requests
               raise E
             File
           "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionmanager
           .py", line 360, in requests
               r.raise_for_status()
             File "C:\Users\your_username\pipx\venvs\ofscraper\Lib\site-packages\httpx\_models.py", line
           761, in raise_for_status
               raise HTTPStatusError(message, request=request, response=self)
           httpx.HTTPStatusError: Client error '400 Bad Request' for url
           'https://onlyfans.com/api2/v2/users/me'
           For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

 [checkers.check_auth:20]  Auth Failed                                                 `

**Comment by datawhores** [comment]
Probably have to switch dynamic rule

**Comment by datawhores** [comment]
https://gist.github.com/datawhores/8e8be131fb1b190b50c5324ab2ca5f89
follow option 1

**Comment by ChillyP** [comment]
Having the same issue, have changed the dynamic rule in config.json but still getting

Trying to login attempt:1/10
 [scraper.check_auth:340]  Auth Failed

**Comment by El-tra** [comment]
> https://gist.github.com/datawhores/8e8be131fb1b190b50c5324ab2ca5f89 follow option 1

Script runs with the suggested changes but doesn't download anything. (And without throwing any errors.)

**Comment by datawhores** [comment]
use the auth issue pinned posts
