### ISSUE TITLE
3.10.1 scrapes but save nothing to db and download no files

### ISSUE THREAD

**Issue by Rustybrickc** [datawhores/OF-Scraper#406]
I downloaded version 3.10.1 exe. I changed the rule to "growik" in the settings. Scrapper starts, gets to the input of cookies from the Mozilla helper. I enter the data, and after loading the list of models, I choose any of them, selecting "false paid content". Scrapper starts parsing the pages. After a certain time, parsing of pages finishes, and the script writes that the job is completed. No files are downloaded, and even if I check the database, the table is completely empty.

**Comment by datawhores** [comment]
This description is not very helpful
Provide a log

**Comment by Rustybrickc** [comment]
[ofscraper_main_profile_2024-06-06.log](https://github.com/user-attachments/files/15606845/ofscraper_main_profile_2024-06-06.log)
