### ISSUE TITLE
After updating from 3.4.4 to 3.10.1, content doesn't download and script crashes

### ISSUE THREAD

**Issue by JohnnyTowns94** [datawhores/OF-Scraper#407]
When I rip content from models after updating to 3.10.1, the script will crash. I have attached my log.
[ofscraper_main_profile_2024-06-06.log](https://github.com/user-attachments/files/15613868/ofscraper_main_profile_2024-06-06.log)

**Comment by datawhores** [comment]
I made a update so this issue should be fixed

**Comment by demib72** [comment]
The model_id and username are switched for some reason. Added print(username,model_id) to see why it is receiving an integer when downloading and got this: https://gist.github.com/demib72/fdf573ee6a478a282566678b6d9876d7

**Comment by JohnnyTowns94** [comment]
> I made a update so this issue should be fixed

All fixed, thank you!
