### ISSUE TITLE
Latest version of ofscraper, 2FA authentication, manual input of auth.json, OF kicks out

### ISSUE THREAD

**Issue by finnishbroccoli** [datawhores/OF-Scraper#408]
## Describe the bug

I've updated session+auth_uid fields when needed. I use 2FA, so far, auth.json updating was successful.  Now I do not see any mistakes how I update the fields.

## Screenshots/Logs

https://privatebin.io/?602dfaaef81fe21f#CPxe7irvTZy8gP5D9QacvqXu7D91ZRvxJxe9YHDCCq4d

## Config
{
    "main_profile": "main_profile",
    "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}",
    "discord": "",
    "file_options": {
        "save_location": "/home/mkw/kookas/pron/ofscraper",
        "dir_format": "{model_username}/{responsetype}/{mediatype}/",
        "file_format": "{filename}.{ext}",
        "textlength": 0,
        "space_replacer": " ",
        "date": "DD-MM-YYYY",
        "text_type_default": "letter",
        "truncation_default": true
    },
    "download_options": {
        "file_size_max": 0,
        "file_size_min": 0,
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "auto_resume": true,
        "system_free_min": 0,
        "max_post_count": 0
    },
    "binary_options": {
        "mp4decrypt": "/home/mkw/.config/ofscraper/bin/mp4decrypt",
        "ffmpeg": "/home/mkw/.config/ofscraper/bin/ffmpeg"
    },
    "cdm_options": {
        "private-key": null,
        "client-id": null,
        "key-mode-default": "keydb",
        "keydb_api": "517453862d4256fd8bad4f58422004d7:5b4b848eac0855d79165d05f3cf16d56"
    },
    "performance_options": {
        "download-sem": 6,
        "threads": 2
    },
    "advanced_options": {
        "code-execution": false,
        "dynamic-mode-default": "deviint",
        "backend": "aio",
        "downloadbars": false,
        "cache-mode": "sqlite",
        "appendlog": true,
        "custom_values": null,
        "sanitize_text": false,
        "temp_dir": null,
        "remove_hash_match": false,
        "infinite_loop_action_mode": false,
        "post_download_script": null,
        "disable_auto_after": false,
        "default_user_list": "main",
        "default_black_list": ""
    },
    "responsetype": {
        "timeline": "Posts",
        "message": "Messages",
        "archived": "Archived",
        "paid": "Messages",
        "stories": "Stories",
        "highlights": "Stories",
        "profile": "Profile",
        "pinned": "Posts"
    },
    "overwrites": {
        "audios": {},
        "videos": {},
        "images": {},
        "text": {}
    }
}
## System Info

- OS: Linux 6.9.3-zen1-1-zen
- Browser vivaldi
- Version6.7.3329.39 (Stable channel) stable (64-bit) 
- python
- python version  installed via pip

**Comment by cjb900** [comment]
https://gist.github.com/datawhores/8e8be131fb1b190b50c5324ab2ca5f89

**Comment by finnishbroccoli** [comment]
> https://gist.github.com/datawhores/8e8be131fb1b190b50c5324ab2ca5f89

change to grovik did not help

About "sneaky" guide option 2 I do not even know what is the correct way to change config

**Comment by datawhores** [comment]
Please state what version of the script your using 
and make this update in the pinned post for auth issues

**Comment by finnishbroccoli** [comment]
Why this is closed?

**Comment by datawhores** [comment]
"make this update in the pinned post for auth issues"

Called auth fix

This is the last post I will make in this thread
