### ISSUE TITLE
Resetting database?

### ISSUE THREAD

**Issue by lordoffools** [datawhores/OF-Scraper#412]
Either my database is corrupted, or something else is going on after upgrading to 3.10.x.

All new updates (available for download) are skipped. Only way to download is to pass the --after 2000 --force-all flags.

Even after downloading via force-all, and noticing that the specific db files were touched/updated, when something newly available to download is looked at, it seems to still be skipped by the script. My hunch is either the db is corrupted, or the checks are failing somehow, but I'm unable to see further despite running in debug mode.

Is anyone else encountering this issue?

If not, what's the safest way to clear the DB and start fresh? I'll then run tests (after downloading all) to confirm.

Thanks!

**Comment by datawhores** [comment]
Can you show the log and I might be able to see what is going on

**Comment by lordoffools** [comment]
Marking this closed as I was able to resolve myself. Seemed like a syntax error in the config (likely user error). Thank you!
