### ISSUE TITLE
Auth Failed 3.10.4 

### ISSUE THREAD

**Issue by BragnarXIX** [datawhores/OF-Scraper#413]
I just installed the new version but when I put the Mozilla authentication it says authentication failed, I use the onlyfans cookies extension

**Comment by cjb900** [comment]
Clear your browser's cookies and cache and re-enter your auth information into the auth.json file and **DO NOT** use the browser extension. Get the auth information manually. If that does not work try using another browser one you have not accessed onlyfans from before.

**Comment by datawhores** [comment]
To  avoid 50 auth issues use the pinned post
