### ISSUE TITLE
not quite an auth problem, but related?

### ISSUE THREAD

**Issue by ssjrocks** [datawhores/OF-Scraper#420]
## Describe the bug

when starting the scraper for the first time it downloads the exe files required, i then paste the cookie details, the script then says something about outputting to console and runs over the previous text and then quits, when i check the log it talks of the auth file not existing... which it does not(i feel like the script was meant to create it from my paste) even if i manually create the file and paste in the json from the cookie helper i get the same crash everytime i run the script

## To Reproduce

just ran the program

## Screenshots/Logs

[Logs are required for any reports of any issue, unless the issue is related to setup of script
Logs must be at least debug level
pasted below
(https://privatebin.io/?f2a1c78b6760c50c#28ZYwh757w64os8okXxLV35FnD2B6KqkAGbZFEHd43S7)

## Config

config:
{
    "config": {
        "config": {
            "main_profile": "main_profile",
            "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}",
            "discord": "",
            "file_options": {
                "save_location": "C:\\Users\\ssjro\\Data\\ofscraper",
                "dir_format": "{model_username}/{responsetype}/{mediatype}/",
                "file_format": "{filename}.{ext}",
                "textlength": 0,
                "space_replacer": " ",
                "date": "MM-DD-YYYY",
                "text_type_default": "letter",
                "truncation_default": true
            },
            "download_options": {
                "file_size_max": 0,
                "file_size_min": 0,
                "filter": [
                    "Images",
                    "Audios",
                    "Videos"
                ],
                "auto_resume": true,
                "system_free_min": 0,
                "max_post_count": 0
            },
            "binary_options": {
                "mp4decrypt": "",
                "ffmpeg": ""
            },
            "cdm_options": {
                "private-key": null,
                "client-id": null,
                "key-mode-default": "cdrm",
                "keydb_api": ""
            },
            "performance_options": {
                "download-sem": 6,
                "threads": 5
            },
            "advanced_options": {
                "code-execution": false,
                "dynamic-mode-default": "deviint",
                "backend": "aio",
                "downloadbars": false,
                "cache-mode": "sqlite",
                "appendlog": true,
                "custom_values": null,
                "sanitize_text": false,
                "temp_dir": null,
                "remove_hash_match": null,
                "infinite_loop_action_mode": false,
                "post_download_script": null,
                "disable_auto_after": false,
                "default_user_list": "main",
                "default_black_list": ""
            },
            "responsetype": {
                "timeline": "Posts",
                "message": "Messages",
                "archived": "Archived",
                "paid": "Messages",
                "stories": "Stories",
                "highlights": "Stories",
                "profile": "Profile",
                "pinned": "Posts",
                "streams": "Streams"
            },
            "overwrites": {
                "audios": {},
                "videos": {},
                "images": {},
                "text": {}
            },
            "mp4decrypt": "C:\\Users\\ssjro\\.config\\ofscraper\\bin\\mp4decrypt.exe"
        },
        "ffmpeg": "C:\\Users\\ssjro\\.config\\ofscraper\\bin\\ffmpeg.exe"
    },
    "ffmpeg": "C:\\Users\\ssjro\\.config\\ofscraper\\bin\\ffmpeg.exe"
}

## System Info

- win10
- firefox chrome and waterfox
- ofscraper_windows_a6e7dbd.exe
- binary

## Additional context

i used the current version like a month ago... ran with no problems everything as expected... tried yesterday to launch and got the errrors... i deleted the .config in my user folder and tried again... i felt like i potentially broke something somewhere, but i went to another pc at home that has never run anything like this before and got the exact same situation

**Comment by Puk0** [comment]
si tienes esa versión reciente:

1. Dale click al exe para que crea el archivo config.json

2. cierra el programa

3. edita el config.json en lo siguiente:
- "mp4decrypt"
- "ffmpeg"

- "key-mode-default" 
"**manual**" > "client-id" y "private-key"
 o
"**keydb** > "keydb_api" 

-"dynamic-mode-default": "deviint",
-"custom_values": {
            "DEVIINT": "https://raw.githubusercontent.com/datawhores/onlyfans-dynamic-rules/main/dynamicRules.json"
        },
4. Vuelve a abrir el programa y ya te aceptara las cookies
4.1 Sino genera otra cookies

**Comment by ssjrocks** [comment]
sorry im a bit confused... not sure if google translate made mistake


here is my config... i cant see keydb.... it already says keydb_api so i think thats already in there..
i dont know where to find client-id and private-key
is this stuff im supposed to change? the last version i use i didnt touch the config files... it all just ran
and im not sure about the last part... the deviint stuff... do i just paste that at the end?
{
    "config": {
        "config": {
            "main_profile": "main_profile",
            "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}",
            "discord": "",
            "file_options": {
                "save_location": "C:\\Users\\ssjro\\Data\\ofscraper",
                "dir_format": "{model_username}/{responsetype}/{mediatype}/",
                "file_format": "{filename}.{ext}",
                "textlength": 0,
                "space_replacer": " ",
                "date": "MM-DD-YYYY",
                "text_type_default": "letter",
                "truncation_default": true
            },
            "download_options": {
                "file_size_max": 0,
                "file_size_min": 0,
                "filter": [
                    "Images",
                    "Audios",
                    "Videos"
                ],
                "auto_resume": true,
                "system_free_min": 0,
                "max_post_count": 0
            },
            "binary_options": {
                "mp4decrypt": "",
                "ffmpeg": ""
            },
            "cdm_options": {
                "private-key": null,
                "client-id": null,
                "key-mode-default": "cdrm",
                "keydb_api": ""
            },
            "performance_options": {
                "download-sem": 6,
                "threads": 5
            },
            "advanced_options": {
                "code-execution": false,
                "dynamic-mode-default": "deviint",
                "backend": "aio",
                "downloadbars": false,
                "cache-mode": "sqlite",
                "appendlog": true,
                "custom_values": null,
                "sanitize_text": false,
                "temp_dir": null,
                "remove_hash_match": null,
                "infinite_loop_action_mode": false,
                "post_download_script": null,
                "disable_auto_after": false,
                "default_user_list": "main",
                "default_black_list": ""
            },
            "responsetype": {
                "timeline": "Posts",
                "message": "Messages",
                "archived": "Archived",
                "paid": "Messages",
                "stories": "Stories",
                "highlights": "Stories",
                "profile": "Profile",
                "pinned": "Posts",
                "streams": "Streams"
            },
            "overwrites": {
                "audios": {},
                "videos": {},
                "images": {},
                "text": {}
            },
            "mp4decrypt": "C:\\Users\\ssjro\\.config\\ofscraper\\bin\\mp4decrypt.exe"
        },
        "ffmpeg": "C:\\Users\\ssjro\\.config\\ofscraper\\bin\\ffmpeg.exe"
    },
    "ffmpeg": "C:\\Users\\ssjro\\.config\\ofscraper\\bin\\ffmpeg.exe"
}

**Comment by ssjrocks** [comment]
or did you mean i just replace my config file so it only contains 

    "mp4decrypt"

    "ffmpeg"

    "key-mode-default"
    "manual" > "client-id" y "private-key"
    o
    "keydb > "keydb_api"

-"dynamic-mode-default": "deviint",
-"custom_values": {
"DEVIINT": "https://raw.githubusercontent.com/datawhores/onlyfans-dynamic-rules/main/dynamicRules.json"
},

**Comment by ssjrocks** [comment]
https://www.youtube.com/watch?v=DsPj6njhflM i have uploaded a video of how i have been trying to run it, i notice after i put the cookie info it does not create auth.json... still fails when i manually create it

**Comment by Pandafixez** [comment]
Hi ssjrocks,

I was able to get mine to work after checking out the main page, but basically this is what I did. (Also I'm also a newbie when it comes to coding and I prefer the .exe and only having to change a few things)


For your config.json file Ctrl+F and find where it custom_values is located and copy and paste the following

"custom_values": {
            "DEVIINT": "https://raw.githubusercontent.com/datawhores/onlyfans-dynamic-rules/new/dynamicRules.json"
        },

![Ofixer1](https://github.com/datawhores/OF-Scraper/assets/172885987/b155ca2a-1978-49ae-960d-08029e0789e2)


For the Marcus Cookie info you pasted in your video, your email and password was blank " " and I'm not sure if you use 2fa but for I don't on my account so I changed it from true to false.

![Ofixer2](https://github.com/datawhores/OF-Scraper/assets/172885987/18070b32-a788-4291-b0aa-e6fba41764fa)

Hopefully this makes sense and helps!

**Comment by ssjrocks** [comment]
cheers for helping, i havent got the username and password filled in because i dont know what the password would be, i created my account with google...i added the line to the config you mentioned but still get the prob.... im wondering if something changed? because i dont remember filling out the email and pass last time i used this program

**Comment by Pandafixez** [comment]
Oh, no the username and password for those fields are what you used for
only fans since it'll log in to your account to pull up what you can
download from your subscriptions.

**Comment by MongoosePanda** [comment]
Oh boy, my reply looks messy when I reply via email lol.

> cheers for helping, i havent got the username and password filled in because i dont know what the password would be, i created my account with google...i added the line to the config you mentioned but still get the prob.... im wondering if something changed? because i dont remember filling out the email and pass last time i used this program

The account you created with Google is for GitHub, for you can comment. (I'm assuming...if you made that account on here)

The one you copy and paste into the ofscraper.exe when you use the cookie info is _your_ onlyfans login info that you use to log onto the onlyfans website.

**Comment by ssjrocks** [comment]
yeah, what i meant was he asked why my username and pass was not filled out, i had used my google account on onlyfans to signup, now i login to of with google... hence i have no password... nor did i have a password when i last used the app successfully... i thought the cookie info was enough... its all good anyway, im using https://github.com/sim0n00ps/OF-DL now and it works great right outta the box

**Comment by Puk0** [comment]
> or did you mean i just replace my config file so it only contains

1. you open the exe, so that it creates the config.json
2. When it asks for cookies, close it
3. You edit the config.json,
To make it work just edit the following:
- You put the routes to "mp4decrypt" and "ffmpeg"
- In "key-mode-default" you put "manual" and the routes for "client-id" and "private-key"
or "keydb" and in "keydb_api" the api of https://keysdb.net/me
- In "dynamic-mode-default" you put "deviint"
- In "custom_values" you put: "DEVIINT": "https://raw.githubusercontent.com/datawhores/onlyfans-dynamic-rules/main/dynamicRules.json"
4. save the changes
5. You open the program, and when you download it will ask you for cookies
6. Paste the cookies with "cookies helper", and pageDown + Enter
7. Click on "yes" and that's it
8. All other options are more for customization
