### ISSUE TITLE
3.10.6 is not downloading archived content

### ISSUE THREAD

**Issue by JohnnyTowns94** [datawhores/OF-Scraper#421]
3.10.6 is not downloading archived content. Looks like the url may have changed? If I do a --dupe on a model which definitely has archived videos, the script says there are 0 pictures/videos/audios to download.

**Comment by datawhores** [comment]
Can you show a log?
Also do --no-cache as an arg

**Comment by JohnnyTowns94** [comment]
It seems that 3.10.10 has solved this issue.
