### ISSUE TITLE
An error occurred during installation

### ISSUE THREAD

**Issue by hojotis** [datawhores/OF-Scraper#423]
![QQ截图20240619142646](https://github.com/datawhores/OF-Scraper/assets/113195193/96fabb01-c6c4-46f5-8dd9-391fe11dd4fb)
Using python3.11.6

**Comment by cjb900** [comment]
If you are trying to install the latest 3.10.6 version of the scraper via pipx try using `pipx install ofscraper==3.10.6 --force` and see if that works

**Comment by josemerinom** [comment]
That's just a warning from the pip library, which could not verify the latest version, you can update manually using the command "python3 -m pip install --upgrade pip" 
(C:\Users\<<YourUser>>\AppData\Local\Programs\Python)
