### ISSUE TITLE
program proceeds as normal; doesnt try to download anything

### ISSUE THREAD

**Issue by alfratrople** [datawhores/OF-Scraper#433]
it says a lot of "precheck failed using db" i dont know what that means or if its relevant

log file attached. apologies if its a retarded problem.

[ofscraper_main_profile_2024-06-29.log](https://github.com/user-attachments/files/16039867/ofscraper_main_profile_2024-06-29.log)

if you need more info just say

**Comment by datawhores** [comment]
Yeah a lot of things have been moved in the code base
It seems that everything is okay now

**Comment by alfratrople** [comment]
hm, for me the newest version doesnt try to check for anything to download, you select the model page and then it says its finished and asks if you want to go again

**Comment by datawhores** [comment]
How did you install?

I'll check the code base for that method

**Comment by datawhores** [comment]
Okay 
Which executable

And if that is the case you need to get a newer one to fix the issue

**Comment by alfratrople** [comment]
2024.07.01_793652_3.10b_eec31b5_package [ofscraper_windows_eec31b5.exe](https://github.com/datawhores/OF-Scraper/releases/download/eec31b5/ofscraper_windows_eec31b5.exe)

**Comment by datawhores** [comment]
Try this one
https://github.com/datawhores/OF-Scraper/releases/tag/8c96de8

**Comment by alfratrople** [comment]
that works. thanks for the help.
