### ISSUE TITLE
Download Paid content from deleted models accounts.

### ISSUE THREAD

**Issue by tobi-polar** [datawhores/OF-Scraper#434]
**Is your feature request related to a problem? Please describe.**
I can go to OF and see purchased content from models that no longer have accounts. But these accounts don't show as active or expired subscriptions on the scraper menu

**Describe the solution you'd like**
Scrape for paid content from deactivated accounts.

**Comment by datawhores** [comment]
These accounts are no longer accessible via the form usernames API

Even if they were searching the purchase API for these names doesn't seem to yield any result

With that said the --scrape-paid is a brute force scan of the purchase paid, and will capture these models. The modelid are still present, but searching for the username from this model names does not work. So they are called "model deleted"
