### ISSUE TITLE
Content check mode  does not work anymore or only with few models

### ISSUE THREAD

**Issue by lemelomane** [datawhores/OF-Scraper#437]
## Describe the bug

Usually when i use content check mode, i am avaible to select what content to download. Since  maybe 3.14 this mode does not work properly anymore.

## To Reproduce

Hint: enter the command and args would be a good idea

Example

1. cmd
2. ofscraper post_check --url https://onlyfans.com/[name of the model]
3. [close.sendCloseMessage:41]  Finished Script

## Expected behavior

a windows should have open with a table of every content to download.
## Screenshots/Logs
C:\Users\myusername>ofscraper post_check --url https://onlyfans.com/[name of the model]
 [logs.printStartValues:29]  Log Level: DEBUG                                                                logs.py:29
 [logs.printStartValues:30]  3.10.18                                                                         logs.py:30
 [logs.printStartValues:35]  config path: C:\Users\your_username\.config\ofscraper\config.json               logs.py:35
 [logs.printStartValues:36]  profile path: C:\Users\your_username\.config\ofscraper\main_profile             logs.py:36
 [logs.printStartValues:37]  log folder: C:\Users\your_username\.config\ofscraper\logging                    logs.py:37

 _______  _______         _______  _______  _______  _______  _______  _______  _______
(  ___  )(  ____ \       (  ____ \(  ____ \(  ____ )(  ___  )(  ____ )(  ____ \(  ____ )
| (   ) || (    \/       | (    \/| (    \/| (    )|| (   ) || (    )|| (    \/| (    )|
| |   | || (__     _____ | (_____ | |      | (____)|| (___) || (____)|| (__    | (____)|
| |   | ||  __)   (_____)(_____  )| |      |     __)|  ___  ||  _____)|  __)   |     __)
| |   | || (                   ) || |      | (\ (   | (   ) || (      | (      | (\ (
| (___) || )             /\____) || (____/\| ) \ \__| )   ( || )      | (____/\| ) \ \__
(_______)|/              \_______)(_______/|/   \__/|/     \||/       (_______/|/   \__/

 [checkers.check_auth:17]  checking auth status                                                          checkers.py:17
 [check.post_check_retriver:209]  Getting Full Timeline for sexyfeet47                                     check.py:209
 [close.sendCloseMessage:41]  Finished Script

## Config

},
    "advanced_options": {
        "code-execution": false,
        "dynamic-mode-default": "datawhores",
        "backend": "aio",
        "downloadbars": false,
        "cache-mode": "sqlite",
        "appendlog": true,
        "custom_values": {
            "DEVIINT": "https://raw.githubusercontent.com/rafa-9/dynamic-rules/main/rules.json"
        },
        "sanitize_text": false,
        "temp_dir": null,
        "remove_hash_match": null,
        "infinite_loop_action_mode": false,
        "post_download_script": null,
        "enable_auto_after": true,
        "default_user_list": "main",
        "default_black_list": ""

## System Info

- windows 10
- firefox
- Python 3.12.4
- binary or python

**Comment by datawhores** [comment]
you need to run 
ofscraper post_check --log debug (your arguments)


I was not able to reproduce this on my end

**Comment by lemelomane** [comment]
Thanks you for you answer,
There is my link https://privatebin.io/?6f1742fb1d34f90c#BVzu6HvKodMsXh9uCDee3RDe37duTuYgH3nAZroxQCBn
And in attached file the log. At moment the  issue with the post check mode only occur with the model : sexyfeet47
[ofscraper_main_profile_2024-07-27.log](https://github.com/user-attachments/files/16400983/ofscraper_main_profile_2024-07-27.log)

**Comment by datawhores** [comment]
fortunately you didn't use the command I gave last time

ofscraper post_check --log debug  --output debug sexyfeet47 

are you able to provide a screen shot of the screen as well

**Comment by lemelomane** [comment]
Thanks your for your answer and help. 
I didn't understand your instruction avour the command, but then with your last message I understood.

I upadated to the lastest version 3.11.1.

I did your commandand : ofscraper post_check --log debug  --output debug sexyfeet47 

There is in attached file the screenshot 
![post check issue](https://github.com/user-attachments/assets/1c608868-93d6-400d-8557-ae9b4631e95c)
https://privatebin.io/?4fb91f3d12f6be4c#HRifUVnpe31deRS2b9i6H1FGdtAhdv7uTo68YSFwgFTR
[paste-6e87d2f4b793d4a6.txt](https://github.com/user-attachments/files/16477764/paste-6e87d2f4b793d4a6.txt)

Also, I finally the content check mode is finally working with the modele sexyfeet47. But there was some unusual message while downloading file. However, download was successfull.
Please let me know if you need more information

**Comment by datawhores** [comment]
Yes that was my fault
```
ofscraper post_check --log debug  --output debug --url sexyfeet47 
```

**Comment by lemelomane** [comment]
Sorry if I didn't make it clear, you solved my issue. Thanks you alot.
