### ISSUE TITLE
Downloading of content just fails every downloads

### ISSUE THREAD

**Issue by Fefolino** [datawhores/OF-Scraper#439]
Hi all,
I am new with this script, so I don't know well how the things work and what to tell
I am having a big issue, when I try to download content it just fails every download
I set up the script only in the CMD, so I didn't manually touch any files
I tried to change CDMs, I tried them all, at the moment I am trying with keydb. I retrieved the API from the site, but when it asks me for "client id file" and "private-key" I don't where to get them.. Maybe this is the problem? 

[Log](https://privatebin.io/?e3f16d13275ab3e7#DmzJCgbaDzaym7nR9fYSE2nr6sEwtVxV1pptmHCFUEDi)

[Config](https://privatebin.io/?4f72eb53deb17aa5#318u58nxsXFoPDTaLBu867nKyUDtaDcNPD5QdE2NxfBN)

- OS: Windows 11
- Browser Chrome
- Version 3.10.20
- python
- python version 3.11.9 installed via pip

I hope I wrote everything you need, if you need more just ask me!

Thanks for the help!

**Comment by datawhores** [comment]
can you resend the log?

**Comment by Fefolino** [comment]
> can you resend the log?

Hi, I just noticed the "Expires" option in pastebin, btw I changed the save location to be in the same disk where ofscraper is (ofscraper is in C, my download folder was in D, now is in C) and it works. It hasn't the permission to write on disks different from the one where ofscraper is?

**Comment by datawhores** [comment]
No it shouldn't matter
It is up to the operating system to determine in the current user running the script has access to make folders and add files to that foldr

**Comment by datawhores** [comment]
Are you able to update to the latest commit on 3.10b branch
I made some changes that should clear up some of the errors.

There are over 100 instances of cloudflare in the log
However mosts of these seem to be coming from uk.upload.onlyfans.com, which is not accessible any more , and removing that url should get rid of a bunch of the errors
