### ISSUE TITLE
Getting timeline media

### ISSUE THREAD

**Issue by xxx-uploaded** [datawhores/OF-Scraper#44]
- Getting timeline media...

Pages Progress: 37: : 37it [04:01, 13.14s/it]

And so endlessly, who's to say what needs to be done?
![Screenshot_1](https://github.com/datawhores/ofscraper/assets/88721958/6945462f-cc3c-4a86-8656-a7b9c53fa00e)

**Comment by datawhores** [comment]
There is a limit on how many posts can be grabbed at once
