### ISSUE TITLE
mp4decrypt

### ISSUE THREAD

**Issue by neuri48** [datawhores/OF-Scraper#45]
can't set path for mp4decrypt on termux. everything was working fine before some change. is mp4decrypt necessary?

**Comment by datawhores** [comment]
Yes 
Just set it directly in the config file

**Comment by neuri48** [comment]
> Yes Just set it directly in the config file

the path should be the same as the download folderr right?

**Comment by datawhores** [comment]
Right now if you don't the repo it is included
However you need to download yourself if your getting from pypi

https://www.bento4.com/documentation/mp4decrypt/

It's a seperate program so wherever it is on your system

**Comment by neuri48** [comment]
mp4decrypt path:  /data/data/com.termux/files/home/storage/shared/Onlyfans/mp4decrypt
                                                                              

Filepath is invalid or not detected as mp4decrypt

^thats all i get

**Comment by datawhores** [comment]
What happens when you run the command from termux

**Comment by neuri48** [comment]
No command mp4decrypt found,
i installed through pip install ofscraper

**Comment by datawhores** [comment]
It doesn't seem like the file is their 
Can you see it in the file explorer

**Comment by neuri48** [comment]
yes

**Comment by datawhores** [comment]
I'm not sure
can you show a screenshot of where mp4decrypt is on your system
