### ISSUE TITLE
Stuck at Authentication

### ISSUE THREAD

**Issue by Bum211** [datawhores/OF-Scraper#451]
Hello, I downloaded the latest version and commits. I inputted all the auth information and I keep getting stuck at the Auth screen. Does this has to do with the dynamic-mode-default? It's currently "deviint" and the custom_values is also ""DEVIINT": "https://raw.githubusercontent.com/datawhores/onlyfans-dynamic-rules/new/dynamicRules."

Please help and thanks!
Bum

**Comment by Puk0** [comment]
In the most recent version it is not necessary to add more than ffmpeg
close it, delete config.json and reopen it

**Comment by Bum211** [comment]
I downloaded the latest file from today and not I'm having issue with ffmpeg... Help please. 

 File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 523, in _check_default_executor
    raise RuntimeError('Executor shutdown has been called')
RuntimeError: Executor shutdown has been callednit__.py", line 346, in loads
Your config.json has a syntax errors)
Traceback (most recent call last):
  File "C:\Users\adang\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\config\context.py", line 16, in
config_contextDecodeError("Extra data", s, end)
    json.load(f)NDecodeError: Extra data: line 1 column 4 (char 3)
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^62]  issue executing path as ffmpeg:                                             check.py:62
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads                                check.py:63
    return _default_decoder.decode(s)back (most recent call last):                                          check.py:64
           ^^^^^^^^^^^^^^^^^^^^^^^^^^nvs\ofscraper\Lib\site-packages\ofscraper\utils\paths\check.py", line
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())rr=subprocess.PIPE)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)as process:
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 8 column 37 (char 259)t__

Invalid \escape: line 8 column 37 (char 259)
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,



There is an issue with the ffmpeg path

**Comment by igobytwo** [comment]
Have same issue I think. Updated to version 3.11.6 but auth keeps failing.

**Comment by Puk0** [comment]
> I downloaded the latest file from today and not I'm having issue with ffmpeg... Help please.
> 
> File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 523, in _check_default_executor raise RuntimeError('Executor shutdown has been called') RuntimeError: Executor shutdown has been callednit__.py", line 346, in loads Your config.json has a syntax errors) Traceback (most recent call last): File "C:\Users\adang.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\config\context.py", line 16, in config_contextDecodeError("Extra data", s, end) json.load(f)NDecodeError: Extra data: line 1 column 4 (char 3) File "C:\Program Files\Python311\Lib\json__init__.py", line 293, in load return loads(fp.read(), ^^^^^^^^^^^^^^^^62] issue executing path as ffmpeg: check.py:62 File "C:\Program Files\Python311\Lib\json__init__.py", line 346, in loads check.py:63 return _default_decoder.decode(s)back (most recent call last): check.py:64 ^^^^^^^^^^^^^^^^^^^^^^^^^^nvs\ofscraper\Lib\site-packages\ofscraper\utils\paths\check.py", line File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end())rr=subprocess.PIPE) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python311\Lib\json\decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx)as process: ^^^^^^^^^^^^^^^^^^^^^^ json.decoder.JSONDecodeError: Invalid \escape: line 8 column 37 (char 259)t__
> 
> Invalid \escape: line 8 column 37 (char 259) hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> 
> There is an issue with the ffmpeg path

- close everything
- delete config.json
- open cmd and put: ofscraper -v
- close cmd 
- in config.json put your ffmpeg path for example:
`"ffmpeg": "D:\\Programs\\Ffmpeg\\Shared\\ffmpeg.exe`
- save changes
- open cmd and put: ofscraper -v 
- ready

**Comment by Bum211** [comment]
Thanks for the note. When I put in ofscraper-v. This is the error I'm seeing: 

![Screenshot 2024-08-25 141542](https://github.com/user-attachments/assets/5496751a-32b4-46f8-ae44-1a89e479abb4)

When you said to delete Config.json, are you talking about this file? 
![image](https://github.com/user-attachments/assets/5cc33b6f-1580-44e2-85df-e6d9278366fc)

sorry I'm new to this. Thank you for your support and patience

**Comment by Bum211** [comment]
Hello, i figured it out. Thank you!
