### ISSUE TITLE
Suggestion: Purchased Folder in Folder Structure

### ISSUE THREAD

**Issue by waswosi** [datawhores/OF-Scraper#453]
At the moment the purchased scenes are downloaded in the Messages folder.
So it can be really hard to find the purchased scenes within all other messages video clips.
So how about let ofscraper make an extra purchased folder for these files?

**Comment by cjb900** [comment]
This is already doable (just not by default). You just need to change the `dir_format` in the config.json file https://of-scraper.gitbook.io/of-scraper/getting-started/config-options/file-output-options/customizing-save-path
