### ISSUE TITLE
A way to download only if the files does not already exist?

### ISSUE THREAD

**Issue by skibidi2981** [datawhores/OF-Scraper#457]
**Is your feature request related to a problem? Please describe.**
I ran into an issue where downloads were marked as downloaded (in the database? not sure where that info is stored), but the file clearly did not exist. After running:

`ofscraper --posts all -ts --username ALL --action download --after 2000 --force-all`

the missing files were downloaded, but this also took a lot of time since `--force-all` redownloads files that already exist as well.

**Describe the solution you'd like**
Is there (or can there be) a flag that bypasses the "marked as downloaded" check? and will not download if the file already exists?

**Comment by liberulo** [comment]
The --after 2000 seems to make the difference for me too.

**Comment by Puk0** [comment]
> were marked as downloaded (in the database?
- what is downloaded is saved in` \.config\ofscraper\main_profile\.data\idmodel\`
- If you download it again it will not download it because it is already in the database
- If you want to download it again use --force-all and it will overwrite it in the database
- if you don't have a database and want to download only from one date onwards with -af <dat

**Comment by skibidi2981** [comment]
Right, but what if I *know* that the database is corrupt in some way? I was using an older version that corrupted the database from a bug, therefore making some media filtered out because the media was deemed "already downloaded", but clearly the media's file did not exist.

`--force-all` currently redownloads *everything*, correct? Even for files that already exist.

So is there a way to "redownload" only files that don't exist, i.e. skip the "already downloaded" check and only check if the file already exists or not?

Would deleting the `.config/ofscraper/main_profile/.data/idmodel/` directory effectively do that? My hope would be that the scraper (with only the `--after 2000` flag) doesn't see any data pertaining to "already downloaded", so it skips the "already downloaded" check for ALL media, but any media (whose file already exists) will NOT be re-downloaded because the file already exists.

**Comment by datawhores** [comment]
you could just do 
ofscraper metadata --metadata update --after 2000 --dupe

This will perform action similar to regular download, but with just checking if files exists, and updating the database

Then you can run the script without the --force-all flag
ofscraper --action download ...etc

**Comment by skibidi2981** [comment]
> you could just do ofscraper metadata --metadata update --after 2000 --dupe
> 
> This will perform action similar to regular download, but with just checking if files exists, and updating the database
> 
> Then you can run the script without the --force-all flag ofscraper --action download ...etc

Thanks! Sounds like this should do exactly what I wanted it to (forcefully update the database based on file existence), I'll try this next time my database gets corrupted, cheers 🫶🫶
