### ISSUE TITLE
Issue #441 still unsolved (--metadata-update argument not recognized on Windows build)

### ISSUE THREAD

**Issue by DADESUPER** [datawhores/OF-Scraper#458]
As i had time to test it today, i can report that (sadly) the bug is still unsolved, regardless of trying the other syntax that was recommended, it crashes the same way.
I have also tried the following syntaxes with no success, they all crash:
```
ofscraper_windows_3.12.1.exe metadata --metadata-update
ofscraper_windows_3.12.1.exe metadata -update
ofscraper_windows_3.12.1.exe --metadata-update
ofscraper_windows_3.12.1.exe --metadata -update
ofscraper_windows_3.12.1.exe -metadata -update
ofscraper_windows_3.12.1.exe -md-update
ofscraper_windows_3.12.1.exe md -update
ofscraper_windows_3.12.1.exe --metadata -update
ofscraper_windows_3.12.1.exe --metadata --metadata-update
ofscraper_windows_3.12.1.exe -metadata --metadata-update
```

The following syntax however does not crash but simply opens the program normally in interactive mode as far as i can tell
```
ofscraper_windows_3.12.1.exe -md -update
```

Original bug report quoted below for reference:

> ## Describe the bug
> Using the --metadata-update argument leads to immediate crashing due to "unrecognized argument"
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> ofscraper_windows_a42cfee.exe --metadata-update
> 
> ## Expected behavior
> Per docs: "This will update files on system based on config, if a file does not exist on system it will be marked as not downloaded in data"
> 
> ## Screenshots/Logs
> Traceback (most recent call last): File "**main**.py", line 4, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\runner\load.py", line 6, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\runner\run.py", line 5, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\commands\picker\picker.py", line 1, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\commands\commands\check.py", line 13, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\api\archive.py", line 23, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\utils\constants.py", line 3, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\utils\config\custom.py", line 3, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\utils\config\file.py", line 7, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\utils\config\utils\context.py", line 5, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\prompts\prompts.py", line 14, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\prompts\prompt_groups\actions.py", line 4, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\prompts\promptConvert.py", line 10, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\utils\live\empty.py", line 4, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "ofscraper\utils\console.py", line 16, in File "ofscraper\utils\args\accessors\output.py", line 4, in low_output File "ofscraper\utils\args\accessors\read.py", line 23, in retriveArgs File "ofscraper\utils\args\main.py", line 46, in parse_args File "click\core.py", line 1157, in **call** File "click\core.py", line 1077, in main File "click\core.py", line 943, in make_context File "cloup\constraints_support.py", line 183, in parse_args File "click\core.py", line 1644, in parse_args File "click\core.py", line 1405, in parse_args File "click\parser.py", line 337, in parse_args File "click\parser.py", line 364, in _process_args_for_options File "click\parser.py", line 514, in _process_opts File "click\parser.py", line 398, in _match_long_opt click.exceptions.NoSuchOption: No such option: --metadata-update [11452] Failed to execute script '**main**' due to unhandled exception!
> 
> ## System Info
> * OS: Windows 10
> * Browser: Chrome
> * Binary version 2024.07.28_201807_dev/3.11_a42cfee_package

**Comment by Puk0** [comment]
> As i had time to test it today, i can report that (sadly) the bug is still unsolved, regardless of trying the other syntax that was recommended, it crashes the same way. I have also tried the following syntaxes with no success, they all crash:
> 
> ```
> ofscraper_windows_3.12.1.exe metadata --metadata-update
> ofscraper_windows_3.12.1.exe metadata -update
> ofscraper_windows_3.12.1.exe --metadata-update
> ofscraper_windows_3.12.1.exe --metadata -update
> ofscraper_windows_3.12.1.exe -metadata -update
> ofscraper_windows_3.12.1.exe -md-update
> ofscraper_windows_3.12.1.exe md -update
> ofscraper_windows_3.12.1.exe --metadata -update
> ofscraper_windows_3.12.1.exe --metadata --metadata-update
> ofscraper_windows_3.12.1.exe -metadata --metadata-update
> ```
> 
> The following syntax however does not crash but simply opens the program normally in interactive mode as far as i can tell
> 
> ```
> ofscraper_windows_3.12.1.exe -md -update

 - comando: **ofscraper metadata --metadata update -u -o**
- user:  ofscraper metadata --metadata update -u <user> -o <all-or-timeline-etc>
- all: ofscraper metadata --metadata update -u all -o all

**Comment by DADESUPER** [comment]
> > As i had time to test it today, i can report that (sadly) the bug is still unsolved, regardless of trying the other syntax that was recommended, it crashes the same way. I have also tried the following syntaxes with no success, they all crash:
> > ```
> > ofscraper_windows_3.12.1.exe metadata --metadata-update
> > ofscraper_windows_3.12.1.exe metadata -update
> > ofscraper_windows_3.12.1.exe --metadata-update
> > ofscraper_windows_3.12.1.exe --metadata -update
> > ofscraper_windows_3.12.1.exe -metadata -update
> > ofscraper_windows_3.12.1.exe -md-update
> > ofscraper_windows_3.12.1.exe md -update
> > ofscraper_windows_3.12.1.exe --metadata -update
> > ofscraper_windows_3.12.1.exe --metadata --metadata-update
> > ofscraper_windows_3.12.1.exe -metadata --metadata-update
> > ```
> 
> * comando: **ofscraper metadata --metadata update -u -o** :
> * user:  `ofscraper_windows_3.12.1.exe metadata --metadata update -u <user> -o <all-or-timeline-etc>`
> * all: `ofscraper_windows_3.12.1.exe metadata --metadata update -u all -o all`
```
ofscraper_windows_3.12.1.exe metadata --metadata update
```
this works properly in interactive mode, thanks, docs would still need to be updated because listed command is worng

**Comment by DADESUPER** [comment]
With proper syntax command works, but [this page](https://of-scraper.gitbook.io/of-scraper/using-the-scraper/recipes/redownload-deleted-downloads) in the docs need to be updated to list the correct command
`ofscraper metadata --metadata update`

**Comment by datawhores** [comment]
Thank you 
the command was change to allow for more flexibility
