### ISSUE TITLE
Choose "Subscribed Models" as default list

### ISSUE THREAD

**Issue by DonaldTPP** [datawhores/OF-Scraper#461]
Could something like this be made as a default setting instead of having your expired and current subs listed first? Unless there is already a way to set it and I've just missed on how to do it?

**Comment by cjb900** [comment]
there is already a way to do this https://of-scraper.gitbook.io/of-scraper/command-reference/shared-options/scrape-metadata-options/account-filter-args#ts-active-subscriptions

**Comment by DonaldTPP** [comment]
It was more of a request for something in the settings so I can just log in, list subbed users, select all and then scrape.

**Comment by datawhores** [comment]
Yes change the list option in the config it's where black list is at

**Comment by DonaldTPP** [comment]
Done.
