### ISSUE TITLE
Auth fail

### ISSUE THREAD

**Issue by Nortorious92** [datawhores/OF-Scraper#467]
My Chrome is all up to date and Ive updated my auth json file and everything looks correct but I keep on getting auth failed error?  I use the 3.12.9 version... anyone know why this keeps showing auth failed?

**Comment by Puk0** [comment]
If you enter the information incorrectly twice, you will be logged out of your account. 
then you have to log back into your account and change it again in the program

**Comment by Nortorious92** [comment]
> If you enter the information incorrectly twice, you will be logged out of your account. then you have to log back into your account and change it again in the program

change it again in the program meaning the auth json file?
