### ISSUE TITLE
"Too many open files" error crashing scraper

### ISSUE THREAD

**Issue by TheTrueColonel** [datawhores/OF-Scraper#470]
## Describe the bug

When using the scraper, after about 33 users scraped, the program will crash and go back to the main menu.

## To Reproduce

Hint: enter the command and args would be a good idea

Example

1. Run `ofscraper` command
2. Select over 33 users to scrape
3. Wait until crash

## Expected behavior

Scraper does not crash do to too many open files.

## Screenshots/Logs

[Logs](https://privatebin.io/?47f1589ce8acbec3#9wRQ2TJnyvugnfhswRYyv8xpNPspmNJbs6ozKrdYMV3U)

## Config

[Config](https://privatebin.io/?d1ba487d9f82b8e9#AKVzyVp4C5Q72fqNr5w1eT8BahvofyMf3eKhqGgr7f7u)

## System Info

- OS: Arch Linux
- Browser: Firefox
- Version: 131 64-bit
- binary or python: Pipx

**Comment by A-Random-Mf** [comment]
Sounds like ulimit
https://askubuntu.com/questions/1182021/too-many-open-files

**Comment by SSj-Saturn** [comment]
This has suddenly started happening for me too, and my ulimit is set to unlimited.
Never been an issue before.
