### ISSUE TITLE
Failure messages for 100% of the content, still the content is there in the directory.

### ISSUE THREAD

**Issue by 0Camus0** [datawhores/OF-Scraper#472]
I tried the both CDRM and manual (providing my keys) and I see the same behavior:

![image](https://github.com/user-attachments/assets/66ed0328-8da0-4184-bbfc-906304696106)

But when I look into my Data folder, all the images and videos are there, I don't see any tmpvideo or anything like that.

Is this expected?

**Comment by cjb900** [comment]
What version of python do you have?

**Comment by 0Camus0** [comment]
> What version of python do you have?

Using 3.13.

**Comment by cjb900** [comment]
Thats why you are having issues. That version has not been tested to work with ofscraper. Completely uninstall it and install python 3.11.6.

**Comment by 0Camus0** [comment]
> Thats why you are having issues. That version has not been tested to work with ofscraper. Completely uninstall it and install python 3.11.6.

Thanks, I will

**Comment by 0Camus0** [comment]
Yeah, it was the python version. Thanks. Closing the bug.
