### ISSUE TITLE
Post ID in folder name

### ISSUE THREAD

**Issue by valdearg** [datawhores/OF-Scraper#48]
I migrated over from the DC script to this and it's working great. One thing that I did have in the DC script was that I had posts go into their own folder.

In the DC script I had:

`        "file_directory_format": "OnlyFans-new2/{model_username}/{api_type}/{media_type}/{post_id} ({date})", `

I currently have the following in this script:

`        "dir_format": "{model_username}/{responsetype}/{mediatype}/", `

Is this possible or something that could be added? I couldn't see the post_id in the docs here: https://github.com/datawhores/OF-Scraper/wiki/Customizing-save-path#dir_path

**Comment by datawhores** [comment]
post id is in the filename section

**Comment by valdearg** [comment]
Apologies, forgot about this one. I did see that the post_id is in the filename section. 

I'd like to put them into folders:

        "file_format": "{post_id} ({date})/{post_id}_{filename}.{ext}",

This gives the correct path, but needs to create the folder otherwise it fails:

``` 
023-05-29 21:45:26 - DEBUG - Media:2108644840 Post:95447788407 Downloading with normal downloader
2023-05-29 21:45:26 - DEBUG - Media:2115786067 Post:102494066850 [attempt 1/5] exception [Errno 2] No such file or directory: 'G:\\Scripts\\ofscraper\\<model>\\Messages\\Images\\102494066850 (22-05-2021)\\102494066850_1847x3024_35f480e70c3d010e51581e3257a2532d.jpeg.part'
2023-05-29 21:45:26 - DEBUG - Media:2115786067 Post:102494066850 [attempt 1/5] exception Traceback (most recent call last):
  File "C:\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 135, in download
    return await main_download_helper(ele,path,file_size_limit,username,model_id,progress)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 166, in main_download_helper
    with open(temp, 'wb') as f:
    ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\Scripts\\ofscraper\\<model>\\Messages\\Images\\102494066850 (22-05-2021)\\102494066850_1847x3024_35f480e70c3d010e51581e3257a2532d.jpeg.part'
```

I added in a quick and nasty solution, which is just a check on whether the folder exists, if not just create it. Probably a better way of doing it, but in utils\download.py before line 166 I just added this:

```
                        folder_path = str(temp).rsplit('\\', 1)[0]
                        log.debug(f"Path for creation: {folder_path} ")

                        if not os.path.exists(folder_path):
                            os.makedirs(folder_path)
```
Probably an easier solution.

**Comment by datawhores** [comment]
pathlib.mkdir is a little better
pathlib.mkdir(parents=True, exist_ok=True)
Something like that
We can add post_id to dir

**Comment by valdearg** [comment]
Oh, slightly interestingly, this ends up with:

71160139506_1 (13-04-2021)
71160139506_2 (13-04-2021)

When a post has multiple images. Would it be possible to get them into one folder?

**Comment by datawhores** [comment]
It because filenames need something to make them unique 
the script uses a counter

By the way I added post_id to dir
since the uniqueness requirment is no longer needed it does not use a counter

**Comment by datawhores** [comment]
https://github.com/datawhores/OF-Scraper/commit/7c3a1ad54a707affbb886f928b2a6aa2535bf833
