### ISSUE TITLE
module 'pathlib' has no attribute 'os'

### ISSUE THREAD

**Issue by SpoogLord** [datawhores/OF-Scraper#488]
## Description

when scraping, all downloads are failing. looking at the log file reveals 
![AttributeError: module 'pathlib' has no attribute 'os'](https://github.com/user-attachments/assets/0b79d8e0-b8aa-4cfa-8a3e-e8b886cce653)

this is happening regardless of config settings, even with the default config

- OS: Windows 10
- Versions 3.12.9 & 3.12.8 (i tried downgrading to test)
- python 3.13.1

**Comment by cjb900** [comment]
Do not use python 3.13.x. Many here have had issues using it. Recommend using python 3.11.6 which seems to be the most stable for this scraper.

**Comment by SpoogLord** [comment]
i did not know that, ill try it

**Comment by SpoogLord** [comment]
yup, that was it. Thank you!
