### ISSUE TITLE
What's the proper way of updating the script?

### ISSUE THREAD

**Issue by avekifes** [datawhores/OF-Scraper#49]
Is running the "pip install ofscraper" command all that's needed? I tried that, but I can't tell what version I'm actually on. My existing config file hasn't been updated with any of the new stuff (e.g., mp4decrypt), either.

**Comment by datawhores** [comment]
Yes 
ofscraper -v should give you a basic version

**Comment by datawhores** [comment]
pip install ofscraper --upgrade
