### ISSUE TITLE
[Feature Request] Add a way to rename content after it's been downloaded

### ISSUE THREAD

**Issue by coderdudeo** [datawhores/OF-Scraper#50]
Is there a way to rename content after it's been downloaded? I've run into the issue where the {text} placeholder didn't truncate enough so I'm left with some random files with no extensions. I've tried using --dupe to force redownload with a different filename but it doesn't seem to change anything. I resorted to using a bulk renamer and hoping all files are either .mp4 or .jpeg, but not ideal. Any thoughts if we could get this as a feature?

**Comment by datawhores** [comment]
Are you setting a text length limit?

**Comment by datawhores** [comment]
Renaming should be possible it going to require copying the files for safety. Too much risk for information lost otherwise.

But we could do one at time to make sure not too much space is required.

**Comment by datawhores** [comment]
I added this to the project board
