### ISSUE TITLE
Force download all

### ISSUE THREAD

**Issue by mwald84** [datawhores/OF-Scraper#51]
Not sure if here is the correct place for this. Please let me know if I should post this somewhere else. I couldn't find help on the wiki and there's no forum (afaik).

I recently started using the script. I ran it a first time and started to download the media. Then I decided to change a few parameters (file name pattern) and rerun it on a different folder to start over (I didn't finish the first run).

I used the -dupe option to redownload all files. but I notice that some of the files complete downloaded on my first run weren't downloaded on the second run in the new folder, even using the -dupe option (mostly DRM files).

Should I delete the cache? Or what is the correct procedure to fix this?

Thanks in advance and sorry again if this is not the proper place for this.

**Comment by datawhores** [comment]
ofscraper --dupe

**Comment by mwald84** [comment]
yes, I used the dupe option.

**Comment by datawhores** [comment]
It may be the decryption key can you 
add --log debug and then you can posts the logs or send on discord

**Comment by mwald84** [comment]
I used the --log and took a look at it. It seems not even trying to download them. It downloaded previous drm files and the last one from yesterday but the ones in the middle aren't even showing in the log. Other than that it seems to be working just fine.

While looking at the log I noticed another file being skipped and throwing an excetion (showing in the log). Apparentý it cannot connect to the remote host for that file. I'm gonna try to see if I can get more info about it.

Thanks for the help so far. I might close this issue and open a new one if I find something new (feel free to close it if you want).

I'll keep you updated if I can find something more meaningful about it.

**Comment by datawhores** [comment]
I made some changes to improve retrieval of posts

**Comment by us3r95** [comment]
Similar problem (?) 
with messages (not drm/not paid):

`ofscraper --account-type paid --sub-status active --posts messages --username ****** --dupe --log debug`

DEBUG - Namespace(version='2.1+.f466e7c', username=['****'], daemon=None, log='DEBUG', discord='OFF', output='NORMAL', dupe=True, posts=['messages'], letter_count=False, action=None, account_type='paid', renewal=None, sub_status='active', before=None, after=None, users_first=False)
DEBUG - Messages Cache 72 found
DEBUG - Some messages where not retrived resetting cache


I run again 
`ofscraper --account-type paid --sub-status active --posts messages --username ****** --dupe --log debug`
and then it works.

**Comment by datawhores** [comment]
Have they previously been downloaded

**Comment by us3r95** [comment]
Yes. I change "file_format" too.

**Comment by datawhores** [comment]
I think your issue might be slightly different
If you already downloaded something then it should not download again

The dupe option is for forced download
If something is not downloading with dupe 
That should not be happening

**Comment by datawhores** [comment]
Not caching would probably fix this issue

But the script would be a lot slower
Saying that looking into how to improve caching.

It's not as simple as just getting the links. Because they seem to change daily

**Comment by datawhores** [comment]
I redid how the cache works so it should grab every posts the first time now
or at least do a better job of it

**Comment by datawhores** [comment]
You should verify that the content still shows up when you search for it by username.

If not you have to use the scrape paid or toggle scrape entire paid page in the prompt menu. It the one with the warning about not using if the model is deleted

**Comment by datawhores** [comment]
If you can
Use this command 
ofscraper --log trace

It would be a lot of output so
force Stopping once the downloading starts would be a good idea.
