### ISSUE TITLE
Minor confusion with config path

### ISSUE THREAD

**Issue by ALonelyJuicebox** [datawhores/OF-Scraper#52]
I would like to have the script save the the `user_data.db` file for each performer into a folder named `metadata` with that folder stored with the saved content itself but I'm having trouble sorting this out.

**For example**
`R:\SomeTopLevelDirectoryName\JanePerformer\Messages\`
`R:\SomeTopLevelDirectoryName\JanePerformer\Metadata\user_data.db` <-- Just like this
`R:\SomeTopLevelDirectoryName\JanePerformer\Posts\`

The default settings put the path for these SQLite DBs somewhere alongside other .json files for things like entering cookie data.
Despite a few attempts I haven't been able to use the guide below to sort out what to use here. 
There doesn't seem to be a `{save_location}` variable for me to use.

https://github.com/datawhores/OF-Scraper/wiki/Customizing-save-path

Any advice? Thanks! 🙂

**Comment by datawhores** [comment]
This should work
{save_location}/{model_username}/Metadata/

**Comment by ALonelyJuicebox** [comment]
Thank you! 🙏🏿
