### ISSUE TITLE
Script ends when selecting to run again after setting variables

### ISSUE THREAD

**Issue by outsdr01** [datawhores/OF-Scraper#53]
===========================
Script Finished
Run Time:  0:50:09
===========================

? Do you want to continue with script Yes
? What would you like to do? Download content from a user
                                                                                                          scraper.py:505
==============================
starting script
==============================

Using profile: main_profile
Status - UP
? Do you want to reset username option Yes
? Modify filters for your accounts list?
Some usage examples are scraping free accounts only or paid accounts without renewal Yes
? Filter account by renewal of subscription status Both
? Filter accounts based on access to content via a subscription Active Only
? Filter accounts by the type of subscription Both
Cleaning up .part files                                                                                      paths.py:75

M:\OF-Scraper-main>ofscraper -v
0.0.0+main.a79ed15

**Comment by outsdr01** [comment]
Sorry, I don't know why it looks weird. I pasted plain text.

**Comment by datawhores** [comment]
Please run with the debugger
--log debugger
and look for the debug file in .config folder

**Comment by ctrlcmdshft** [comment]
I've had same issue running script again when it asks and I choose not to reset model option and it just ends script after selecting my choices 

So I just stop script and re run

**Comment by outsdr01** [comment]
Log file attached. 
[ofscraper_main_profile_2023-05-23.log](https://github.com/datawhores/OF-Scraper/files/11547662/ofscraper_main_profile_2023-05-23.log)

**Comment by datawhores** [comment]
I pushed some fixes for this issue

**Comment by datawhores** [comment]
This has been reported fix so I'm closing for now
