### ISSUE TITLE
[Feature Request] Optional Skip For Timed Posts

### ISSUE THREAD

**Issue by Jules-WinnfieldX** [datawhores/OF-Scraper#60]
It'd be nice to have the option to skip the download of timed posts as most are advertisements.

**Comment by datawhores** [comment]
I might need an example

**Comment by Jules-WinnfieldX** [comment]
![image](https://github.com/datawhores/OF-Scraper/assets/61347133/5f1ce70c-db67-4627-afc0-4173f9fb1db9)
This profile has a ton of them. In the returned post json obj it's any post where expiresAt is not null.

**Comment by datawhores** [comment]
Ah I see thank you

**Comment by datawhores** [comment]
--skip-promo

**Comment by Jules-WinnfieldX** [comment]
Appreciate it
