### ISSUE TITLE
For more information check: https://httpstatuses.com/429

### ISSUE THREAD

**Issue by CannotTouch** [datawhores/OF-Scraper#62]
Can you insert some kind of delay or retry for it, plz?

I use the `ofscraper --posts all --username model1,model2,model3,...` to scrape a personal list but there are some model that have too much content and goes on 429 even if scraped alone.

Or at least a system that don't scrape everytime from the start (if not forced) and it remember where it was last time...

Thanks for support

**Comment by ctrlcmdshft** [comment]
It should only be scrapping content it hasn't scrapped yet. If you start scrapping a model and then it downloaded 100 of the 500 videos and you stop it then when scrapping again it will verify it scrapper the 100 then begin scrapping the 400 videos that are left. There is a database file that know what was downloaded. If it's scrapping every post again ten make sure you aren't using the --dupe flag. If it were me I would run scrapper normally with ofscraper the choose the options you want let it finish then start using you full command line flags

**Comment by CannotTouch** [comment]
Nope the problem is that it don't arrive neither at the download part... it goes on the 429 error while cheching the pages. it stop at page 936. and than continue to other models going on 429 directly on each of them (till the 429 pass and than after a lot of 429 finally ir restart working).


Getting Selected post type(s) for model_username
Subscription Active: True
Name: model_name | Username: model_username | ID: model_id | Joined:
2020-04-23T00:00:00+00:00
- 28128 posts
 -- 19656 photos
 -- 6964 videos
 -- 326 audios
- 76 archived posts
Pages Progress: 942: : 942it [01:18, 11.96it/s]
Pages Progress: 0: 0it [01:10, ?it/s]
run failed with exception:  Client error '429 Too Many Requests' for url
'https://onlyfans.com/api2/v2/chats/model_id/messages?limit=100&offset=0&id=id_id&order=desc&skip_users=all&skip
_users_dups=1'
For more information check: https://httpstatuses.com/429
Getting Selected post type(s) for model_name_2
Subscription Active: True
run failed with exception:  Client error '429 Too Many Requests' for url
'https://onlyfans.com/api2/v2/users/model_name_2'
For more information check: https://httpstatuses.com/429

**Comment by datawhores** [comment]
I think the retry library this program is using is pretty flexible

We can try to make some changes.
Maybe do increase the number and change the variation of lenfth

**Comment by CannotTouch** [comment]
i don't know if you have do any changes but with the latest commit https://github.com/datawhores/OF-Scraper/commit/f1e794c6c88352b24988155dc9d6ef1b519bfb5d its stop on the same point

**Comment by CannotTouch** [comment]
I have updated to the 2.1 and no more 429. thanks :)

**Comment by datawhores** [comment]
Oh I assumed you were on the latest version

I actually hadn't made any changes to this yet

**Comment by CannotTouch** [comment]
indeed i had think the same too probably i didn't understand how update correctly... usually i download the latest commit and than i made the `pip install ofscraper`
today watching it don't update nothing and see that you changed the version i have made a `pip install ofscraper==2.1` and finally it update corretly :)

**Comment by CannotTouch** [comment]
just to let you know, i think is related with the timestamp modify... because with it it the "page progess" seems a lot more slowly (but always enought fast to don't complain about) and so probably this "slow" is enought to dont let me fall on the 429 on the user with more tham 950 pages...
