### ISSUE TITLE
[Feature Request]: Add option to configuration for users to automatically scrape

### ISSUE THREAD

**Issue by ondrovic** [datawhores/OF-Scraper#65]
Can you add a couple of configuration elements and options so you can have a default scrape list something like this

```json
"automatic": {
  "users": [
     "userone",
     "usertwo",
      .....
   ], 
  "types":  [
   "all"
  ]
}

```

`users` should check any subscription type

`types` would be, specify all or any combination but not `all` to anything else

```
all - = to doing a ctrl+r
timeline
pinned
archived
highlights
stories
messages
purchases
```

**Comment by datawhores** [comment]
Yeah this feature has been asked for before
Honestly I am against added this to the main config

Because right now It fairly easy to understand, and at this point we do have quite a bit of different options available. But I do see this as being a useful feature to have.

What I could do is instead have this be an additional arg example
--auto-args file

This way you could load any arg you wanted, not just the ones you listed
Also you would be able to have multiple

**Comment by CannotTouch** [comment]
or instead of external list the possibility to scrape people that are in a specific list on the site :)

**Comment by RonnieBlaze** [comment]
I came looking about the same thing the OP did, and found the command line args just like they did.. its been working great.. except i can not figure out how to stop it from looking at accounts that are not active. "Subscription Active: False"  I have tried adding the "--sub-status active" flag but that did not do it..  

My running command is "ofscraper --posts all --username user1,user1,etc,etc"

**Comment by 6R1M4C3** [comment]
> I'm creating reference page https://github.com/datawhores/OF-Scraper/wiki/Command-Reference which should help with creating the correct command

if I use this to content check a deleted model that I have purchased from it throws a lot of errors doesn't even find anything, and the normal scrape method doesn't have them listed on the subpage or expired page either, is there a reason even with the model number it cant find the content?

**Comment by datawhores** [comment]
I will allow users to great there own scripts for this
But the program has gotten quite complicated for this to make sense
