### ISSUE TITLE
[Feature Request] Change image saving format

### ISSUE THREAD

**Issue by distantowl** [datawhores/OF-Scraper#68]
Any way to chose between saving images as .jpg vs .jpeg? I could go through and convert all files to one or another but being able to save everything as a .jpg instead would be super helpful.

**Comment by cjb900** [comment]
Why do you want to save images a .jpg when there is really no difference in image quality or file size between jpg and jpeg?

**Comment by datawhores** [comment]
I don't make the extension
they come directly from only fans
