### ISSUE TITLE
Duplication of content folders

### ISSUE THREAD

**Issue by Bun-Bun** [datawhores/OF-Scraper#70]
Since updating a few days ago I have all my media folders duplicated. 

First time running the script on May 21st all the media folders were created with capital first letter. Messages, Posts, Profile etc. Since updating on June 3rd I have new folders all lower case. 

EDIT: 

The folders underneath those still have capital first letter (the {mediatype} folders)

**Comment by datawhores** [comment]
Change response mapping it is now cade sensitive read the wiki page about save path

**Comment by Bun-Bun** [comment]
Okay, but your change has made the folders unreadable by samba shares from other OSes. Couldn't have added some checks when making that change as it was your generated config file that had lower case in it? (I was using the defaults).

**Comment by datawhores** [comment]
You can redownload files from recent with 
ofscraper --after 2023.04.01 --dupe

It was in the release notes
But a change like this should have had more warnings and allowed people time to adapt.
I'll make sure to keep this in mind for the future
