### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by Jodc2** [datawhores/OF-Scraper#73]
I tested it under the same conditions and OF-Scraper gives 2-3MB/s while the original onlyfans-scraper gives 10-15MB/s 
I'm talking about each file
Downloading with the original onlyfans-scraper is much faster
How can this be fixed?
Thanks

**Comment by datawhores** [comment]
Please mention what version you are on

**Comment by Jodc2** [comment]
> 2.1

**Comment by datawhores** [comment]
Are you outputting to discord by chance

**Comment by Jodc2** [comment]
Yes, I run the script with the command ofscraper -dc STATS

**Comment by Jodc2** [comment]
I tried without -dc STATS and nothing changed

**Comment by datawhores** [comment]
I have a branch with aiohttp instead of httpx for request.
It would be better to do some sort of average of the speeds.

So I'm planning on recording the difference in completion time between different changes

**Comment by datawhores** [comment]
Do you know where it fails
it weird that this only happens with purchased content

As all content goes through the same downloader in the end, after scraping

**Comment by Jodc2** [comment]
I just chose to download only purchased content and it did not download anything then I immediately switched to version 2.1 and it downloaded everything fine

**Comment by Jodc2** [comment]
I checked the speed on 2.4 and it still does not go higher than 4.5 MB/s

**Comment by datawhores** [comment]
I haven't changed the downloader 
In going to add that in a patch after more testing.

**Comment by Jodc2** [comment]
Okay, thanks :)

**Comment by datawhores** [comment]
I switched the engine
