### ISSUE TITLE
Problem scraping one creator; others work fine

### ISSUE THREAD

**Issue by eeged** [datawhores/OF-Scraper#74]
I'm using version 2.1, and it's working fine for all creators I've tried except one. It doesn't seem to properly detect their content when trying to scrape their timeline, and downloads only a few videos before stopping. The files it does download are separate video and audio tracks with random names; it doesn't combine or rename them.

The only obvious difference I can see is that the creators name has a "." in it (by which I mean their username is "user.name"). Could this be causing issues with the script?

**Comment by ctrlcmdshft** [comment]
upgrade and try one of the newer versions 2.1 is old

**Comment by datawhores** [comment]
I would run with 
--output debug to see where it is failing

sounds like there might be multiple failures

**Comment by datawhores** [comment]
were you able to try this again?
