### ISSUE TITLE
Update istruction

### ISSUE THREAD

**Issue by CannotTouch** [datawhores/OF-Scraper#79]
Can you insert in the Readme.md the correct procedure to update, please?

Till now i can update it only when you do some release using `pip install ofscraper==x` 

thanks for support

**Comment by CannotTouch** [comment]
p.s. i'm on 2.4.1 because 2.4.2 don't like the latest 3.11.4 python version

**Comment by ctrlcmdshft** [comment]
`pip install ofscraper --upgrade` is the proper command
