### ISSUE TITLE
not downloading paid messages

### ISSUE THREAD

**Issue by Kokorin50** [datawhores/OF-Scraper#80]
hi
it doesn't download paid messages. is there anyone who can help about this issue?

**Comment by datawhores** [comment]
Can you run with --output debug

You can also run with 
--output debug --dupe 
to make sure the dupe catcher is not getting the file

**Comment by Kokorin50** [comment]
I don't understand what you mean, I'm sorry, can you share with visual explanation, I'm new in this field, thank you

**Comment by datawhores** [comment]
ofscraper --output debug 
of that doesn't work
ofscraper --output debug --dupe

**Comment by Kokorin50** [comment]
Post downloading but not downloading locked messages 
![16871644780333973883833854218556](https://github.com/datawhores/OF-Scraper/assets/136534713/750f4fcf-6713-41f6-920d-e0e7480e0717)

**Comment by datawhores** [comment]
Have you unlocked them?

Do they show up on your purchase tab on onlyfans.com?

**Comment by Kokorin50** [comment]
I have a subscription to the user, he only downloads the posts on his wall, except for the locked ones

**Comment by datawhores** [comment]
> I have a subscription to the user, he only downloads the posts on his wall, except for the locked ones
and you've unlocked them?

**Comment by Kokorin50** [comment]
Except for locked messages

**Comment by datawhores** [comment]
Like I said this script can not downloaded locked messages
You will have to unlock them first

**Comment by Kokorin50** [comment]
Do you know any other way to download it?

**Comment by datawhores** [comment]
You can look
but I doubt there is any public way of downloaded content that is still locked
