### ISSUE TITLE
Missing metadata on DRM files

### ISSUE THREAD

**Issue by bluman181** [datawhores/OF-Scraper#81]
Not sure if this is a feature or anything, but for the past few weeks I noticed the DRM .mp4 are missing metadata (unable to see file preview on the right side of file explorer) anyway to get that data back on the files?

**Comment by datawhores** [comment]
Might be something that needs to be added if possible

The only data that is changed currently is the date of files, so they match with the post date of the content

**Comment by datawhores** [comment]
The metadata should still be there it is just the incorrect file extension I pushed a fix, and will be adding a remedy for current files
