### ISSUE TITLE
Assuming --config/--auth is in $HOME

### ISSUE THREAD

**Issue by ResidentSpaceDragon** [datawhores/OF-Scraper#88]
Using the new --auth and --config options it is assuming, on linux, that the config files are located in $HOME instead of $HOME/.config/ofscraper (where the main_profile information is generated) and erroring out when it does not find them and creates a new folder for you in $HOME.
The $HOME/.config/ofscraper folder should be the default location that it looks in.

**Comment by datawhores** [comment]
What are you passing 
Is is the full path to config and auth or relative paths

**Comment by ResidentSpaceDragon** [comment]
I was assuming it was a relative path working out of the ofscraper config folder (as does the main_profile folder/files)
Calling ofscraper with no arguments uses $HOME/.config/ofscraper/main_profile without having to run ofscraper from within the .config/ofscraper folder,can the --auth and --config options be actioned the same way before looking for an absolute path?

Command
```
ofscraper -u model --config config-b -auth auth-b
```

**Comment by datawhores** [comment]
I think that only works if you make the folder before hand 

Otherwise I have to assume you want it at root

This also has to work for other people and not just your use case

**Comment by datawhores** [comment]
I think that only works if you make the folder before hand 

Otherwise I have to assume you want it at root

This also has to work for other people and not just your use case

**Comment by datawhores** [comment]
I think I'm just going to make a prompt for this. 

It will help with this ambiguous causes

**Comment by ResidentSpaceDragon** [comment]
Well its just following the already established flow of the program. If you are on linux and are running the program the first time following the prompts your main_profile folder is made in $HOME/.config/ofscraper by default on first run and your auth and config files go there as well. Then running ofscraper -u model parses $HOME/.config/ofscraper/main_profile without any prompts or input from the user. It makes sense that alternative config/auth files would be present in the same config folder that the program is already looking at by default.

**Comment by datawhores** [comment]
Working on the auth part but these are the rules for config

https://of-scraper.gitbook.io/of-scraper/batch-scraping-and-bot-actions/advanced-args#multiple-configs

I'm enforcing some hard rules about what is allowed in the --config argument

For a path to be interpreted as a config_file it needs a extension. Otherwise the config.json will be made inside of the argument passed

Also single files with no root get put in the default ofscraper folder

So in your case you need to pass
--config test.json or something with a extension
so that it gets put in the ofscraper config folder

If you pass 
--config /home/me/test.json 
that will be put  the config_file at
/home/me/test.json 
and the profiles at
/home/me/

**Comment by datawhores** [comment]
I've removed the --auth arg
profiles are the way the program handles multiple accounts

saying that if you want to change from the default profile in the config use the 
--profile arg

**Comment by ResidentSpaceDragon** [comment]
--profile seems to be misconfigured as using it results in the following
```
ofscraper -u model --profile profile-2 --config config-b -o purchased
```
```
ofscraper: error: argument command: invalid choice: 'profile-2' (choose from 'post_check', 'msg_check', 'paid_check', 'story_check'
```

"profile-2" being a folder in $HOME/.config/ofscraper with an auth.json file within it that is different then main_profile

**Comment by datawhores** [comment]
Are you on windows

**Comment by datawhores** [comment]
I did a test on a machine that hadn't been updated. I got the same error
try 
ofscraper --profile
It should say
OF-Scraper: error: argument -r/--profile: expected one argument

This came after the 2.5 release so you need to update to a repo version

**Comment by ResidentSpaceDragon** [comment]
> Are you on windows

No,linux

> This came after the 2.5 release so you need to update to a repo version

This was a fresh git pull minutes before i posted. I just pulled again to 9afb76e and the same error message happens

> -r

It seems -r is misconfigured as well as it gives this error
```
ofscraper: error: argument -rw/--renewal: invalid choice: 'profile-2' (choose from 'active', 'disabled')
```

**Comment by datawhores** [comment]
Did you pip uninstall before upgrading 
both commands work on my local machine

**Comment by datawhores** [comment]
I pushing a new release soon anyways
also you need to pass
--config config-b.json

Or some file with an extension
