### ISSUE TITLE
Create a profile exits program (v2.5)

### ISSUE THREAD

**Issue by Jules-WinnfieldX** [datawhores/OF-Scraper#91]
I often have multiple accounts and I assume the way this is meant to be handled with OFScraper is through profiles. Going through the GUI to create a new profile causes the program to exit (most likely error out, however no error is displayed)

Unsure if there is logging that I should provide, but I'm assuming this will be fairly easily reproducible.

edit: As an easy place to ask this, when running a command such as `ofscraper --username ALL --sub-status active --posts all --skip-timed` with multiple profiles, is only the default profile processed, or are all profiles? Is there a way to indicate which to process? I couldn't find info on this in the wiki.

**Comment by datawhores** [comment]
Only th main profile
I'm adding a profile arg soon

It will be stated in the commit

**Comment by datawhores** [comment]
This should be fixed there is also a new 
--profile arg that will auto create a profile or use an existing one

**Comment by Jules-WinnfieldX** [comment]
I'm hoping --profile will accept `all`, that possible?

**Comment by datawhores** [comment]
I'm not sure what all would do

But the program is really built right now for having one active account
So any command using multiple for scanning media without some sort of user switch 

It one of those things that would have to be a mini-project of its own

**Comment by Jules-WinnfieldX** [comment]
Ahh fair, While running multiple accounts I like being able to scrape all at a single time. I can just adjust my start script and have it run a command for each account. It's no biggie
