### ISSUE TITLE
Not Downloading all content?

### ISSUE THREAD

**Issue by god43** [datawhores/OF-Scraper#94]
so ive set up the scrapper and my config, i am trying to dl one model but its not dling the photo's or stories, its only dling "some video's" (not all videos)?

"{
    "config": {
        "main_profile": "main_profile",
        "save_location": "E:\\OF-Scraper-main\\Sites",
        "file_size_limit": 0,
        "dir_format": "{model_username}/{responsetype}/{mediatype}/",
        "file_format": "{filename}.{ext}",
        "textlength": "0",
        "space-replacer": " ",
        "date": "MM-DD-YYYY",
        "metadata": "E:\\OF-Scraper-main\\Metadata\\{model_username}_{model_id}",
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "threads": "10",
        "code-execution": true,
        "mp4decrypt": "E:\\OF-Scraper-main\\bin\\mp4decrypt.exe",
        "ffmpeg": "E:\\OF-Scraper-main\\bin\\ffmpeg.exe",
        "discord": "",
        "responsetype": {
            "timeline": "Posts",
            "archived": "Archived",
            "pinned": "Posts",
            "message": "Messages",
            "paid": "Paid",
            "stories": "Stories",
            "highlights": "Highlights",
            "profile": "Profile"
        }
    }
}"

**Comment by datawhores** [comment]
please run 
ofscraper output --debug

**Comment by datawhores** [comment]
Also please not that any locked content will not download until unlocked

**Comment by god43** [comment]
it does not seem to like that command

PS E:\OF-Scraper-main> ofscraper output --debug
usage: OF-Scraper [-v] [-cg CONFIG] [-au AUTH] [-l {OFF,STATS,LOW,NORMAL,DEBUG}] [-dc {OFF,STATS,LOW,NORMAL,DEBUG}]
                  [-p {PROMPT,STATS,LOW,NORMAL,DEBUG}] [-h] [-u USERNAME] [-eu EXCLUDED_USERNAME] [-d DAEMON] [-g]
                  [-e] [-o POSTS] [-c] [-a {like,unlike}] [-sk] [-ft FILTER] [-sp] [-at {paid,free}]
                  [-rw {active,disabled}] [-ss {active,expired}] [-be BEFORE] [-af AFTER]
                  [-st {Name,Subscribed,Expiring,Price}] [-ds] [-uf] [-nc]
                  {post_check,msg_check,paid_check,story_check,manual} ...

**Comment by datawhores** [comment]
ofscraper --output debug

**Comment by god43** [comment]
oh oops thanks

**Comment by god43** [comment]
is this what you wanted from the output?

DEBUG    Messages Count with Dupes 124 found                                                            messages.py:104
DEBUG    Some messages where not retrived resetting cache                                               messages.py:120
DEBUG    Messages Media Count with locked 48                                                                   of.py:39
DEBUG    Removing locked messages media                                                                        of.py:40
DEBUG    offset:0 -> media found 17                                                                         paid.py:104
DEBUG    offset:0 -> hasmore value in json False                                                            paid.py:105
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
DEBUG    Paid Post count without Dupes 17 found                                                              paid.py:77
DEBUG    Paid Media Count with locked 24                                                                       of.py:51
DEBUG    Removing locked paid media                                                                            of.py:52
DEBUG    Highlight Post Count without Dupes 2 found                                                    highlights.py:83
DEBUG    Story Post Count without Dupes 0 found                                                        highlights.py:84
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
DEBUG    Combined Story and Highlight Media count 0                                                            of.py:66
Removing duplicate media                                                                                  filters.py:29
DEBUG    Combined Media Count with dupes  1310                                                            filters.py:30
DEBUG    Combined Media Count without dupes 1220                                                          filters.py:35
filtering Media to images,audios,videos                                                                   filters.py:64
Skipping previously downloaded                                                                           download.py:87
Media left for download 28

**Comment by god43** [comment]
DEBUG    Namespace(version='2.5+main.588bc4d', config=None, auth=None, log='OFF', discord='OFF',            start.py:11
         output='DEBUG', username=set(), excluded_username=set(), daemon=None, original=False, dupe=False,
         posts=[], letter_count=False, action=None, skip_timed=None, filter='.*', scrape_paid=False,
         account_type=None, renewal=None, sub_status=None, before=None, after=None, sort='name',
         desc=False, users_first=False, no_cache=False, command=None)
Welcome to OF-Scraper Version 2.5+main.588bc4d


- 1141 posts
 -- 269 photos
 -- 929 videos
 -- 0 audios
- 9 archived posts

**Comment by datawhores** [comment]
So the target media count for timeline post is

**Comment by god43** [comment]
its  1310

**Comment by god43** [comment]
im running it again

**Comment by god43** [comment]
DEBUG    Timeline Count with Dupes 1138 found                                                           timeline.py:149
DEBUG    Timeline Count without Dupes 1138 found                                                        timeline.py:156
DEBUG    Timeline Media Count with locked 1195                                                                 of.py:88
DEBUG    Removing locked timeline media                                                                        of.py:89
DEBUG    Archived Cache 9 found

**Comment by god43** [comment]
1195 posts are not locked

**Comment by datawhores** [comment]
in the first run you had

**Comment by datawhores** [comment]
Which is why it said

Skipping previously downloaded download.py:87
Media left for download 28

**Comment by god43** [comment]
so its an issue with the dupe checker? it hasnt downloaded anything though, no pictures at all. i deleted the metadata file as well. yeah i cam coming from DC, looks like the version is 2.5, and i installed from pip.

**Comment by datawhores** [comment]
Did you delete the entire folder?

If not can you rename E:\OF-Scraper-main\Metadata\ E:\OF-Scraper-main\Metadata2\

run the script again and see if you still have the issue

**Comment by god43** [comment]
ok ill try that and let you know, but i deleted everything in the folder, so it should be gone, but ill delete the folder and recreate it.

**Comment by god43** [comment]
ok im going to run it now, btw any way i can get the folders to match the same as DC? like in his script he has content separated by paid and free?

**Comment by god43** [comment]
huh that's weird, it looks like it was actually working, but then it looks like it got stuck and its just hanging there not doing anything?

Progress: (280 photos, 897 videos, 0 audios,  0 skipped || 1177/1223||12.92 GB)

**Comment by datawhores** [comment]
use the value placeholder in the config
https://of-scraper.gitbook.io/of-scraper/config-options/customizing-save-path
{value}

**Comment by datawhores** [comment]
most of the other downloads work so it probably means
A. onlyfans is taking a bit longer to respond from these requests
B. the requests error out, so it needs to wait to retry again

**Comment by god43** [comment]
i tried running it again with debug off and it completed successfully, thanks.

are you saying i would use {value} in the response types?

like Messages/{value}

**Comment by god43** [comment]
or are you saying i would put value in the dir format?

**Comment by datawhores** [comment]
Yes in the dir format it gets replaced when downloading with free or paid

**Comment by god43** [comment]
so does this make sense?

        "dir_format": "{model_username}/{responsetype}/{value}/{mediatype}/",

**Comment by god43** [comment]
thanks

**Comment by god43** [comment]
you may want to update this to reflect that. thanks

https://of-scraper.gitbook.io/of-scraper/migrating-from-digitalcriminals-script

**Comment by god43** [comment]
what happens if
