### ISSUE TITLE
scanning everypage each time?

### ISSUE THREAD

**Issue by god43** [datawhores/OF-Scraper#95]
why does the scrapper scan every page each time, should it only scan what ever is different from the metadata? its seems like each time i run the script its going through each page? thanks.

**Comment by datawhores** [comment]
If you don't want to do a full scan pass the --after argument
https://of-scraper.gitbook.io/of-scraper/batch-scraping-and-bot-actions/selecting-posts#dehumanize-strings

**Comment by datawhores** [comment]
ofscraper --after "1 month ago"
that way you don't have to keep calculating the date

**Comment by god43** [comment]
hmm i think it should automatically just check for only new content based on the previous scan. like if we need a full scan we can just delete the metadata file, like DC's script. ok well thanks i guess ill wait for it to finish.

**Comment by datawhores** [comment]
If you need to do a full scan 
ofscraper --dupe will skip checking the database 

You should not have to touch the db files ever

**Comment by PsychoSid** [comment]
Just a suggestion but I wrap my runs in a simple bash script to write out a file with the date in of the run so I can pass that back in as the `--after` statement.

Wonder if that is worth doing "built in" ?
