### ISSUE TITLE
Bug - Program Hangs After Keyboard Interrupt

### ISSUE THREAD

**Issue by slitchampion** [datawhores/OF-Scraper#96]
Running on Ubuntu 22.04.2 with the program in daemon mode. Entering keyboard interrupt after a run (ctrl + c) creates two messages, "Cleaning up temp files" and then "Pushing Discord Queue," but then program never actually exits and hangs after the Discord message. Have waited up to 30 minutes with no change. A second keyboard interrupt will exit the program.

**Comment by datawhores** [comment]
python actually has a queuemanager for logs so I didn't have to make my own.

There has been some improvements in how the shutdown process is handled
In my testing in most causes in when running in daemon the keyboard is able to send the signal to all threads and running processes and succesfully shutdown
