### ISSUE TITLE
Database Locked (Release 2.6)

### ISSUE THREAD

**Issue by Jarsky** [datawhores/OF-Scraper#97]
Just ran an update, when trying to access any model; it gives this error:

```
DEBUG    Init username length: 61                                                                                                                   userselector.py:95
DEBUG    final length with all filters: 61                                                                                                         userselector.py:122
? Which models do you want to scrape
: modelnamexxxx
DEBUG    Getting content+downloading 1/1 model                                                                                                          scraper.py:164
DB may be locked                                                                                                                                      operations.py:29
TRACEBACK failed with exception: unable to open database file                                                                                           scraper.py:178
TRACEBACK Traceback (most recent call last):                                                                                                            scraper.py:179
            File "/root/ofscraper/ofscraper/commands/scraper.py", line 170, in normal_post_process                                                                    
              operations.write_profile_table(model_id,ele['name'])                                                                                                    
            File "/root/ofscraper/ofscraper/db/operations.py", line 30, in inner                                                                                      
              raise E                                                                                                                                                 
            File "/root/ofscraper/ofscraper/db/operations.py", line 27, in inner                                                                                      
              return func(*args,**kwargs)                                                                                                                             
            File "/root/ofscraper/ofscraper/db/operations.py", line 184, in write_profile_table                                                                       
              cur.execute(queries.profileUpdate,insertData)                                                                                                           
          sqlite3.OperationalError: unable to open database file                       
```

**Comment by valdearg** [comment]
Seem to be getting this one myself a lot, here's the debug:

![image](https://github.com/datawhores/OF-Scraper/assets/2789033/95a08e3a-22c4-4ca7-9ac9-e0921e3de74e)

I don't think the database is specifically locked, usually there's a db-journal file, but the metadata database seems quite happy.

**Comment by datawhores** [comment]
I don't think it is locked in this case
What do you have for your config

**Comment by valdearg** [comment]
```
{
    "config": {
        "main_profile": "main_profile",
        "save_location": "G:/Scripts/OnlyFans/.sites/OnlyFans-new2",
        "file_size_limit": 0,
        "dir_format": "{model_username}/{responsetype}/{mediatype}/{post_id} ({date})",
        "file_format": "{filename}.{ext}",
        "textlength": 0,
        "space-replacer": " ",
        "date": "DD-MM-YYYY",
        "metadata": "G:/Scripts/OnlyFans/.sites/OnlyFans-new2/{model_username}/Metadata",
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "threads": 8,
        "code-execution": false,
        "mp4decrypt": "G:\\Scripts\\ofscraper\\OF-Scraper\\bin\\mp4decrypt.exe",
        "ffmpeg": "G:\\Scripts\\ofscraper\\OF-Scraper\\bin\\ffmpeg.exe",
        "discord": "https://discord.com/fgklhjgfkl",
        "responsetype": {
            "timeline": "posts",
            "message": "messages",
            "archived": "archived",
            "paid": "paid",
            "stories": "stories",
            "highlights": "highlights",
            "profile": "profile",
            "pinned": "archived"
        }
    }
}
```

**Comment by jcisz** [comment]
i'm getting the same error as [valdearg](https://github.com/valdearg), downgraded to `2.5` and it worked again. I'm on windows using pipx

**Comment by Jarsky** [comment]
I also downgraded to 2.5 which resolved the issue. But i've upgraded with later builds since 2.6, and its still working so im going to go ahead and close this.

**Comment by doublepedaldylan** [comment]
I am on 2.6.4 and getting "DB may be locked" errors, skipping lots of downloads. Will try downgrading, but here's one section of debug where it happens:

`DEBUG     [download.download:150]  Media:2757790607 Post:504249779  exception Traceback (most recent call last):                                                                                                                                               download.py:150
           File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\ofscraper\utils\download.py", line 143, in download
             return await main_download_helper(c,ele,pathlib.Path(".").absolute(),file_size_limit,username,model_id,progress)
           File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\ofscraper\utils\download.py", line 179, in main_download_helper
             operations.write_media_table(ele,path_to_file,model_id,username)
           File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\ofscraper\db\operations.py", line 30, in inner
             raise E
           File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\ofscraper\db\operations.py", line 27, in inner
             return func(*args,**kwargs)
           File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\ofscraper\db\operations.py", line 135, in write_media_table
             with contextlib.closing(sqlite3.connect(datebase_path,check_same_thread=False)) as conn:
         sqlite3.OperationalError: unable to open database file`

**Comment by datawhores** [comment]
I switch to aiosqlite in the repo version because it seems to handle the code better
